# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rating.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0crating.proto*\xa7\x03\n\x06Rating\x12\x0f\n\x0bUNAVAILABLE\x10\x00\x12\x0c\n\x08TERRIBLE\x10\x01\x12\x18\n\x14TERRIBLE_TO_VERY_BAD\x10\x02\x12\x0c\n\x08VERY_BAD\x10\x03\x12\x13\n\x0fVERY_BAD_TO_BAD\x10\x04\x12\x07\n\x03\x42\x41\x44\x10\x05\x12\x15\n\x11\x42\x41\x44_TO_PRETTY_BAD\x10\x06\x12\x0e\n\nPRETTY_BAD\x10\x07\x12\x18\n\x14PRETTY_BAD_TO_DECENT\x10\x08\x12\n\n\x06\x44\x45\x43\x45NT\x10\n\x12\x19\n\x15\x44\x45\x43\x45NT_TO_PRETTY_GOOD\x10\x0b\x12\x0f\n\x0bPRETTY_GOOD\x10\x0c\x12\x17\n\x13PRETTY_GOOD_TO_GOOD\x10\r\x12\x08\n\x04GOOD\x10\x0e\x12\x15\n\x11GOOD_TO_VERY_GOOD\x10\x0f\x12\r\n\tVERY_GOOD\x10\x10\x12\x16\n\x12VERY_GOOD_TO_GREAT\x10\x11\x12\t\n\x05GREAT\x10\x12\x12\x17\n\x13GREAT_TO_INCREDIBLE\x10\x13\x12\x0e\n\nINCREDIBLE\x10\x14\x12\x1b\n\x17INCREDIBLE_TO_BRILLIANT\x10\x15\x12\r\n\tBRILLIANT\x10\x16\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rating_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _RATING._serialized_start=17
  _RATING._serialized_end=440
# @@protoc_insertion_point(module_scope)
