title: "Rogue One: A Star Wars Story"
rating: 8.5
review: "Final Third of the movie was amazing, great action, great plot, has a gradual progression from slow to fast pace, not a memorable cast due to the fact that they all die."
release_year: 2016
review_date: "01/06/2017"
redux: false
