title: "Zoolander"
rating: 7.1
review: "Decent Direction, Pretty Funny acting (Though very stupid), Decent story, Pretty Funny movie (Even though its so dumb why its funny), Runtime was short but every minute was used effectively (nothing needed to be added/cut). Overall, a pretty funny movie overall even though it was incredibly stupid."
release_year: 2001
review_date: "07/03/2021"
redux: false
