title: "Deadpool"
rating: 0.1
review {
  direction {
    director {
      name: "Tim Miller"
    }
    rating: "TODO"
    comments: "macroscale is; microscale is; direction of actors is; storytelling is; tension is"
  }
  acting {
    performance {
      actor {
        name: "Ryan Reynolds"
      }
      rating: "TODO"
      comments: "TODO"
    }
    performance {
      actor {
        name: "Morena Baccarin"
      }
      rating: "TODO"
      comments: "TODO"
    }
    performance {
      actor {
        name: "Ed Skrein"
      }
      rating: "TODO"
      comments: "TODO"
    }
    performance {
      actor {
        name: "T. J. Miller"
      }
      rating: "TODO"
      comments: "TODO"
    }
    performance {
      actor {
        name: "Gina Carano"
      }
      rating: "TODO"
      comments: "TODO"
    }
    performance {
      actor {
        name: "Brianna Hildebrand"
      }
      rating: "TODO"
      comments: "TODO"
    }
    cast {
      rating: "TODO"
      comments: "TODO"
    }
    rating: ""
  }
  story {
    writer {
      name: "Rhett Reese"
    }
    writer {
      name: "Paul Wernick"
    }
    rating: "TODO"
    comments: "The concept is; the plot structure is; flow between sequences is; character writing is"
  }
  screenplay {
    writer {
      name: "Rhett Reese"
    }
    writer {
      name: "Paul Wernick"
    }
    rating: "TODO"
    comments: "The dialogue is; the humor is; the symbolism is; the foreshadowing is"
  }
  score {
    composer {
      name: "Tom Holkenborg"
    }
    rating: "TODO"
    comments: "TODO"
  }
  cinematography {
    cinematographer {
      name: "Ken Seng"
    }
    rating: "TODO"
    comments: "TODO"
  }
  editing {
    editor {
      name: "Julian Clarke"
    }
    rating: "TODO"
    comments: "TODO"
  }
  sound {
    rating: "TODO"
    comments: "TODO"
  }
  visual_effects {
    rating: "TODO"
    comments: "TODO"
  }
  production_design {
    rating: "TODO"
    comments: "TODO"
  }
  makeup {
    rating: "TODO"
    comments: "TODO"
  }
  costumes {
    rating: "TODO"
    comments: "TODO"
  }
  pacing: "Pacing "
  climax: "Climax "
  tone: "Tone "
  final_notes: ""
  overall: "Overall, "
}
release_year: 2016
review_date: "07/23/2024"
redux: false
id: 471
imdb_id: "tt1431045"
