title: "Dune"
rating: 7.8
review {
  direction {
    director {
      name: "Denis Villeneuve"
    }
    rating: "Good to Very Good"
    comments: "Was able to manage the grand scenes very well and did a decent job with the interpersonal scenes"
  }
  acting {
    performance {
      actor {
        name: "Timoth\303\251e Chalamet"
      }
      rating: "Pretty Good"
    }
    performance {
      actor {
        name: "Rebecca Ferguson"
      }
      rating: "Pretty Bad to Decent"
    }
    performance {
      actor {
        name: "Oscar Isaac"
      }
      rating: "Good"
    }
    performance {
      actor {
        name: "Josh Brolin"
      }
      rating: "Good"
    }
    performance {
      actor {
        name: "Stellan Skarsg\303\245rd"
      }
      rating: "Good"
    }
    performance {
      actor {
        name: "Jason Momoa"
      }
      rating: "Good"
    }
    performance {
      actor {
        name: "Javier Bardem"
      }
      rating: "Good"
    }
    rating: "Pretty Good to Good"
  }
  story {
    writer {
      name: "Jon Spaihts"
    }
    writer {
      name: "Denis Villeneuve"
    }
    writer {
      name: "Eric Roth"
    }
    rating: "Bad"
    comments: "Bad storytelling as the exposition does a very poor job of explaining the backstory"
  }
  screenplay {
    writer {
      name: "Jon Spaihts"
    }
    writer {
      name: "Denis Villeneuve"
    }
    writer {
      name: "Eric Roth"
    }
    rating: "Pretty Good to Good"
  }
  score {
    composer {
      name: "Hans Zimmer"
    }
    rating: "Great"
  }
  cinematography {
    cinematographer {
      name: "Greig Fraser"
    }
    rating: "Great"
  }
  editing {
    editor {
      name: "Joe Walker"
    }
    rating: "Good"
    comments: "Though it made the movie more confusing when it cut between dreams and reality"
  }
  sound {
    rating: "Great"
  }
  visual_effects {
    rating: "Great"
  }
  production_design {
    rating: "Good"
  }
  plot_structure: "Plot Structure very skewed because this is one part of a two part movie (First half is the exposition and second half is rising action)"
  pacing: "Pacing was Very Slow (The first half is incredibly slow while the second half is pretty slow)"
  climax: "Climax for this movie is not that significant because it is meant to be a rise in the conflict for the next movie"
  overall: "Overall, a movie with great visuals and the presentations of a great space epic that acts as more of a prologue and beginning of a story than a full movie, though it does suffer from bad storytelling that makes the movie hard to follow; hopefully, this means that this part one sets up part two to be a better movie"
}
release_year: 2021
review_date: "10/31/2021"
redux: false
id: 223
imdb_id: "tt1160419"
