title: "Home Alone"
rating: 8.8
review {
  direction {
    director {
      name: "Chris Columbus"
    }
    rating: "Very Good to Great"
    comments: "Able to bring out the humor and joy in many moments, helps set the lighthearted tone that kevin brings throughout the movie"
  }
  acting {
    performance {
      actor {
        name: "Macaulay Culkin"
      }
      rating: "Great"
      comments: "Able to bring the charm the movie is known for"
    }
    performance {
      actor {
        name: "Joe Pesci"
      }
      rating: "Great"
      comments: "Able to bring the charm the movie is known for"
    }
    performance {
      actor {
        name: "Daniel Stern"
      }
      rating: "Very Good"
      comments: "The good comedic relief to the comedic relief from joe pesci"
    }
    performance {
      actor {
        name: "Catherine O\'Hara"
      }
      rating: "Good to Very Good"
    }
    cast {
      rating: "Decent to Pretty Good"
    }
    rating: "Pretty Good to Good"
  }
  story {
    writer {
      name: "John Hughes"
    }
    rating: "Great to Incredible"
    comments: "Something that was very unique and iconic for the time as it takes the christmas movie genre to new heights"
  }
  screenplay {
    writer {
      name: "John Hughes"
    }
    rating: "Very Good to Great"
    comments: "Filled with iconic lines but the actual dialogue is pretty simple (mostly due to the movie staring a child and it being a family movie)"
  }
  score {
    composer {
      name: "John Williams"
    }
    rating: "Incredible"
    comments: "One of john williams most iconic works"
  }
  cinematography {
    cinematographer {
      name: "Julio Macat"
    }
    rating: "Good"
  }
  sound {
    rating: "Good"
  }
  plot_structure: "Plot Structure was very nicely laid out as there are no real wasted scenes in developing the story"
  pacing: "Pacing was great as it was a steady pace that used its runtime very nicely"
  climax: "Build to the climax was great as it helped tie loose ends in Kevin\'s fears of being alone and with the old man; climax is the most iconic part of the movie as it shows Kevin against the Wet Bandits as he lays the house out with traps to defend himself and show how he is not afraid anymore"
  overall: "Overall, one of the best christmas movies ever made as we get to see the iconic elements carried out by Culkin and the wet bandits as they navigate through the different traps and high jinks, and I would rate this movie higher but I personally prefer the sequel more due to personal reasons"
}
release_year: 1990
review_date: "12/25/2021"
redux: false
id: 234
imdb_id: "tt0099785"
