title: "Home Alone 2: Lost in New York"
rating: 9.0
review: "Great Acting By Culkin and Pesci, Very Funny, Iconic, Very Fun Movie to watch, Great Score, Great Screenplay, Great Story, Great Sequel."
release_year: 1992
review_date: "01/05/2020"
redux: false
id: 124
imdb_id: "tt0104431"
