title: "Moneyball"
rating: 9.4
review: "Great Acting, Great Story, Great Screenplay but some lines are questionable, Great Score, Very Relatable Movie, Great Job exploring the demons of every character and how almost everyone has something to prove, Ending was kinda out of place."
release_year: 2011
review_date: "06/13/2017"
redux: false
id: 28
imdb_id: "tt1210166"
