title: "Requiem for a Dream"
rating: 8.3
review: "Very good but so fucked up. Acting was great, Screenplay was excellent, Story was excellent, Incredible Score, way to grotesque, jump cuts created a genre."
release_year: 2000
review_date: "10/20/2017"
redux: false
id: 50
imdb_id: "tt0180093"
