title: "The Disaster Artist"
rating: 1.0
review {
  direction {
    director {
      name: "James Franco"
    }
    comments: "Direction ()"
  }
  acting {
    actor {
      name: "James Franco"
      comments: " from James Franco ()"
    }
    actor {
      name: "Dave Franco"
      comments: " from Dave Franco ()"
    }
    actor {
      name: "Seth Rogen"
      comments: " from Seth Rogen ()"
    }
    actor {
      name: "Alison Brie"
      comments: " from Alison Brie ()"
    }
    actor {
      name: "Ari Graynor"
      comments: " from Ari Graynor ()"
    }
    actor {
      name: "Josh Hutcherson"
      comments: " from Josh Hutcherson ()"
    }
    actor {
      name: "Jacki Weaver"
      comments: " from Jacki Weaver ()"
    }
    cast: "from the rest of the cast ()"
    comments: " Acting"
  }
  story {
    writer {
      name: "Scott Neustadter"
    }
    writer {
      name: "Michael H. Weber"
    }
    comments: "Story ()"
  }
  screenplay {
    writer {
      name: "Scott Neustadter"
    }
    writer {
      name: "Michael H. Weber"
    }
    comments: "Screenplay ()"
  }
  score {
    composer {
      name: "Dave Porter"
    }
    comments: "Score ()"
  }
  cinematography {
    cinematographer {
      name: "Brandon Trost"
    }
    comments: "Cinematography ()"
  }
  sound: "Sound ()"
  editing {
    editor {
      name: "Stacey Schroeder"
    }
    comments: "Editing ()"
  }
  visual_effects: "Visual Effects ()"
  production_design: "Production Design ()"
  makeup: "Makeup ()"
  costumes: "Costumes ()"
  plot_structure: "Plot Structure "
  pacing: "Pacing "
  climax: "Climax "
  tone: "Tone "
  final_notes: ""
  overall: "Overall, "
}
release_year: 2017
review_date: "07/24/2023"
redux: true
id: 361
imdb_id: "tt3521126"
