title: "127 Hours"
rating: 8.5
review: "Great Performance by James Franco, Score was great, Direction was great, Story was very good, Very short movie which is a shame because it throws the pacing off for the movie, wanted to see more of the movie but was constrained by the time. "
release_year: 2010
review_date: "12/22/2019"
redux: false
