title: "1917"
rating: 9.2
review: "Incredible Cinematography, Incredible Direction, Great Score, Great realistic visuals, Good Acting, Great Pacing, Cliche War Movie Tropes, Combination of Saving Private Ryan and Dunkirk, decent screenplay, Emotions were conveyed really well, pacing was good."
release_year: 2019
review_date: "01/17/2020"
redux: false
id: 125
imdb_id: "tt8579674"
