title: "28 Days Later"
rating: 7.8
review {
  direction {
    director {
      name: "Danny Boyle"
    }
    rating: "Good"
    comments: "Some times were better than others cause it was a very raw experience overall"
  }
  acting {
    performance {
      actor {
        name: "Cillian Murphy"
      }
      rating: "Very Good"
    }
    performance {
      actor {
        name: "Naomie Harris"
      }
      rating: "Very Good"
    }
    performance {
      actor {
        name: "Megan Burns"
      }
      rating: "Very Bad"
      comments: "Though a child actor so do not take seriously"
    }
    performance {
      actor {
        name: "Brendan Gleeson"
      }
      rating: "Very Good"
    }
    cast {
      rating: "Pretty Good to Good"
    }
    rating: "Good"
  }
  story {
    writer {
      name: "Alex Garland"
    }
    rating: "Good to Very Good"
    comments: "Though the inception of the idea of the virus is a very stupid idea"
  }
  screenplay {
    writer {
      name: "Alex Garland"
    }
    rating: "Good"
  }
  score {
    composer {
      name: "John Murphy"
    }
    rating: "Good to Very Good"
  }
  cinematography {
    cinematographer {
      name: "Anthony Dod Mantle"
    }
    rating: "Very Good to Great"
    comments: "Presents a raw feeling of fear and desolation; though it does help play into the movie reeking of the early 00s"
  }
  editing {
    editor {
      name: "Chris Gill"
    }
    rating: "Bad"
    comments: "The jump cuts and style reeks of the early 00s"
  }
  sound {
    rating: "Very Bad"
    comments: "Inconsistent"
  }
  visual_effects {
    rating: "Very Bad"
    comments: "CGI/effects that reek of the early 00s"
  }
  plot_structure: "Plot Structure was good for the most part (first 5-10 minutes was very bad but rest of the exposition was fine, all other plot points were fine with the climax being good (though the actual storytelling in this part was chaotic), the ending was not necessarily bad but it was extremely safe)"
  pacing: "Pacing was a good steady pace"
  tone: "I liked how the movie had its tone set more to finding hope rather than living in fear"
  final_notes: "The horror elements of the movie were presented very well as there were suspenseful moments (even though it was not a majority of the film)"
  overall: "Overall, a fun watch for a horror movie that makes you care more about the actual plot than the horror elements, even though the movie badly reeks of the early 00s"
}
release_year: 2002
review_date: "10/27/2021"
redux: false
id: 222
imdb_id: "tt0289043"
