title: "A Quiet Place Part II"
rating: 8.5
review {
  direction {
    director {
      name: "John Krasinski"
    }
    rating: "Great"
  }
  acting {
    performance {
      actor {
        name: "Emily Blunt"
      }
      rating: "Very Good"
    }
    performance {
      actor {
        name: "Cillian Murphy"
      }
      rating: "Very Good"
    }
    performance {
      actor {
        name: "Millicent Simmonds"
      }
      rating: "Good"
    }
    performance {
      actor {
        name: "Noah Jupe"
      }
      rating: "Good"
    }
    performance {
      actor {
        name: "John Krasinski"
      }
      rating: "Good"
    }
    rating: "Good to Very Good"
  }
  story {
    writer {
      name: "John Krasinski"
    }
    rating: "Good"
  }
  screenplay {
    writer {
      name: "John Krasinski"
    }
    rating: "Good"
    comments: "Uses less ASL makes the movie a bit more \'Blunt,\' but the movie uses plot points throughout the movie to tie the movie together"
  }
  score {
    composer {
      name: "Marco Beltrami"
    }
    rating: "Decent to Pretty Good"
  }
  cinematography {
    cinematographer {
      name: "Polly Morgan"
    }
    rating: "Great"
  }
  sound {
    rating: "Great to Incredible"
  }
  plot_structure: "Plot Structure was Good"
  pacing: "Short runtime is used effectively as no scene is really unused and there really isn\'t anything that needs to be added/cut"
  climax: "Build to the climax was great with the final 15 minutes being a very well executed sequence that kept me on the edge of my seat"
  final_notes: "The movie was scarier than the first (but uses more jump scares to achieve this); movie sort of ends on a cliff hanger but does have some closure to what will happen to the characters"
  overall: "Overall, a movie that is more of a direct continuation of the first as it uses a larger budget to make a better movie that is scarier, better executed, and a better watch overall (something I hope the spin-off builds on)"
}
release_year: 2020
review_date: "07/22/2021"
redux: false
id: 211
imdb_id: "tt8332922"
