title: "A Quiet Place Part II"
rating: 8.6
review {
  direction {
    director {
      name: "John Krasinski"
    }
    comments: "Great Direction"
  }
  acting {
    actor {
      name: "Emily Blunt"
      comments: "Very Good from Emily Blunt"
    }
    actor {
      name: "Cillian Murphy"
      comments: "Very Good from Cillian Murphy"
    }
    actor {
      name: "Millicent Simmonds"
      comments: "Good from Millicent Simmonds"
    }
    actor {
      name: "Noah Jupe"
      comments: "Good from Noah Jupe"
    }
    actor {
      name: "John Krasinski"
      comments: "Good from John Krasinski"
    }
    cast: ""
    comments: "Good to Very Good Acting"
  }
  story {
    writer {
      name: "John Krasinski"
    }
    comments: "Good Story"
  }
  screenplay {
    writer {
      name: "John Krasinski"
    }
    comments: "Good Screenplay (Uses less ASL makes the movie a bit more 'Blunt,' but the movie uses plot points throughout the movie to tie the movie together)"
  }
  score {
    composer {
      name: "Marco Beltrami"
    }
    comments: "Decent to Pretty Good Score"
  }
  cinematography {
    cinematographer {
      name: "Polly Morgan"
    }
    comments: "Great Cinematography"
  }
  sound: "Great to Incredible Sound"
  plot_structure: "Plot Structure was Good"
  climax: "Build to the climax was great with the final 15 minutes being a very well executed sequence that kept me on the edge of my seat"
  final_notes: "The movie was scarier than the first (but uses more jump scares to achieve this); movie sort of ends on a cliff hanger but does have some closure to what will happen to the characters"
  overall: "Overall, a movie that is more of a direct continuation of the first as it uses a larger budget to make a better movie that is scarier, better executed, and a better watch overall (something I hope the spin-off builds on)"
}
release_year: 2020
review_date: "07/22/2021"
redux: false
