title: "A Quiet Place"
rating: 8.4
review {
  direction {
    director {
      name: "John Krasinski"
    }
    comments: "Good Direction"
  }
  acting {
    actor {
      name: "Emily Blunt"
      comments: "Very Good to Great from Emily Blunt"
    }
    actor {
      name: "John Krasinski"
      comments: "Good to Very Good from John Krasinski"
    }
    cast: ""
    comments: "Good Acting"
  }
  story {
    writer {
      name: "Bryan Woods"
    }
    writer {
      name: "Scott Beck"
    }
    comments: "Good Story"
  }
  screenplay {
    writer {
      name: "Bryan Woods"
    }
    writer {
      name: "Scott Beck"
    }
    writer {
      name: "John Krasinski"
    }
    comments: "Very Good Screenplay (Especially how it uses symbolism along with ASL to tell the story)"
  }
  score {
    composer {
      name: "Marco Beltrami"
    }
    comments: "Decent Score"
  }
  cinematography {
    cinematographer {
      name: "Charlotte Bruus Christensen"
    }
    comments: "Good Cinematography"
  }
  sound: "Great Sound"
  plot_structure: "Plot Structure was Good; Like how the movie ends on a cliff hanger to set up Part 2"
  pacing: "Short runtime is used effectively as no scene is really unused and there really isn\'t anything that needs to be added/cut"
  climax: "Build to the climax was great with the final 20 minutes being a very great executed sequence"
  overall: "Overall, a well made horror film on the apocalypse trope that is a fun watch that keeps you on your seat, leaving you with wanting more by the time its over"
}
release_year: 2018
review_date: "07/03/2021"
redux: false
id: 205
imdb_id: "tt6644200"
