title: "A Star Is Born"
rating: 9.4
review: "Incredible Acting, Incredible Story, Incredible Screenplay, Great Music, Incredible Cinematography, Movie dragged at times."
release_year: 2018
review_date: "12/17/2018"
redux: false
id: 78
imdb_id: "tt1517451"
