title: "Abre Los Ojos"
rating: 9.0
review: "Extremely good movie, Very conceptual and very good because of it, Very good acting though at times can be overacting, great score, Incredible movie."
release_year: 1997
review_date: "09/18/2017"
redux: false
id: 47
imdb_id: "tt0125659"
