title: "Ad Astra"
rating: 4.8
review: "Visuals, Sound mixing and editing were very good, Plot was very boring, with direction and acting very poor and boring as well, Score was nonexistent and not used when it was needed, Screenplay was very bland."
release_year: 2019
review_date: "12/22/2019"
redux: false
id: 113
imdb_id: "tt2935510"
