title: "Airplane!"
rating: 9.0
review: "Extremely funny movie, Majority of the jokes hit hard and well but when they miss they miss pretty badly, Incredible Screenplay, Pretty Bad to Decent story (its a parody movie after all they can\'t really do much), decent acting overall by the cast, very iconic lines and jokes, decent direction, plot continuity makes no sense but I guess thats the point, actually uses its short runtime well surprisingly as the pacing as good. Overall, as a movie it is decent, but as a medium to display comedy it is incredible as it is way ahead of its time."
release_year: 1980
review_date: "08/18/2020"
redux: false
