title: "Alien"
rating: 0.1
review {
  direction {
    director {
      name: "Ridley Scott"
    }
    rating: "TODO"
    comments: "macroscale is; microscale is; direction of actors is; storytelling is; tension is"
  }
  acting {
    performance {
      actor {
        name: "Tom Skerritt"
      }
      rating: "TODO"
      comments: "TODO"
    }
    performance {
      actor {
        name: "Sigourney Weaver"
      }
      rating: "TODO"
      comments: "TODO"
    }
    performance {
      actor {
        name: "Veronica Cartwright"
      }
      rating: "TODO"
      comments: "TODO"
    }
    performance {
      actor {
        name: "Harry Dean Stanton"
      }
      rating: "TODO"
      comments: "TODO"
    }
    performance {
      actor {
        name: "John Hurt"
      }
      rating: "TODO"
      comments: "TODO"
    }
    performance {
      actor {
        name: "Ian Holm"
      }
      rating: "TODO"
      comments: "TODO"
    }
    performance {
      actor {
        name: "Yaphet Kotto"
      }
      rating: "TODO"
      comments: "TODO"
    }
    cast {
      rating: "TODO"
      comments: "TODO"
    }
    rating: ""
  }
  story {
    writer {
      name: "Dan O\'Bannon"
    }
    writer {
      name: "Ronald Shusett"
    }
    rating: "TODO"
    comments: "The concept is; the plot structure is; flow between sequences is; character writing is"
  }
  screenplay {
    writer {
      name: "Dan O\'Bannon"
    }
    rating: "TODO"
    comments: "The dialogue is; the humor is; the symbolism is; the foreshadowing is"
  }
  score {
    composer {
      name: "Jerry Goldsmith"
    }
    rating: "TODO"
    comments: "TODO"
  }
  cinematography {
    cinematographer {
      name: "Derek Vanlint"
    }
    rating: "TODO"
    comments: "TODO"
  }
  editing {
    editor {
      name: "Terry Rawlings"
    }
    editor {
      name: "Peter Weatherley"
    }
    rating: "TODO"
    comments: "TODO"
  }
  sound {
    rating: "TODO"
    comments: "TODO"
  }
  visual_effects {
    rating: "TODO"
    comments: "TODO"
  }
  production_design {
    rating: "TODO"
    comments: "TODO"
  }
  makeup {
    rating: "TODO"
    comments: "TODO"
  }
  costumes {
    rating: "TODO"
    comments: "TODO"
  }
  pacing: "Pacing "
  climax: "Climax "
  tone: "Tone "
  final_notes: ""
  overall: "Overall, "
}
release_year: 1979
review_date: "04/28/2024"
redux: false
id: 444
imdb_id: "tt0078748"
