title: "All Quiet on the Western Front"
rating: 8.1
review {
  direction {
    director {
      name: "Edward Berger"
    }
    rating: "Good to Very Good"
    comments: "Did a great job in the macro scenes as he was able to capture the horrors of war through well choreographed battle scenes, also is able to use storytelling and tone to help build scenes and show the message; direction took a hit in more of the interpersonal scenes/negotiation scenes as they are not on the same level as the more important scenes"
  }
  acting {
    performance {
      actor {
        name: "Felix Kammerer"
      }
      rating: "Good"
      comments: "Does a good job in holding his own as the transitions from the hopefully kid to someone shell-shocked by the fears of War helps with displaying the message"
    }
    performance {
      actor {
        name: "Albrecht Schuch"
      }
      rating: "Good"
      comments: "Plays the companion character very well and plays off of Kammerer very well"
    }
    performance {
      actor {
        name: "Daniel Br\303\274hl"
      }
      rating: "Pretty Good"
      comments: "Really is not given that much to work with but does hold his own well"
    }
    cast {
      rating: "Pretty Good"
    }
    rating: "Pretty Good to Good"
  }
  story {
    writer {
      name: "Edward Berger"
    }
    writer {
      name: "Ian Stokell"
    }
    writer {
      name: "Lesley Paterson"
    }
    rating: "Pretty Good"
    comments: "When the story stays true to the source material, the movie is very good as it shows the horrors of war and how the trauma effects the soldiers, but the armistice scenes were really pointless as they were not from the source material and really do not add that much to the message at all; also the interpersonal scenes were hit or miss as some really helped add to caring about the characters while some were just not that well executed; the falling action really is a bit too long and could have been cut to make the movie way more tighter as it does not add too much to the story"
  }
  screenplay {
    writer {
      name: "Edward Berger"
    }
    writer {
      name: "Ian Stokell"
    }
    writer {
      name: "Lesley Paterson"
    }
    rating: "Good to Very Good"
    comments: "Dialogue overall flows pretty nicely with no major issues (hard to tell considering it was a translation); symbolism is prevalent as it helps aid with the the machinery of war as well as the trauma the people face; foreshadowing is pretty obvious but this does not hurt too much"
  }
  score {
    composer {
      name: "Volker Bertelmann"
    }
    rating: "Bad"
    comments: "Really does not match the scenes it is in and is mixed in way too loud"
  }
  cinematography {
    cinematographer {
      name: "James Friend"
    }
    rating: "Very Good to Great"
    comments: "Helps with displaying the war"
  }
  editing {
    editor {
      name: "Sven Budelmann"
    }
    rating: "Pretty Good"
    comments: "For the most part the movie has good editing but there were some noticeable editing mistakes"
  }
  sound {
    rating: "Good to Very Good"
    comments: "The war scenes and gunshots really helped with displaying the war, the issues have to do with mixing the score in"
  }
  visual_effects {
    rating: "Very Good"
  }
  production_design {
    rating: "Good"
    comments: "Helped with creating the scene of WWI"
  }
  makeup {
    rating: "Very Good"
    comments: "Especially the gore"
  }
  plot_structure: "Plot Structure was a major issue for the movie as it has a main story that it does very well but a side story about the armistice was pointless to where it drew away from the main story and what the overall message of the movie was; the falling action after the announcement of the war ending really could have been cut in half as it really make the movie drag for the final 40 minutes"
  pacing: "Pacing was a bit on the slower side as the movie is more of a slower burn (but about 20-30 minutes of the movie could have been cut for plot that does not need to be there)"
  climax: "There were multiple climaxes (with all of them being carried out very well to show the fear of war; the actual climax (the final one) was very well shot and helps display the message for the movie"
  tone: "Tone was conveyed very nicely as the historical time-period coupled with the fearful performances by the actor really helped provide a thrilling tone filled with anxietyS"
  final_notes: "The movie stays pretty true to the source material but added additional scenes that were unnecessary"
  overall: "Overall, a war movie that is very good when staying true to the story as it shows the horrors war has on the soldiers, but is really held back by scenes that were unnecessary (like the armistice and parts of the falling action) to where the movie drags on longer than it needs to be, thus taking away from the overall message."
}
release_year: 2022
review_date: "03/02/2023"
redux: false
id: 322
imdb_id: "tt1016150"
