title: "American History X"
rating: 8.5
review {
  direction {
    director {
      name: "Tony Kaye"
    }
    rating: "Good"
    comments: "While a lot of the conversational moments with smaller character or extras was pretty bad, the more important moments and grand scale moments were carried out very well"
  }
  acting {
    performance {
      actor {
        name: "Edward Norton"
      }
      rating: "Incredible"
      comments: "Range of emotions, ferocity, and epiphany were carried out very well"
    }
    performance {
      actor {
        name: "Edward Furlong"
      }
      rating: "Pretty Good"
      comments: "Good in some moments and Pretty bad and emotionless in others"
    }
    cast {
      rating: "Pretty Bad to Decent"
      comments: "Minor characters were Decent to Pretty Good, extras and very small characters were Pretty Bad"
    }
    rating: "Decent to Pretty Good"
  }
  story {
    writer {
      name: "David McKenna"
    }
    rating: "Pretty Good to Good"
    comments: "Really liked the way the story was filtered between flashbacks in B&W and current in color, the fall and redemption of Vinyard was a bit formulaic, but the story towards the end really was carried out very well to show the message of the story"
  }
  screenplay {
    writer {
      name: "David McKenna"
    }
    rating: "Pretty Good to Good"
    comments: "Symbols were a bit overt (though they were good in what they were trying to show) and the dialogue was very meta and forced"
  }
  score {
    composer {
      name: "Anne Dudley"
    }
    rating: "Pretty Good"
  }
  cinematography {
    cinematographer {
      name: "Tony Kaye"
    }
    rating: "Great to Incredible"
    comments: "Especially the way to show flashback being B&W (showing Vinyards past of separating color) with the present being in color (to show Vinyards future to look at multiple facets)"
  }
  editing {
    editor {
      name: "Jerry Greenberg"
    }
    editor {
      name: "Alan Heim"
    }
    rating: "Great to Incredible"
    comments: "Helping with the cinematography"
  }
  plot_structure: "Plot Structure was good as it is a story that mixes past and present to move the story forward"
  pacing: "Pacing was very good (nothing to really take out)"
  climax: "The build to the climax was very good as the climax of the movie really shows the true nature of how life really is; it was the correct decision to end the movie at the climax as it really leaves the audience understanding how life really is"
  final_notes: "the character and arc of Derek Vinyard is fascinating as (though formulaic) as it shows the way influence has in corrupting the mind and it is only through self-exploration that real thoughts can be formed; the message of the film is very clear and a good way to end the movie as it shows how America is a nation filled with flaws from Racism though the beauty is try to overcome and learn from this (even though everyone is not ready to do so)"
  overall: "Overall, a good watch to show the importance influence can have on corrupting the mind as we go through the story of Derek Vinyard (through an incredible and powerful performance from Edward Norton) to see how America is a nation filled with flaws and it is up to us to learn from and overcome these flaws (even though some may not be ready to do so), even though the movie may be meta and simple and representation in this message"
}
release_year: 1998
review_date: "11/09/2021"
redux: false
id: 225
imdb_id: "tt0120586"
