title: "American Graffiti"
rating: 7.2
review {
  direction {
    director {
      name: "George Lucas"
    }
    rating: "Pretty Good to Good"
    comments: "Does a Good job in moving the narrative forward and on an overall macro-scale, and does a pretty good job in the more interpersonal scenes and getting the most out of his actors (though it is obvious where he meets his limit for this)"
  }
  acting {
    performance {
      actor {
        name: "Richard Dreyfuss"
      }
      rating: "Pretty Good to Good"
      comments: "Holds his own well and helps carry the scenes he is in (it\'s kinda hard to believe he is a teenager though)"
    }
    performance {
      actor {
        name: "Ron Howard"
      }
      rating: "Pretty Good"
      comments: "Holds his own well throughout the movie"
    }
    performance {
      actor {
        name: "Paul Le Mat"
      }
      rating: "Decent to Pretty Good"
      comments: "Really takes from James Dean with the role (but it borderline becomes copying than paying homage at points)"
    }
    performance {
      actor {
        name: "Charles Martin Smith"
      }
      rating: "Decent to Pretty Good"
      comments: "Takes from the nerdy 60s kid trope"
    }
    performance {
      actor {
        name: "Candy Clark"
      }
      rating: "Decent to Pretty Good"
      comments: "Holds her own well throughout the movie"
    }
    performance {
      actor {
        name: "Mackenzie Phillips"
      }
      rating: "Decent to Pretty Good"
      comments: "Holds her own well throughout the movie"
    }
    performance {
      actor {
        name: "Cindy Williams"
      }
      rating: "Pretty Good"
      comments: "Shows some range of emotion and works well off of Ron Howard"
    }
    performance {
      actor {
        name: "Wolfman Jack"
      }
      rating: "Decent to Pretty Good"
    }
    cast {
      rating: "Decent to Pretty Good"
      comments: "The ensemble as a whole does its job in portraying the youth of the time (it is just that it\'s not extraordinary in any way given the inexperience of most of the actors)"
    }
    rating: "Decent to Pretty Good"
  }
  story {
    writer {
      name: "George Lucas"
    }
    writer {
      name: "Gloria Katz"
    }
    writer {
      name: "Willard Huyck"
    }
    rating: "Good"
    comments: "The story construction is good and the vignette style across a single night helped with showing the youth of the time; the story ended very well as all the different storylines converged in the end and story elements/symbols are shown throughout the movie"
  }
  screenplay {
    writer {
      name: "George Lucas"
    }
    writer {
      name: "Gloria Katz"
    }
    writer {
      name: "Willard Huyck"
    }
    rating: "Pretty Good"
    comments: "The dialogue was pretty typical of the time (and sounded a bit more normal than typical George Lucas dialogue (it probably helped that he wasn\'t the sole screenwriter)); the comedic elements were decent (but a bit dated considering the jokes were tailored for an audience who lived during the 60s); the symbolism was present throughout the movie (like the white car); the foreshadowing was pretty predictable given the genre (though it executed pretty well)"
  }
  cinematography {
    cinematographer {
      name: "Ron Eveslage"
    }
    cinematographer {
      name: "Jan D\'Alquen"
    }
    cinematographer {
      name: "Haskell Wexler (visual consultant)"
    }
    rating: "Good"
    comments: "Especially with the car scenes"
  }
  editing {
    editor {
      name: "Verna Fields"
    }
    editor {
      name: "Marcia Lucas"
    }
    rating: "Pretty Good"
  }
  sound {
    rating: "Pretty Good"
    comments: "Sounded kinda cheap and cartoony at times"
  }
  visual_effects {
    rating: "Pretty Good"
  }
  production_design {
    rating: "Good"
    comments: "Helped with setting the time period"
  }
  plot_structure: "Plot Structure was a unique part of the movie as the vignette style of multiple storylines converging to a single conclusion helped with showing the different lives of the ensemble"
  pacing: "Pacing was fine (did not feel too fast or too slow); Runtime felt just right (maybe deleting about 5-10 minutes of the exposition could have helped with making the movie a bit more tight)"
  climax: "Climax was decent to pretty good (Did not feel incredibly captivating but did its purpose in helping converge the different storylines)"
  tone: "Tone was very laid back as this film felt a lot like a \'hang-out\' movie with its feel and subject matter"
  final_notes: ""
  overall: "Overall, a pretty good hangout movie that helped put George Lucas on the map as we see a young filmmaker take low-budget with a cast of young actors and make an influential movie in cinema history through its story-writing and construction, though there are noticeable limitations in what he can do with his direction of actors and dialogue"
}
release_year: 1973
review_date: "09/04/2023"
redux: false
id: 367
imdb_id: "tt0069704"
