title: "American Beauty"
rating: 9.5
review {
  direction {
    director {
      name: "Sam Mendes"
    }
    comments: "Great to Incredible Direction (Especially the ability to capture the symbols, illusions, and acting performances all at once)"
  }
  acting {
    actor {
      name: "Kevin Spacey"
      comments: "Brilliant from Kevin Spacey (Especially his ability to change moods very quickly and for him to display emotion through monotonous expressions (as if the character was written for Spacey to play, a true masterclass))"
    }
    actor {
      name: "Annette Bening"
      comments: "Incredible from Annette Bening (with her ability to capture dying beauty and someone who is trying to escape her mid-life crisis)"
    }
    actor {
      name: "Mena Suvari"
      comments: "Very Good from Mena Suvari (was able to convey someone who was trying so hard to escape from being ordinary by lying about who she really is)"
    }
    actor {
      name: "Wes Bentley"
      comments: "Good to Very Good from Wes Bentley"
    }
    cast: "Good from the rest of the cast"
    comments: "Great Acting"
  }
  story {
    writer {
      name: "Alan Ball"
    }
    comments: "Incredible Story (in a modern retelling of Lolita)"
  }
  screenplay {
    writer {
      name: "Alan Ball"
    }
    comments: "Incredible to Brilliant Screenplay (the dialogue was extremely conversational and used as a real tool to help convey emotions and the message, the symbols were omnipresent (especially the rose to display beauty and innocence) in helping convey the message)"
  }
  score {
    composer {
      name: "Thomas Newman"
    }
    comments: "Good Score"
  }
  cinematography {
    cinematographer {
      name: "Conrad L. Hall"
    }
    comments: "Great Cinematography to show perspective"
  }
  sound: "Sound ()"
  editing {
    editor {
      name: "Tariq Anwar"
    }
    editor {
      name: "Christopher Greenbury"
    }
    comments: "Great to Incredible Editing (helps separate reality from illusions)"
  }
  visual_effects: "Great to Incredible Visual Effects (see Editing)"
  production_design: "Production Design ()"
  makeup: "Makeup ()"
  costumes: "Costumes ()"
  plot_structure: "Plot Structure was Great because you see how each character goes through development at each stage (especially Lester)"
  pacing: "Pacing was Very Good (no need to cut or add any scenes)"
  climax: "Build to the climax was done very well because it is a gradual build throughout the entire movie; the climax itself was a carried out very well as you get to see Lester's real motivations in life and him being content for the first time in forever"
  final_notes: "Narration was a vital part (unlike its use in other movies) as it is used to drive the story forward (and not just tell it); the message of the movie (trying to fine beauty in a fractured suburban America) is effectively conveyed very well through the movie's themes and symbols (like the rose)"
  overall: "Overall, an Incredible Movie that used the setting of a dying Suburban America to show the true beauty of America and finding self purpose when it may be too late, something that is effectively carried out in a career defining performance from Kevin Spacey and an Incredible Screenplay filled with many symbols"
}
release_year: 1999
review_date: "11/17/2021"
redux: false
