title: "Arrival"
rating: 7.9
review: "Acting has no emotion but is not bad, Great Story, Great Screenplay, Incredible Cinematography, Great Score, Mind-Blowing plot twist (which I caught hehe), ending is very forced and pretty bad."
release_year: 2016
review_date: "02/12/2017"
redux: false
id: 7
imdb_id: "tt2543164"
