title: "As Good as it Gets"
rating: 8.7
review: "Great Acting Overall (Incredible by Jack Nicholson and Helen Hunt, Great by Greg Kinnear, Good by the supporting cast), Very Good Story, Great Screenplay (Incredible Dialogue and Lines and Good symbolism and meanings but mostly surface level), Good Direction, Very Good Score, Good Displays of emotion, Pretty Funny (especially Jack), the shifts in emotions did not have that smooth of transitions, decent to pretty good chemistry between main two (Good enough for a Rom Com), Definitely a good rom com overall, pretty good pacing overall (uses its time wisely). Overall, its a great fun watch but mostly surface level in terms of content."
release_year: 1997
review_date: "07/14/2020"
redux: false
