title: "Avatar"
rating: 7.6
review {
  direction {
    director {
      name: "James Cameron"
    }
    comments: "Pretty Good Direction (Does a Very good job at helping build the world and moving the story forward (plus helping create the action and suspense); but really does not do that well at directing his actors)"
  }
  acting {
    actor {
      name: "Sam Worthington"
      comments: "Pretty Bad from Sam Worthington (His performance felt very monotonous and did not really do well as the lead character (plus the voice is the exact same voice he does for Black Ops so that was all I could think about))"
    }
    actor {
      name: "Zoe Saldana"
      comments: "Pretty Good from Zoe Saldana"
    }
    actor {
      name: "Stephen Lang"
      comments: "Good from Stephen Lang (Really commands himself well as the antagonist of the movie and inserts his presence well in all the scenes he is in)"
    }
    actor {
      name: "Michelle Rodriguez"
      comments: "Decent from Michelle Rodriguez"
    }
    actor {
      name: "Sigourney Weaver"
      comments: "Pretty Good from Sigourney Weaver"
    }
    cast: "Pretty Bad to Decent from the rest of the cast"
    comments: "Decent Acting"
  }
  story {
    writer {
      name: "James Cameron"
    }
    comments: "Decent Story (While the actual story is not bad, it is a bland copy of other movies that fall under the trope of a colonizer assimilating with a native tribe, making the story very predictable)"
  }
  screenplay {
    writer {
      name: "James Cameron"
    }
    comments: "Decent Screenplay (The concepts and names felt like they were made on the spot and the overall dialogue is just very standard for a Sci-fi movie; the allegory for the story is also incredibly obvious that the movie feels very preachy (exploiting natives for their resources and not caring about the humanity trope))"
  }
  score {
    composer {
      name: "James Horner"
    }
    comments: "Good Score (Has some iconic elements to it)"
  }
  cinematography {
    cinematographer {
      name: "Mauro Fiore"
    }
    comments: "Good Cinematography (Kinda hard to gauge considering how much of the movie is CGI)"
  }
  sound: "Very Good Sound"
  editing {
    editor {
      name: "Stephen Rivkin"
    }
    editor {
      name: "John Refoua"
    }
    editor {
      name: "James Cameron"
    }
    comments: "Very Good Editing"
  }
  visual_effects: "Great Visual Effects (This is based on for the time; with the advancement in technology since this movie came out, the movie looks incredibly dated)"
  plot_structure: "Plot Structure was very predictable given the trope"
  pacing: "Pacing was fine for the most part (even with the longer runtime it does not feel like it overstays its welcome)"
  climax: "Climax was very good as it is the most action packed part of the movie"
  tone: "Tone tries to be a mix of sci-fi and colonization movies but ends up being very bland overall"
  final_notes: "This movie has become incredibly dated as the years have gone on as it heavily relies on CGI to tell the story and build the world (so watching it years after it comes out makes the movie feel less groundbreaking)"
  overall: "Overall, a groundbreaking film at the time it was released, but has become incredibly dated given how far technology has advanced since the movie was released, causing the movie to fall back on mediocre filmmaking with a very predictable/copied story due to how much the film relies on CGI to tell the story"
}
release_year: 2009
review_date: "12/28/2022"
redux: false
id: 306
imdb_id: "tt0499549"
