title: "Avengers: Endgame"
rating: 8.7
review: "Great Acting, Good Story, Very Nostalgic to the past movies, Great Action Scenes, Good Tie up for the MCU and ending for some of the characters, Too many plot holes."
release_year: 2019
review_date: "05/22/2019"
redux: false
id: 93
imdb_id: "tt4154796"
