title: "Baahubali 2: The Conclusion"
rating: 6.2
review: "Unnecessary CGI moments, good story, Decent acting, not as good as the first, good action."
release_year: 2017
review_date: "05/21/2017"
redux: false
id: 21
imdb_id: "tt4849438"
