title: "Back to the Future"
rating: 9.6
review: "Great Acting, Brilliant Story, Great Screenplay, Great Score, Extremely Iconic, Marty\'s girlfriend cannot act"
release_year: 1985
review_date: "06/13/2017"
redux: false
