title: "Batman Begins"
rating: 8.6
review: "Good Direction (Great at times when directing the story and actions but poor when directing dialogue between minor characters and extras), Good Acting by all cast members that came back in the series and Tom Wilkinson (Includes Liam Neeson and Cillian Murphy as they have cameos in the future movies), Bad acting by supporting cast and Katie Holmes (Katie and Christian Bale have little to no chemistry), Great Cinematography, Incredible Story (Especially for an Origin story), Good Screenplay (Incredible at incorporating story elements as symbols and foreshadowing but dialogue is on a spectrum from Bad to Incredible), Incredible Score, Great Pacing, Some plot holes from towards the end. Basically this movie was a test run for The Dark Knight as it used the feedback on what to improve on and did that incredibly (Making bad elements incredible and good elements Brilliant)."
release_year: 2005
review_date: "07/28/2020"
redux: false
id: 149
imdb_id: "tt0372784"
