title: "Black Swan"
rating: 9.1
review {
  direction {
    director {
      name: "Darren Aronofsky"
    }
    rating: "Incredible"
    comments: "Only someone like Darren Aronofsky could have made this film"
  }
  acting {
    performance {
      actor {
        name: "Natalie Portman"
      }
      rating: "Incredible"
    }
    performance {
      actor {
        name: "Vincent Cassel"
      }
      rating: "Decent"
      comments: "Hit or miss performance"
    }
    performance {
      actor {
        name: "Mila Kunis"
      }
      rating: "Very Good"
    }
    performance {
      actor {
        name: "Winona Ryder"
      }
      rating: "Good"
      comments: "Very Winona Ryder Performance"
    }
    cast {
      rating: "Good"
    }
    rating: "Good"
  }
  story {
    writer {
      name: "Andres Heinz"
    }
    rating: "Great to Incredible"
  }
  screenplay {
    writer {
      name: "Mark Heyman"
    }
    writer {
      name: "Andres Heinz"
    }
    writer {
      name: "John McLaughlin"
    }
    rating: "Great"
    comments: "A very simple yet complex screenplay (Simple in terms of the dialogue as it was very forced/unnatural and made no sense at times, while very complex in terms of the content/subject mater/symbolism in how it presents it)"
  }
  score {
    composer {
      name: "Clint Mansell"
    }
    rating: "Good"
    comments: "Blended in very nicely and really liked how they used romantic/swan lake motifs"
  }
  cinematography {
    cinematographer {
      name: "Matthew Libatique"
    }
    rating: "Great"
    comments: "Though nauseating at times"
  }
  editing {
    editor {
      name: "Andrew Weisblum"
    }
    rating: "Great"
    comments: "Great editing/visual effects in how it was molded together to show the hallucinations"
  }
  visual_effects {
    rating: "Great"
    comments: "See Editing"
  }
  pacing: "Pacing was pretty fast fast/chaotic to mimic that of the mind of Nina (runtime was good (no need to add/cut scenes))"
  climax: "The build to the climax was great as you really do not know what is real and what is just made up in Nina\'s head (as she slowly drives into madness on her way to perfection)"
  final_notes: "Incredible symbolism and parallel construction on how the obsession of the artist turned the white/innocent swan that Nina was into the dark/lost soul black swan she became at the end of the movie (something that is parallel to Swan Lake)"
  overall: "Overall, a great movie that is both a simple, yet complex modern retelling of Swan Lake that looks into the obsession of an artist and how far one will go to pollute their innocence to become the best, even though it was told in a very simple, direct way"
}
release_year: 2010
review_date: "06/21/2021"
redux: false
id: 202
imdb_id: "tt0947798"
