title: "Blackkklansman"
rating: 7.8
review: "Great Acting, great story, good screenplay, funny at times, Love interest side story was not good, Preachy but its a Spike Lee movie so like that\'s not that surprising, The ending is extremely anticlimactic and just very bad, The end just became a PSA against Trump for like absolutely no reason, like it was not needed at all."
release_year: 2018
review_date: "02/23/2019"
redux: false
id: 83
imdb_id: "tt7349662"
