title: "Blade Runner 2049"
rating: 8.1
review {
  direction {
    director {
      name: "Denis Villeneuve"
    }
    rating: "Pretty Good to Good"
    comments: "Does a Great Job in storytelling/moving the story forward as he is able to build scenes/worlds and pieces them toghether with other story elements; the issues in the direction come with directors his actors as it has a similar style to the first film and because of it there is a lot of dull performances with dead air"
  }
  acting {
    performance {
      actor {
        name: "Ryan Gosling"
      }
      rating: "Pretty Good to Good"
      comments: "Uses a lot of his facial experiences to help sell the scenes and acts as a replicant very well (which kinda hurts him because he really is not given that much to work with in terms of showing range)"
    }
    performance {
      actor {
        name: "Harrison Ford"
      }
      rating: "Decent"
      comments: "Shows more experience and emotion from the last time but the performance just shows that he put no prep into the role as it just feels like he showed up with very little interest"
    }
    performance {
      actor {
        name: "Ana de Armas"
      }
      rating: "Good to Very Good"
      comments: "Really acts as the morality of the movie as she works well off of Gosling to help give humanity to his life despite being fake herself"
    }
    cast {
      rating: "Decent"
      comments: "Just a lot of emotionless performances that don\'t really help or hurt the movie"
    }
    rating: "Decent to Pretty Good"
  }
  story {
    writer {
      name: "Hampton Fancher"
    }
    rating: "Good to Very Good"
    comments: "Really does a good job in differing from the previous movie as the plot this time around was more about K finding his own humanity rather than a Blade Runner trying to hunt down replicants; the movie also does share the same philosophical interpretations on what it means to be alive but it is less open ended than last time"
  }
  screenplay {
    writer {
      name: "Hampton Fancher"
    }
    writer {
      name: "Michael Green"
    }
    rating: "Decent to Pretty Good"
    comments: "The screenplay does improve as it flows more than the last movie (not by that much though) but the symbolism is not as good as the previous movie; the foreshadowing is still very on-par with the previous movie as it is very evident at what they are trying to build throughout the movie"
  }
  score {
    composer {
      name: "Benjamin Wallfisch"
    }
    composer {
      name: "Hans Zimmer"
    }
    rating: "Good to Very Good"
  }
  cinematography {
    cinematographer {
      name: "Roger A. Deakins"
    }
    rating: "Incredible to Brilliant"
    comments: "Such a beautiful movie in how they try to set up these different worlds and how they use lighting to help set the ominous nature of the scenes"
  }
  editing {
    editor {
      name: "Joe Walker"
    }
    rating: "Great"
  }
  sound {
    rating: "Great"
  }
  visual_effects {
    rating: "Incredible"
  }
  production_design {
    rating: "Great"
  }
  costumes {
    rating: "Very Good"
  }
  plot_structure: "Plot Structure was laid out very well as it was prevalent which part of the story the movie is in"
  pacing: "Pacing was on the slower side (with 20-30 minutes that could have been cut to make the movie a bit tighter and faster)"
  climax: "Build to climax was decent (but hard considering how slow the movie was progressing); climax was decent but not that interesting or entertaining"
  tone: "Tone had more of that sci-fi tone than the original movie was going for as the advancement in technology really helped with setting this"
  final_notes: "The movie really benefits from the advancements in technology as it is able to be more of a realistic sci-fi movie as opposed to the previous movie"
  overall: "Overall, a very technically sound movie that uses advancements in filmmaking and technology to help make a better movie that its predecessor, though it still falters a bit in terms of bland writing/acting that is still very slow in pace"
}
release_year: 2017
review_date: "12/04/2022"
redux: false
id: 303
imdb_id: "tt1856101"
