title: "Blitz"
rating: 0.1
review {
  direction {
    director {
      name: "Steve McQueen"
    }
    rating: "TODO"
    comments: "macroscale is; microscale is; direction of actors is; storytelling is; tension is"
  }
  acting {
    performance {
      actor {
        name: "Saoirse Ronan"
      }
      rating: "TODO"
      comments: "TODO"
    }
    performance {
      actor {
        name: "Harris Dickinson"
      }
      rating: "TODO"
      comments: "TODO"
    }
    performance {
      actor {
        name: "Elliott Heffernan"
      }
      rating: "TODO"
      comments: "TODO"
    }
    cast {
      rating: "TODO"
      comments: "TODO"
    }
    rating: "TODO"
  }
  story {
    writer {
      name: "Steve McQueen"
    }
    rating: "TODO"
    comments: "The concept is; the plot structure is; flow between sequences is; character writing is"
  }
  screenplay {
    writer {
      name: "Steve McQueen"
    }
    rating: "TODO"
    comments: "The dialogue is; the humor is; the symbolism is; the foreshadowing is"
  }
  score {
    composer {
      name: "Hans Zimmer"
    }
    rating: "TODO"
    comments: "TODO"
  }
  cinematography {
    cinematographer {
      name: "Yorick Le Saux"
    }
    rating: "TODO"
    comments: "TODO"
  }
  editing {
    editor {
      name: "Peter Sciberras"
    }
    rating: "TODO"
    comments: "TODO"
  }
  sound {
    rating: "TODO"
    comments: "TODO"
  }
  visual_effects {
    rating: "TODO"
    comments: "TODO"
  }
  production_design {
    rating: "TODO"
    comments: "TODO"
  }
  costumes {
    rating: "TODO"
    comments: "TODO"
  }
  pacing: "Pacing "
  climax: "Climax "
  tone: "Tone "
  final_notes: ""
  overall: "Overall, "
}
release_year: 2024
review_date: "10/29/2024"
redux: false
id: 505
imdb_id: "tt15939198"

* Premeire at Austin Film Festival