title: "Borat: Cultural Learnings of America for Make Benefit Glorious Nation of Kazakhstan"
rating: 9.7
review: "Hilarious, Great Acting, Incredible Writing, Has a lot of balls to make a movie like this. "
release_year: 2006
review_date: "02/24/2017"
redux: false
