title: "Borat Subsequent Moviefilm: Delivery of Prodigious Bribe to American Regime for Make Benefit Once Glorious Nation of Kazakhstan"
rating: 8.0
review: "Contiunation of a beloved classic and one of, if not the, greatest comedies of all time. In its sequel, Borat does not have as much of the charm as its original movie did. Very funny at times but very mild or bland or disgusting at others, story was coherent as very poltiically brown nose against the right, the movie is ultamitely propoganda to vote. Sasha was great, though lost a step from her previous version, Tutar was good acting but was no where near the level of sidekick as Azamt, Good but safe story, Very good but safe screenplay, Good direction (But misleading editing). Overall, This movie was a good look back into one of the greatest movies of all time but plays it safe and ultamitley boils down into a movie urging the audience to vote out the right (making it a very topical movie at the present but something that will not make it a classic like its predecssor). This movie really didn\'t have to be made and turns down into a cash grab on a retired character. "
release_year: 2020
review_date: "10/29/2020"
redux: false
