title: "Carrie"
rating: 7.6
review: "Great Acting from leads, Decent Screenplay, Unnecessary Nudity, Not That Scary, Ending Sequence is very good."
release_year: 1976
review_date: "07/09/2018"
redux: false
