title: "Catch Me If You Can"
rating: 9.2
review {
  direction {
    director {
      name: "Steven Spielberg"
    }
    rating: "Great"
  }
  acting {
    performance {
      actor {
        name: "Leonardo DiCaprio"
      }
      rating: "Great to Incredible"
    }
    performance {
      actor {
        name: "Tom Hanks"
      }
      rating: "Great to Incredible"
    }
    performance {
      actor {
        name: "Christopher Walken"
      }
      rating: "Great to Incredible Acting"
    }
    cast {
      rating: "Good"
    }
    rating: "Great"
  }
  story {
    writer {
      name: "Jeff Nathanson"
    }
    rating: "Incredible"
    comments: "Stays pretty true to the source material"
  }
  screenplay {
    writer {
      name: "Jeff Nathanson"
    }
    rating: "Great"
    comments: "Filled with foreshadowing"
  }
  score {
    composer {
      name: "John Williams"
    }
    rating: "Good"
  }
  pacing: "Pacing was great up until the final like 20 minutes (probably could have cut it down to 10)"
  climax: "The build to the climax was incredible as the standoff scene between Leo and Hanks really showed both actor\'s best in displaying the anxiety and fright in the situation"
  final_notes: ""
  overall: "Overall, a great film that is one of the most entertaining films to watch as it is a thrill of a ride to see all the different scams Frank Abagnale was able to pull off from the very start to the very end, something that really keeps you engaged at all times"
}
release_year: 2002
review_date: "05/24/2021"
redux: false
id: 190
imdb_id: "tt0264464"
