title: "Citizen Kane"
rating: 9.4
review {
  direction {
    director {
      name: "Orson Welles"
    }
    comments: "Direction ()"
  }
  acting {
    actor {
      name: "Orson Welles"
      comments: " from Orson Welles ()"
    }
    actor {
      name: "Joseph Cotten"
      comments: " from Joseph Cotten ()"
    }
    actor {
      name: "Dorothy Comingore"
      comments: " from Dorothy Comingore ()"
    }
    actor {
      name: "Everett Sloane"
      comments: " from Everett Sloane ()"
    }
    actor {
      name: "Ray Collins"
      comments: " from Ray Collins ()"
    }
    actor {
      name: "George Coulouris"
      comments: " from George Coulouris ()"
    }
    actor {
      name: "Agnes Moorehead"
      comments: " from Agnes Moorehead ()"
    }
    actor {
      name: "Paul Stewart"
      comments: " from Paul Stewart ()"
    }
    actor {
      name: "Ruth Warrick"
      comments: " from Ruth Warrick ()"
    }
    actor {
      name: "Erskine Sanford"
      comments: " from Erskine Sanford ()"
    }
    actor {
      name: "William Alland"
      comments: " from William Alland ()"
    }
    cast: "from the rest of the cast ()"
    comments: " Acting "
  }
  story {
    writer {
      name: "Herman J. Mankiewicz"
    }
    writer {
      name: "Orson Welles"
    }
    comments: "Story ()"
  }
  screenplay {
    writer {
      name: "Herman J. Mankiewicz"
    }
    writer {
      name: "Orson Welles"
    }
    comments: "Screenplay ()"
  }
  score {
    composer {
      name: "Bernard Herrmann"
    }
    comments: "Score ()"
  }
  cinematography {
    cinematographer {
      name: "Gregg Toland"
    }
    comments: "Cinematography ()"
  }
  sound: "Sound ()"
  editing {
    editor {
      name: "Robert Wise"
    }
    comments: "Editing ()"
  }
  visual_effects: "Visual Effects ()"
  production_design: "Production Design ()"
  makeup: "Makeup ()"
  costumes: "Costumes ()"
  plot_structure: "Plot Structure "
  pacing: "Pacing "
  climax: "climax "
  tone: "tone"
  final_notes: ""
  overall: "Overall, "
}
release_year: 1941
review_date: "04/27/2022"
redux: false
