title: "Clown in a Cornfield"
rating: 0.1
review {
  direction {
    director {
      name: "Eli Craig"
    }
    rating: "TODO"
    comments: "macroscale is; microscale is; storytelling is; tension is"
  }
  acting {
    performance {
      actor {
        name: "Katie Douglas"
      }
      rating: "TODO"
      comments: "TODO"
    }
    performance {
      actor {
        name: "Aaron Abrams"
      }
      rating: "TODO"
      comments: "TODO"
    }
    performance {
      actor {
        name: "Carson MacCormac"
      }
      rating: "TODO"
      comments: "TODO"
    }
    performance {
      actor {
        name: "Kevin Durand"
      }
      rating: "TODO"
      comments: "TODO"
    }
    performance {
      actor {
        name: "Will Sasso"
      }
      rating: "TODO"
      comments: "TODO"
    }
    cast {
      rating: "TODO"
      comments: "TODO"
    }
    rating: "TODO"
  }
  story {
    writer {
      name: "Carter Blanchard"
    }
    writer {
      name: "Eli Craig"
    }
    rating: "TODO"
    comments: "The concept is; the plot structure is; character writing is"
  }
  screenplay {
    writer {
      name: "Carter Blanchard"
    }
    writer {
      name: "Eli Craig"
    }
    rating: "TODO"
    comments: "The dialogue is; the humor is; the symbolism is; the foreshadowing is"
  }
  score {
    composer {
      name: "Brandon Roberts"
    }
    composer {
      name: "Marcus Trumpp"
    }
    rating: "TODO"
    comments: "TODO"
  }
  soundtrack {
    rating: "TODO"
    comments: "TODO"
  }
  cinematography {
    cinematographer {
      name: "Brian Pearson"
    }
    rating: "TODO"
    comments: "TODO"
  }
  editing {
    editor {
      name: "Sabrina Pitre"
    }
    rating: "TODO"
    comments: "TODO"
  }
  sound {
    rating: "TODO"
    comments: "TODO"
  }
  visual_effects {
    rating: "TODO"
    comments: "TODO"
  }
  production_design {
    rating: "TODO"
    comments: "TODO"
  }
  makeup {
    rating: "TODO"
    comments: "TODO"
  }
  costumes {
    rating: "TODO"
    comments: "TODO"
  }
  pacing: "Pacing "
  climax: "Climax "
  tone: "Tone "
  final_notes: ""
  overall: "Overall, "
}
release_year: 2025
review_date: "03/10/2025"
redux: false
id: 548
imdb_id: "tt23060698"
