title: "Cocaine Bear"
rating: 1.0
review {
  direction {
    director {
      name: "Elizabeth Banks"
    }
    comments: "Very Bad to Bad Direction (The use of storytelling was lackluster as it was very anticlimatic the way the multiple storylines converged; the meta humor felt very childish as it felt more cheap than funny; did not get anything from the actors as it did not feel like they were playing off each other at all)"
  }
  acting {
    actor {
      name: "Keri Russell"
      comments: "Decent to Prety Good from Keri Russell (The only somewhat memorable performance from the movie as it felt like she was holding her own solely from the experience she has and not from any direction given)"
    }
    actor {
      name: "O\'Shea Jackson Jr."
      comments: "Pretty Bad to Decent from O\'Shea Jackson Jr. (Felt like he was playing the similiar character he has been playing since Straight Outta Compton as it is pretty one-dimensional (though does has some charm and humor at times))"
    }
    actor {
      name: "Alden Ehrenreich"
      comments: "Decent from Alden Ehrenreich (Had moments where he was fine and moments where he really could not hold his own, though overall was a decent performance)"
    }
    actor {
      name: "Isiah Whitlock Jr."
      comments: "Pretty Bad to Decent from Isiah Whitlock Jr. (One of the many one-dimensional performances in the movie)"
    }
    actor {
      name: "Margo Martindale"
      comments: "Pretty Bad from Margo Martindale (A very emotionalless performance from the movie despite her trying very hard to be shocking for humor (which is a shame cause she is actually very talented))"
    }
    actor {
      name: "Ray Liotta"
      comments: "Decent to Pretty Good from Ray Liotta (Pulls a lot from experience as he plays a character that is very similiar to others he has played recently)"
    }
    cast: "Bad from the rest of the cast (Just filled with many performances that don't work off of each other and inexperience overall (this does not include the child actors though))"
    comments: "Bad Pretty Bad Acting"
  }
  story {
    writer {
      name: "Jimmy Warden"
    }
    comments: "Story ()"
  }
  screenplay {
    writer {
      name: "Jimmy Warden"
    }
    comments: "Screenplay ()"
  }
  score {
    composer {
      name: "Mark Mothersbaugh"
    }
    comments: "Decent Score"
  }
  cinematography {
    cinematographer {
      name: "John Guleserian"
    }
    comments: "Pretty Bad Cinematography (Just felt very amatuerish)"
  }
  sound: "Pretty Bad Sound"
  editing {
    editor {
      name: "Joel Negron"
    }
    comments: "Bad Editing (Felt very cheap)"
  }
  visual_effects: "Bad Visual Effects (The CGI of the bear made it feel very much in the uncanny valley (which is a shame given the animal is the whole point of the movie))"
  production_design: "Production Design ()"
  makeup: "Makeup ()"
  costumes: "Costumes ()"
  plot_structure: "Plot Structure "
  pacing: "Pacing "
  climax: "Climax "
  tone: "Tone "
  final_notes: ""
  overall: "Overall, "
}
release_year: 2023
review_date: "07/24/2023"
redux: false
id: 357
imdb_id: "tt1420991"
