title: "CODA"
rating: 8.5
review {
  direction {
    director {
      name: "Sian Heder"
    }
    comments: "Great Direction (espeically the ability to control the scenes with deaf actors (especially during the signing arguments))"
  }
  acting {
    actor {
      name: "Emilia Jones"
      comments: " from Emilia Jones ()"
    }
    actor {
      name: "Eugenio Derbez"
      comments: " from Eugenio Derbez ()"
    }
    actor {
      name: "Troy Kotsur"
      comments: " from Troy Kotsur ()"
    }
    actor {
      name: "Ferdia Walsh-Peelo"
      comments: " from Ferdia Walsh-Peelo ()"
    }
    actor {
      name: "Daniel Durant"
      comments: " from Daniel Durant ()"
    }
    actor {
      name: "Marlee Matlin"
      comments: " from Marlee Matlin ()"
    }
    cast: "from the rest of the cast ()"
    comments: " Acting "
  }
  story {
    writer {
      name: "Sian Heder"
    }
    comments: "Good to Very Good Story (The story is very predictable because of it being a bildungsroman movie but there are some unique elements that make it interesting to watch (like the juxtaposition of being a singer in a deaf family))"
  }
  screenplay {
    writer {
      name: "Sian Heder"
    }
    comments: "Very Good Screenplay (especially the usage of ASL in intense arguments, though the imagery/symbolism is a bit surface-level (mostly due to it being a coming of age story))"
  }
  score {
    composer {
      name: "Marius de Vries"
    }
    comments: "Decent Score"
  }
  cinematography {
    cinematographer {
      name: "Paula Huidobro"
    }
    comments: "Good Cinematography"
  }
  sound: "Sound ()"
  editing {
    editor {
      name: "Geraud Brisson"
    }
    comments: "Good Editing"
  }
  visual_effects: "Visual Effects ()"
  production_design: "Production Design ()"
  makeup: "Makeup ()"
  costumes: "Costumes ()"
  plot_structure: "Plot Structure "
  pacing: "Pacing "
  climax: "climax "
  tone: "tone"
  final_notes: ""
  overall: "Overall, a good movie that is carried by the strong performances of the entire cast as we get to see a rare insight into deaf culture, though the movie is held back by it playing way too much to the coming-of-age genre through its cliches and predictable plot"
}
release_year: 2021
review_date: "01/01/2021"
redux: false
