title: "Conclave"
rating: 0.1
review {
  direction {
    director {
      name: "Edward Berger"
    }
    rating: "TODO"
    comments: "macroscale is; microscale is; direction of actors is; storytelling is; tension is"
  }
  acting {
    performance {
      actor {
        name: "Ralph Fiennes"
      }
      rating: "TODO"
      comments: "TODO"
    }
    performance {
      actor {
        name: "Stanley Tucci"
      }
      rating: "TODO"
      comments: "TODO"
    }
    performance {
      actor {
        name: "John Lithgow"
      }
      rating: "TODO"
      comments: "TODO"
    }
    performance {
      actor {
        name: "Sergio Castellitto"
      }
      rating: "TODO"
      comments: "TODO"
    }
    performance {
      actor {
        name: "Isabella Rossellini"
      }
      rating: "TODO"
      comments: "TODO"
    }
    cast {
      rating: "TODO"
      comments: "TODO"
    }
    rating: "TODO"
  }
  story {
    writer {
      name: "Peter Straughan"
    }
    rating: "TODO"
    comments: "The concept is; the plot structure is; flow between sequences is; character writing is"
  }
  screenplay {
    writer {
      name: "Peter Straughan"
    }
    rating: "TODO"
    comments: "The dialogue is; the humor is; the symbolism is; the foreshadowing is"
  }
  score {
    composer {
      name: "Volker Bertelmann"
    }
    rating: "TODO"
    comments: "TODO"
  }
  cinematography {
    cinematographer {
      name: "St\303\251phane Fontaine"
    }
    rating: "TODO"
    comments: "TODO"
  }
  editing {
    editor {
      name: "Nick Emerson"
    }
    rating: "TODO"
    comments: "TODO"
  }
  sound {
    rating: "TODO"
    comments: "TODO"
  }
  visual_effects {
    rating: "TODO"
    comments: "TODO"
  }
  production_design {
    rating: "TODO"
    comments: "TODO"
  }
  makeup {
    rating: "TODO"
    comments: "TODO"
  }
  costumes {
    rating: "TODO"
    comments: "TODO"
  }
  pacing: "Pacing "
  climax: "Climax "
  tone: "Tone "
  final_notes: ""
  overall: "Overall, "
}
release_year: 2024
review_date: "11/04/2024"
redux: false
id: 509
imdb_id: "tt20215234"
