title: "Creed"
rating: 9.5
review: "The Acting was Incredible (Especially Sly), The Direction was Incredible, The Score was Incredible, The Screenplay was good."
release_year: 2015
review_date: "07/09/2018"
redux: false
id: 64
imdb_id: "tt3076658"
