title: "Cuties"
rating: 1.9
review: "Poor Direction, Very boring screenplay (From a translation perspective), the story had a decent idea but the plot points were very wtf and ultimately not necessary, very poor acting (Especially for the controversial scenes), The lack of score makes the movie extremely emotionless and the scenes seem very dull, The movie isn\'t as controversial as people are saying it is although the final 30 mins definitely could be argued against this because it was very cringe/hard to watch, It tries to show the evil in child sexualization but does it so poorly that it ultimately promotes it. Very bad movie overall and very boring to watch."
release_year: 2020
review_date: "09/28/2020"
redux: false
id: 165
imdb_id: "tt9196192"
