title: "Dallas Buyers Club "
rating: 8.5
review: "Pretty good acting (but Leo deserved the Oscar more), good story, good screenplay, Too short and ending felt very jammed together."
release_year: 2013
review_date: "06/27/2017"
redux: false
