title: "Deadpool 2"
rating: 8.6
review {
  direction {
    director {
      name: "David Leitch"
    }
    rating: "Good to Very Good"
    comments: "The direction on a macroscale is good, as they picked up where they left off; but the movie feels more relaxed this time, because they are playing with house money; the direction on a microscale is very good, as they really lean into the comedic elements of this movie and bring out the best in Deadpool and his metacomedy; the storytelling starts off similar to the first film in how they go back and forth between the past and the present, but only does this for the first quarter as the rest of the movie is pretty linear"
  }
  acting {
    performance {
      actor {
        name: "Ryan Reynolds"
      }
      rating: "Very Good"
      comments: "Continues where he left off, as he perfectly embodies the role, as it feels like he is Deadpool; from his comedic mannerisms to his meta, fourth-wall breaking, but feels more relaxed this time around, as he is more comfortable and is playing with house money this time around"
    }
    performance {
      actor {
        name: "Josh Brolin"
      }
      rating: "Pretty Good to Good"
      comments: "He plays his character well to show his motives and has a good relationship with Reynolds; however, his character is overall pretty flat"
    }
    performance {
      actor {
        name: "Morena Baccarin"
      }
      rating: "Pretty Good"
      comments: "Continues where she left off and has good chemistry with Reynolds, but she really isn\'t given that much screen time in this movie"
    }
    performance {
      actor {
        name: "Julian Dennison"
      }
      rating: "Pretty Good"
      comments: "Plays the rageful teenager filled with trauma well and plays off of Deadpool nicely"
    }
    performance {
      actor {
        name: "Zazie Beetz"
      }
      rating: "Pretty Good"
      comments: "She does her best and has good charisma and chemistry with Reynolds, but her character is written pretty flat overall"
    }
    performance {
      actor {
        name: "T. J. Miller"
      }
      rating: "Pretty Good"
      comments: "Pretty good sidekick to Deadpool"
    }
    performance {
      actor {
        name: "Brianna Hildebrand"
      }
      rating: "Decent to Pretty Good"
      comments: "Plays the teenager role well, but is given less to work with this time around"
    }
    performance {
      actor {
        name: "Karan Soni"
      }
      rating: "Pretty Good to Good"
      comments: "Given more to work with as his Indian comedic relief really has more of a part in the comedy as it helps juxtapose the bad-ass nature of Deadpool"
    }
    cast {
      rating: "Decent"
      comments: "No one feels really outstanding, but everyone plays their part"
    }
    rating: "Decent to Pretty Good"
  }
  story {
    writer {
      name: "Rhett Reese"
    }
    writer {
      name: "Paul Wernick"
    }
    writer {
      name: "Ryan Reynolds"
    }
    rating: "Decent to Pretty Good"
    comments: "The concept is pretty funny as this movie basically is just a metacomedy on how successful the first movie was, so the whole movie felt like they were playing with house money; the overall narrative is pretty formulaic and typical to other superhero movies; the plot structure is pretty similar to other superhero movies, but does have a unique structure in the first 30 minutes; the character writing for Deadpool is pretty good as the whole movie is about him fighting guilt and loss, but the rest of the characters feel very flat"
  }
  screenplay {
    writer {
      name: "Rhett Reese"
    }
    writer {
      name: "Paul Wernick"
    }
    writer {
      name: "Ryan Reynolds"
    }
    rating: "Very Good"
    comments: "The dialogue is better this time around, as it is funnier by continuing the metacomedy from the first film and being more relaxed when making jokes; the whole movie felt like it was playing with house money from the success of the first movie; the humor is an improvement this time around, as it is a lot funnier; the symbolism is somewhat prevalent this time around, as the movie deals with guilt and loss (but in a somewhat surface-level way); the foreshadowing is pretty standard, but the ending honestly throws away what they were building"
  }
  score {
    composer {
      name: "Tyler Bates"
    }
    rating: "Pretty Good"
  }
  cinematography {
    cinematographer {
      name: "Ken Seng"
    }
    rating: "Good"
    comments: "Used well to give the action sequences personality"
  }
  editing {
    editor {
      name: "Dirk Westervelt"
    }
    editor {
      name: "Craig Alpert"
    }
    editor {
      name: "El\303\255sabet Ronaldsd\303\263ttir"
    }
    rating: "Very Good"
    comments: "Feels very crisp and helps make this movie feel unique"
  }
  sound {
    rating: "Very Good"
  }
  visual_effects {
    rating: "Decent"
    comments: "Feels a bit oversaturated"
  }
  costumes {
    rating: "Very Good"
    comments: "Deadpool\'s costume is very iconic, as it stays really true to the comic books"
  }
  pacing: "Pacing is pretty good as they use comedy to slow things down"
  climax: "Climax is a typical comic book ending, but mixed with a lot of humor; the post-credit scene basically removes whatever they were trying to build and feels very unnecessary"
  tone: "Tone is very metacomedy mixed with superhero movie, making it uniquely Deadpool"
  final_notes: ""
  overall: "Overall, a very good sequel that is funnier than the first, as it feels like they were playing with house money when they made this movie, but it reverts back to being a traditional superhero movie with its linear structure and shallow character writing"
}
release_year: 2018
review_date: "07/23/2024"
redux: false
id: 471
imdb_id: "tt5463162"
