title: "Deadpool"
rating: 9.1
review: "Extremely Funny, Incredible Satire, Good Story, Great Screenplay, Good Acting, Good Soundtrack, Some jokes were meh."
release_year: 2016
review_date: "06/18/2017"
redux: false
