title: "Dead Poets Society"
rating: 8.5
review {
  direction {
    director {
      name: "Peter Weir"
    }
    comments: "Good Direction"
  }
  acting {
    actor {
      name: "Robin Williams"
      comments: "Incredible from Robin Williams (really tailored to his personality and was a good precursor to his role in Good Will Hunting)"
    }
    actor {
      name: "Robert Sean Leonard"
      comments: "Good from Robert Sean Leonard"
    }
    actor {
      name: "Ethan Hawke"
      comments: "Good from Ethan Hawke (for what he was supposed to portray)"
    }
    cast: "Pretty Good from the rest of the cast"
    comments: "Good Acting"
  }
  story {
    writer {
      name: "Tom Schulman"
    }
    comments: "Decent to Pretty Good Story (the generic coming-of-age story in a conservative society)"
  }
  screenplay {
    writer {
      name: "Tom Schulman"
    }
    comments: "Very Good Screenplay (filled with many iconic quotes and is really carried out well by the cast (especially Robin Williams))"
  }
  score {
    composer {
      name: "Maurice Jarre"
    }
    comments: "Pretty Good Score"
  }
  cinematography {
    cinematographer {
      name: "John Seale"
    }
    comments: "Good Cinematography"
  }
  sound: "Bad Sound (it makes it sounds extremely cartoony and unrealistic (especially in the spanking scenes))"
  editing {
    editor {
      name: "William Anderson"
    }
    comments: "Pretty Good Editing"
  }
  plot_structure: "Plot Structure was a bit off because the movie just ends at the climax (with no resolution or loose ends even close to being tied)"
  pacing: "Pacing was good (though there definitely needed to be 10-15 minutes added towards the end because of how abrupt the movie ends)"
  climax: "The build to the climax was very well done because you begin to feel for Perry towards the end; the overall climax was fine but the movie just ends at the iconic scene (making it very hard to understand what happens to the characters because there are so many loose ends that are left untied)"
  final_notes: "it is important to point out the plot holes in the movie (especially when Keating probably teaches other students, so like what happens to them; also in the iconic scene not everyone stands up and some of the people who stand up are not even in the Dead Poets Society);the development in all the characters (especially Ethan Hawke\'s character) makes you want to root for them towards the end; the portrayal of John Keating by Robin Williams needs to be highlighted more (even though it can be argued he was not really the main character (I would argue it is Ethan Hawke\'s character), he really steals the show with his iconic charm and comedy, but also shows his dramatic acting ability that prepped him for his career defining performance in Good Will Hunting)"
  overall: "Overall, a coming of age drama that is a bit generic but is carried by Robin Williams\' performance and iconic lines as you root for the characters in the end, even though the movie ends very abruptly"
}
release_year: 1989
review_date: "11/10/2021"
redux: false
id: 226
imdb_id: "tt0097165"
