title: "Django Unchained "
rating: 9.5
review: "Incredible acting by main cast, though some was not better than others, Incredible Screenplay, Incredible Story, Great violence, great music, some music didn\'t really fit the mood"
release_year: 2012
review_date: "03/26/2017"
redux: false
