title: "Don\'t Breathe"
rating: 7.5
review: "Decent acting, probably the movie with the most twists I have ever seen, story was good, not that scary but more of a thriller, had you rooting for the characters."
release_year: 2016
review_date: "06/27/2017"
redux: false
id: 33
imdb_id: "tt4160708"
