title: "Don\'t Look Up"
rating: 7.6
review {
  direction {
    director {
      name: "Adam McKay"
    }
    comments: "Good Direction"
  }
  acting {
    actor {
      name: "Leonardo DiCaprio"
      comments: "Great from Leonardo Dicaprio (though it is not one of his better performances)"
    }
    actor {
      name: "Jennifer Lawrence"
      comments: "Very Good from Jennifer Lawrence (played her character very well, her performance was just limited by what the script allowed her to do)"
    }
    actor {
      name: "Rob Morgan"
      comments: "Good to Very Good from Rob Morgan"
    }
    actor {
      name: "Jonah Hill"
      comments: "Great from Jonah Hill (playing a character he built his name off of early in his career (which is great to see))"
    }
    actor {
      name: "Mark Rylance"
      comments: "Very Good from Mark Rylance (especially with the awkwardness of the tech character)"
    }
    actor {
      name: "Cate Blanchett"
      comments: "Very Good from Cate Blanchett"
    }
    actor {
      name: "Meryl Streep"
      comments: "Good to Very Good from Meryl Streep"
    }
    cast: "Pretty Good to Good from the rest of the cast"
    comments: "Very Good Acting"
  }
  story {
    writer {
      name: "Adam McKay"
    }
    writer {
      name: "David Sirota"
    }
    comments: "Pretty Good Story (Though it is a mess in terms of how the plot is structured (a given from McKay nowadays))"
  }
  screenplay {
    writer {
      name: "Adam McKay"
    }
    comments: "Pretty Good Screenplay (the jokes were actually pretty funny and back to his old self as his script really was not taking itself too seriously as it was in McKay\'s previous two movies (standout joke being the non-sequiturs to the General asking for money for the snacks; it is pretty obvious at how the movie tries to force politics into its message, its just extremely overt and not well carried out cause of how overt it is))"
  }
  score {
    composer {
      name: "Nicholas Britell"
    }
    comments: "Pretty Good Score"
  }
  cinematography {
    cinematographer {
      name: "Linus Sandgren"
    }
    comments: "Good Cinematography"
  }
  sound: "Good Sound"
  editing {
    editor {
      name: "Hank Corwin"
    }
    comments: "Pretty Good Editing"
  }
  plot_structure: "Plot Structure was a bit of the mess (there are really two climaxes (and while the movie does a good job heading into the first one, it becomes a huge mess after the this as it goes to the end))"
  pacing: "No consistent pace at all in the movie (some parts felt slow and some parts felt really fast)"
  climax: "Build to the climax (or two climaxes) is done well as the real climax is more built off of the suspense coming down with the characters\' having their realizations"
  final_notes: "The forced political message of the movie really makes it a mess as the inconsistent structure and very simple showing of this message really hurts at what the movie is trying to show"
  overall: "Overall, it is great to see Adam McKay play more to his roots at not taking himself too seriously as he creates a funny comedy that has some real highlights, though he still has a big mess on his hands from a pretty poorly structured plot and forced political message that is not told well"
}
release_year: 2021
review_date: "01/06/2022"
redux: false
id: 240
imdb_id: "tt11286314"
