title: "Draft Day"
rating: 3.7
review {
  direction {
    director {
      name: "Ivan Reitman"
    }
    comments: "Very Bad Direction (The whole movie just felt like a mess as the acting, storytelling, editing, and tone-setting were just off as it tries way too hard to be a feel-good movie than tell a realistic story)"
  }
  acting {
    actor {
      name: "Kevin Costner"
      comments: "Pretty Bad to Decent from Kevin Costner (The only competent performance in the movie as he does she his presence in all the scenes he is in, but he still is no where near the level he is capable of as he does not have chemistry with the cast and often feels forced into scenes)"
    }
    actor {
      name: "Jennifer Garner"
      comments: "Pretty Bad from Jennifer Garner (Her character is just there for the sole purpose of having a female character that understands sports, and because of this her performance just feels forced as she tries to please so many different angles)"
    }
    actor {
      name: "Denis Leary"
      comments: "Bad to Pretty Bad from Denis Leary (Tries way too hard to be the comedic relief character that he does not play off any of the characters well)"
    }
    actor {
      name: "Frank Langella"
      comments: "Pretty Bad from Frank Langella (Acting just feels very forced (even though he is meant to be cold), just a very one-dimensional performance overall)"
    }
    actor {
      name: "Ellen Burstyn"
      comments: "Pretty Bad from Ellen Burstyn (Ellen why are you in this movie, you are so much better than this role because the character is just so one-dimensional)"
    }
    actor {
      name: "Chadwick Boseman"
      comments: "Pretty Bad from Chadwick Boseman (His body really did not look like a Linebacker and it just felt like this role was not written for him (so he was acting as someone he was not supposed to be))"
    }
    cast: "Bad from the rest of the cast (Just filled with amateurs reading poorly written dialog and receiving poor direction)"
    comments: "Bad Acting"
  }
  story {
    writer {
      name: "Rajiv Joseph"
    }
    writer {
      name: "Scott Rothman"
    }
    comments: "Very Bad Story (The story has very little plot overall and is just incredibly unrealistic (to the point where the movie just starts to not make sense for people who know football); there is also so many side-plots that are just unnecessary)"
  }
  screenplay {
    writer {
      name: "Rajiv Joseph"
    }
    writer {
      name: "Scott Rothman"
    }
    comments: "Very Bad Screenplay (The dialog does not flow at all and is incredibly corny; the movie just jams in facts about football to make it seem it knows what it's talking about on the subject (but just comes off as if it is just posing); the symbolism and foreshadowing is just incredibly corny that its fun to watch how somebody actually wrote this; the message of the film is just so feel good its laughable)"
  }
  score {
    composer {
      name: "John Debney"
    }
    comments: "Decent Score (Just sounds generic)"
  }
  cinematography {
    cinematographer {
      name: "Eric Steelberg"
    }
    comments: "Pretty Bad Cinematography (Tries to give off this heist feel but just comes off as very amateur)"
  }
  sound: "Decent Sound"
  editing {
    editor {
      name: "Sheldon Kahn"
    }
    editor {
      name: "Dana E. Glauberman"
    }
    comments: "Terrible Editing (The movie just felt like it was made on Windows Movie Maker with the transitions and simultaneous cameras it uses; the transition slides also were incredibly corny)"
  }
  visual_effects: "Bad Visual Effects (The effects just felt corny (especially the title slides))"
  production_design: "Decent Production Design (The sets did feel like they were in NFL facilities and at the draft)"
  plot_structure: "Plot Structure was incredibly formulaic and super predictable at what was going to happen next (it was obvious which part of the plot the movie was in)"
  pacing: "Pacing was incredibly slow for a movie that is meant to be fast paced (it just felt like they fit in so much unnecessary plot that the movie could have been cut 30 minutes to make the conflict feel more high stakes)"
  climax: "Climax was decent and probably the best part of the movie (but it was incredibly unrealistic, making it so hard to watch)"
  tone: "Tone tried to emulate a sports drama like Moneyball but just hits so far from the mark that is just comes off as more comedically bad than actually interesting"
  final_notes: "The only really this movie was somewhat watchable was because it was about the NFL (or else I would have turned it off after the halfway mark for how bad it was); the movie is a fun bad though (like it is a watchable movie for how bad it is)"
  overall: "Overall, a movie that is only watchable because it is about the NFL because there is nothing good about this movie as it has some of the worst writing, directing, acting, and editing I have ever seen, though this movie is a fun bad movie if you want to watch it just for how bad and unrealistic it is"
}
release_year: 2014
review_date: "04/29/2023"
redux: false
id: 339
imdb_id: "tt2223990"
