title: "Drive"
rating: 8.7
review: "Great Story, Great screenplay, great cinematography, great concept, ok acting by ryan gosling, him and carey mulligan have like 0 chemistry, very graphic (not a bad thing), There is no pacing to this movie and the final 30 minutes are really rushed. I would have liked to see at least 20-30 more minutes to this movie. "
release_year: 2011
review_date: "03/16/2019"
redux: false
id: 88
imdb_id: "tt0780504"
