title: "Drop"
rating: 0.1
review {
  direction {
    director {
      name: "Christopher Landon"
    }
    rating: "TODO"
    comments: "macroscale is; microscale is; storytelling is; tension is"
  }
  acting {
    performance {
      actor {
        name: "Meghann Fahy"
      }
      rating: "TODO"
      comments: "TODO"
    }
    performance {
      actor {
        name: "Brandon Sklenar"
      }
      rating: "TODO"
      comments: "TODO"
    }
    performance {
      actor {
        name: "Violett Beane"
      }
      rating: "TODO"
      comments: "TODO"
    }
    performance {
      actor {
        name: "Jacob Robinson"
      }
      rating: "TODO"
      comments: "TODO"
    }
    performance {
      actor {
        name: "Reed Diamond"
      }
      rating: "TODO"
      comments: "TODO"
    }
    performance {
      actor {
        name: "Gabrielle Ryan"
      }
      rating: "TODO"
      comments: "TODO"
    }
    performance {
      actor {
        name: "Jeffery Self"
      }
      rating: "TODO"
      comments: "TODO"
    }
    performance {
      actor {
        name: "Ed Weeks"
      }
      rating: "TODO"
      comments: "TODO"
    }
    performance {
      actor {
        name: "Travis Nelson"
      }
      rating: "TODO"
      comments: "TODO"
    }
    cast {
      rating: "TODO"
      comments: "TODO"
    }
    rating: "TODO"
  }
  story {
    writer {
      name: "Jillian Jacobs"
    }
    writer {
      name: "Chris Roach"
    }
    rating: "TODO"
    comments: "The concept is; the plot structure is; character writing is"
  }
  screenplay {
    writer {
      name: "Jillian Jacobs"
    }
    writer {
      name: "Chris Roach"
    }
    rating: "TODO"
    comments: "The dialogue is; the humor is; the symbolism is; the foreshadowing is"
  }
  score {
    composer {
      name: "Bear McCreary"
    }
    rating: "TODO"
    comments: "TODO"
  }
  soundtrack {
    rating: "TODO"
    comments: "TODO"
  }
  cinematography {
    cinematographer {
      name: "Marc Spicer"
    }
    rating: "TODO"
    comments: "TODO"
  }
  editing {
    editor {
      name: "Ben Baudhuin"
    }
    rating: "TODO"
    comments: "TODO"
  }
  sound {
    rating: "TODO"
    comments: "TODO"
  }
  visual_effects {
    rating: "TODO"
    comments: "TODO"
  }
  production_design {
    rating: "TODO"
    comments: "TODO"
  }
  makeup {
    rating: "TODO"
    comments: "TODO"
  }
  costumes {
    rating: "TODO"
    comments: "TODO"
  }
  pacing: "Pacing "
  climax: "Climax "
  tone: "Tone "
  final_notes: ""
  overall: "Overall, "
}
release_year: 2025
review_date: "03/09/2025"
redux: false
id: 546
imdb_id: "tt32149847"
