title: "Dumb Money"
rating: 7.6
review {
  direction {
    director {
      name: "Craig Gillespie"
    }
    rating: "Good"
    comments: "Does a good job at telling the story and progressing the narrative forward on both a macro and a micro scale as he plays the line between comedy and drama to keep the movie entertaining yet focused; gets a lot out of his actors as he takes more traditionally comedic actors and gets them to be somewhat dramatic"
  }
  acting {
    performance {
      actor {
        name: "Paul Dano"
      }
      rating: "Good"
      comments: "Really embodies the character and uses a lot of his personal persona to tell this story; feels like the character was written for him"
    }
    performance {
      actor {
        name: "Pete Davidson"
      }
      rating: "Pretty Good"
      comments: "Plays the typical Pete Davidson character"
    }
    performance {
      actor {
        name: "Vincent D\'Onofrio"
      }
      rating: "Pretty Good"
      comments: "Uses the most out of his screentime"
    }
    performance {
      actor {
        name: "America Ferrera"
      }
      rating: "Pretty Good to Good"
      comments: "Shows more of her dramatic chops than the rest of the cast, but there are moments that are kind of cringe though"
    }
    performance {
      actor {
        name: "Nick Offerman"
      }
      rating: "Pretty Good to Good"
      comments: "Embodies the character well"
    }
    performance {
      actor {
        name: "Anthony Ramos"
      }
      rating: "Pretty Good"
      comments: "Has a good amount of charisma in the role"
    }
    performance {
      actor {
        name: "Sebastian Stan"
      }
      rating: "Good"
      comments: "Really embodied the role as it felt very believable he was the CEO of Robinhood"
    }
    performance {
      actor {
        name: "Shailene Woodley"
      }
      rating: "Pretty Good"
      comments: "Works off of Dano well"
    }
    performance {
      actor {
        name: "Seth Rogen"
      }
      rating: "Pretty Good to Good"
      comments: "Uses a lot of his experience to show both the comedic sides of the character along with some of the more dramatic parts"
    }
    cast {
      rating: "Decent"
      comments: "The adult cast did a pretty good job in their roles, but the college students were incredibly cringe"
    }
    rating: "Pretty Good"
  }
  story {
    writer {
      name: "Lauren Schuker Blum"
    }
    writer {
      name: "Rebecca Angelo"
    }
    rating: "Pretty Good"
    comments: "Really entertaining story and does a pretty good job at being someone true to the story (at least with the main plotline because of how public it was); the more composite storylines were kinda irrelevant and one of them could have been cut to save on time; the story was laid out well and the more Reddit/memer side of the story felt like something Internet Historian would make; the use of real footage and interviews with the actors helped with keeping it more accurate"
  }
  screenplay {
    writer {
      name: "Lauren Schuker Blum"
    }
    writer {
      name: "Rebecca Angelo"
    }
    rating: "Decent"
    comments: "The dialogue embodies how Wall Street Bets and Roaring Kitty talked (which is a double-edged sword cause of how cringy it is), but was mostly pretty simplistic; the jokes were pretty funny and helped keep the movie entertaining; the symbolism is pretty overt and the message was on-the-nose; the foreshadowing is on par with other biopics"
  }
  score {
    composer {
      name: "Will Bates"
    }
    rating: "Decent"
    comments: "Somewhat there"
  }
  soundtrack {
    rating: "Good"
    comments: "Really stayed true to the time period and made the movie more entertaining"
  }
  cinematography {
    cinematographer {
      name: "Nikolas Karakatsanis"
    }
    rating: "Good"
  }
  editing {
    editor {
      name: "Kirk Baxter"
    }
    rating: "Pretty Good"
    comments: "Really feels like something Internet Historian would make"
  }
  sound {
    rating: "Good"
    comments: "Makes it feel very memey/Reddity"
  }
  plot_structure: "Plot Structure was pretty good as it was a main storyline of what happened and multiple composite storylines that all follow the main storyline (with all of them having their narrative journey); one of these composite storylines could have been cut to make the movie a bit tighter as one main storyline and three composite storylines is a lot for a runtime of this size"
  pacing: "Pacing was pretty good as it wasn\'t too short or fast"
  climax: "Climax was executed pretty well as it just follows what happened (presenting some of its movie magic interjecting the actual events that happened)"
  tone: "Tone felt like something Internet Historian would make (at least when trying to emulate Wall Street Bets); the more dramatic elements felt like something from a Comedy-Drama"
  final_notes: "I understand that The Social Network (who is the same author of the material) was made right after the events but it just feels like this movie came out way too early"
  overall: "Overall, an entertaining movie about the Wall Street Bets situation as the movie stays true to being a comedy-drama as it uses comedic actors and a lot of internet humor to help tell a somewhat serious situation, but because of this it feels like the movie is very cringy at times; also, it just feels like the movie was made too soon as it like just happened (which ruins a lot of the learning aspect of a biopic)"
}
release_year: 2023
review_date: "10/04/2023"
redux: false
id: 370
imdb_id: "tt13957560"
