title: "Dunkirk"
rating: 9.3
review: "The movie is one of the most accurate depictions of war. Nolan brilliantly depicts the emotions of war with brilliant direction meshed with incredible cinematography, and a score that blends with the scenes. None of the bullshit with the writing or acting as it is stripped down to what it should be."
release_year: 2017
review_date: "08/05/2017"
redux: false
