title: "Elf"
rating: 8.4
review {
  direction {
    director {
      name: "Jon Favreau"
    }
    rating: "Very Good"
    comments: "Especially for the lengths Jon Favreau went to limit the use of CGI"
  }
  acting {
    performance {
      actor {
        name: "Will Ferrell"
      }
      rating: "Very Good"
    }
    cast {
      rating: "Pretty Good"
      comments: "Everyone plays their part well"
    }
    rating: "Good"
  }
  story {
    writer {
      name: "David Berenbaum"
    }
    rating: "Very Good/Iconic"
    comments: "Although it is filled with cliches and is very safe"
  }
  screenplay {
    writer {
      name: "David Berenbaum"
    }
    rating: "Very Good"
  }
  cinematography {
    cinematographer {
      name: "Greg Gardiner"
    }
    rating: "Great"
    comments: "Uses force perspective very well (even though it can lead to inconsistencies at times)"
  }
  editing {
    editor {
      name: "Dan Lebental"
    }
    rating: "Very Good"
  }
  visual_effects {
    rating: "Great"
    comments: "Especially for the stop motion parts of the film to give is a very classic Christmas movie feel"
  }
  pacing: "Pacing was pretty good overall"
  climax: "Build to climax is pretty abrupt but the overall ending is pretty intense for a Christmas movie and Favreau pulls it off very well"
  final_notes: ""
  overall: "Overall, an iconic christmas movie that is filled with many emotions, makes you root for the characters, and makes you remember the spirit of christmas, even though the movie is very safe, formulaic, cliche, and plays its cards very close to its chest (something I can\'t really blame given its a family Christmas movie)"
}
release_year: 2003
review_date: "12/26/2020"
redux: false
id: 174
imdb_id: "tt0319343"
