title: "Eternal Sunshine of the Spotless Mind"
rating: 9.6
review: "Great to Incredible direction, Brilliant Screenplay, Brilliant Story, Great Acting by the cast (Incredible Acting by Jim Carrey and Kate Winslet), Great Visual Effects, Very Good Cinematography, Incredible Editing, Good Score, Incredible displays of emotion, Pacing a bit slow (Could\'ve cut about 15-20 mins), Plot was a bit confusing till the end where everything begins to make sense, One of the best movies to depict mental illness an loneliness."
release_year: 2004
review_date: "08/08/2020"
redux: false
