title: "Ex Machina"
rating: 8.6
review {
  direction {
    director {
      name: "Alex Garland"
    }
    rating: "Great"
    comments: "Like the stylistic choices he made by interweaving the scenic shots/sets with the character\'s dialogue"
  }
  acting {
    performance {
      actor {
        name: "Domhnall Gleeson"
      }
      rating: "Pretty Good"
    }
    performance {
      actor {
        name: "Oscar Isaac"
      }
      rating: "Very Good"
    }
    performance {
      actor {
        name: "Alicia Vikander"
      }
      rating: "Very Good"
    }
    cast {
      rating: "Good"
    }
    rating: "Good"
  }
  story {
    writer {
      name: "Alex Garland"
    }
    rating: "Great"
    comments: "Shows the effects of AI and actually putting trust into cognizant automata"
  }
  screenplay {
    writer {
      name: "Alex Garland"
    }
    rating: "Very Good to Great"
    comments: "While the movie was pretty spot on with some of the technical jargon/ideas, it also definitely forced in a lot of buzz words that no programmer/software engineer would ever say"
  }
  score {
    composer {
      name: "Ben Salisbury"
    }
    composer {
      name: "Geoff Barrow"
    }
    rating: "Great to Incredible"
    comments: "Used well in how it is blended with the mood/feelings the audience has towards what is presented (especially when there is a heartbeat increasing to show the story becoming more tense)"
  }
  cinematography {
    cinematographer {
      name: "Rob Hardy"
    }
    rating: "Great to Incredible"
    comments: "Espiecially how it it used the different intensities/colors of lighting to show the mood"
  }
  visual_effects {
    rating: "Incredible"
    comments: "Especailly for a movie with a lower budget"
  }
  production_design {
    rating: "Incredible"
  }
  plot_structure: "Plot Structure was great"
  pacing: "Pacing was good (Runtime was good)"
  climax: "Build to the climax was great but the overall climax/resolution felt very off (even though the events of the movie were exactly how I expected/wanted to happen)"
  final_notes: ""
  overall: "Overall, a film that is very visually pleasing (an artsy movie that actually pulls it off very nicely) and well made that makes society question AI and how cognizant we should make Automata (definitely one of the better portrayals of this phenomenon), even if the film blows it more out of proportion/exaggerates the extent/ideas behind it"
}
release_year: 2014
review_date: "05/30/2021"
redux: false
id: 195
imdb_id: "tt0470752"
