title: "Fargo"
rating: 8.6
review {
  direction {
    director {
      name: "Joel Coen"
    }
    comments: "Very Good Direction"
  }
  acting {
    actor {
      name: "Frances McDormand"
      comments: "Great from Frances McDormand"
    }
    actor {
      name: "William H. Macy"
      comments: "Very Good from William H. Macy"
    }
    actor {
      name: "Steve Buscemi"
      comments: "Good to Very Good from Steve Buscemi"
    }
    cast: "Pretty Good from the rest of the cast (Good from the remaining main cast, and decent from the supporting cast and extras)"
    comments: "Good Acting"
  }
  story {
    writer {
      name: "Joel and Ethan Coen"
    }
    comments: "Great Story (though is very surface level in its imagery and symbolism)"
  }
  screenplay {
    writer {
      name: "Joel and Ethan Coen"
    }
    comments: "Great Screenplay (laced with witty, quirky midwestern dialogue (as seen by the intentional awkward pauses during the Minnesotan conversations))"
  }
  cinematography {
    cinematographer {
      name: "Roger Deakins"
    }
    comments: "Great to Incredible Cinematography (Especially the distant panning shots that show the contrast between the main images and the snow)"
  }
  pacing: "Pacing is Great for the most part given its short runtime (but is incredibly rushed towards the end (particularly the final 15-20 minutes))"
  overall: "Overall, the Coen brothers give a prime example of why they are some of the best screenwriters in Hollywood as they make a short runtime filled with many memorable, funny moments (even though it may not be as incredible as their other movies), but it does falter towards the end as it is incredibly rushed as it feels like it could\'ve used 15 more minutes to keep up to the pace it had for the majority of the movie"
}
release_year: 1996
review_date: "11/22/2020"
redux: false
id: 168
imdb_id: "tt0116282"
