title: "Fast Times at Ridgemont High"
rating: 0.1
review {
  direction {
    director {
      name: "Amy Heckerling"
    }
    rating: "TODO"
    comments: "macroscale is; microscale is; direction of actors is; storytelling is; tension is"
  }
  acting {
    performance {
      actor {
        name: "Sean Penn"
      }
      rating: "TODO"
      comments: "TODO"
    }
    performance {
      actor {
        name: "Jennifer Jason Leigh"
      }
      rating: "TODO"
      comments: "TODO"
    }
    performance {
      actor {
        name: "Judge Reinhold"
      }
      rating: "TODO"
      comments: "TODO"
    }
    performance {
      actor {
        name: "Phoebe Cates"
      }
      rating: "TODO"
      comments: "TODO"
    }
    performance {
      actor {
        name: "Brian Backer"
      }
      rating: "TODO"
      comments: "TODO"
    }
    performance {
      actor {
        name: "Robert Romanus"
      }
      rating: "TODO"
      comments: "TODO"
    }
    performance {
      actor {
        name: "Ray Walston"
      }
      rating: "TODO"
      comments: "TODO"
    }
    cast {
      rating: "TODO"
      comments: "TODO"
    }
    rating: "TODO"
  }
  story {
    writer {
      name: "Cameron Crowe"
    }
    rating: "TODO"
    comments: "The concept is; the plot structure is; flow between sequences is; character writing is"
  }
  screenplay {
    writer {
      name: "Cameron Crowe"
    }
    rating: "TODO"
    comments: "The dialogue is; the humor is; the symbolism is; the foreshadowing is"
  }
  cinematography {
    cinematographer {
      name: "Matthew F. Leonetti"
    }
    rating: "TODO"
    comments: "TODO"
  }
  editing {
    editor {
      name: "Eric Jenkins"
    }
    rating: "TODO"
    comments: "TODO"
  }
  sound {
    rating: "TODO"
    comments: "TODO"
  }
  visual_effects {
    rating: "TODO"
    comments: "TODO"
  }
  production_design {
    rating: "TODO"
    comments: "TODO"
  }
  makeup {
    rating: "TODO"
    comments: "TODO"
  }
  costumes {
    rating: "TODO"
    comments: "TODO"
  }
  pacing: "Pacing "
  climax: "Climax "
  tone: "Tone "
  final_notes: ""
  overall: "Overall, "
}
release_year: 1982
review_date: "08/31/2024"
redux: false
id: 483
imdb_id: "tt0083929"
