title: "Fences"
rating: 6.4
review: "First Half extremely boring (Did not connect with story), Southern drawl makes it a turn off, Great Acting by all characters (movie only acting though), Viola Davis was incredible, Screenplay makes it only based on acting so might appeal to others who like plays and broadway."
release_year: 2016
review_date: "02/12/2017"
redux: false
id: 5
imdb_id: "tt2671706"
