title: "Field of Dreams"
rating: 7.8
review {
  direction {
    director {
      name: "Phil Alden Robinson"
    }
    comments: "Direction ()"
  }
  acting {
    actor {
      name: "Kevin Costner"
      comments: " from Kevin Costner ()"
    }
    actor {
      name: "Amy Madigan"
      comments: " from Amy Madigan ()"
    }
    actor {
      name: "James Earl Jones"
      comments: " from James Earl Jones ()"
    }
    actor {
      name: "Ray Liotta"
      comments: " from Ray Liotta ()"
    }
    actor {
      name: "Burt Lancaster"
      comments: " from Burt Lancaster ()"
    }
    cast: "from the rest of the cast ()"
    comments: " Acting "
  }
  story {
    writer {
      name: "Phil Alden Robinson"
    }
    comments: "Story ()"
  }
  screenplay {
    writer {
      name: "Phil Alden Robinson"
    }
    comments: "Screenplay ()"
  }
  score {
    composer {
      name: "James Horner"
    }
    comments: "Score ()"
  }
  cinematography {
    cinematographer {
      name: "John Lindley"
    }
    comments: "Cinematography ()"
  }
  sound: "Sound ()"
  editing {
    editor {
      name: "Ian Crafford"
    }
    comments: "Editing ()"
  }
  visual_effects: "Visual Effects ()"
  production_design: "Production Design ()"
  makeup: "Makeup ()"
  costumes: "Costumes ()"
  plot_structure: "Plot Structure "
  pacing: "Pacing "
  climax: "climax "
  tone: "tone"
  final_notes: ""
  overall: "Overall, "
}
release_year: 1989
review_date: "08/16/2021"
redux: false
