title: "Field of Dreams"
rating: 7.8
review {
  direction {
    director {
      name: "Phil Alden Robinson"
    }
    comments: "Pretty Good to Good Direction"
  }
  acting {
    actor {
      name: "Kevin Costner"
      comments: "Pretty Good to Good from Kevin Costner (Kinda has the same expression throughout the movie (not bad but very static))"
    }
    actor {
      name: "Amy Madigan"
      comments: "Good to Very Good from Amy Madigan"
    }
    actor {
      name: "James Earl Jones"
      comments: "Good to Very Good from James Earl Jones"
    }
    cast: "Pretty Bad to Decent from the rest of the cast"
    comments: "Decent to Pretty Good Acting"
  }
  story {
    writer {
      name: "Phil Alden Robinson"
    }
    comments: "Decent to Pretty Good Story (Though a majority of the movie stems away from the actual subject of the film as the film takes about 40 minutes into a pointless side quest)"
  }
  screenplay {
    writer {
      name: "Phil Alden Robinson"
    }
    comments: "Pretty Good Screenplay (Has iconic lines and good moments but the rest of the dialogue reeks of the 80s and is kinda bland)"
  }
  score {
    composer {
      name: "James Horner"
    }
    comments: "Great Score"
  }
  cinematography {
    cinematographer {
      name: "John Lindley"
    }
    comments: "Pretty Good Cinematography"
  }
  editing {
    editor {
      name: "Ian Crafford"
    }
    comments: "Good Film Editing"
  }
  pacing: "Pacing was extremely fast in the beginning then pretty good in the middle and then pretty slow towards the end with a very abrupt ending (though the ending of the movie was decent to pretty good with everything coming back full circle (As all the points come to the purpose of Kevin Costner's character))"
  climax: "The build to the climax was very abrupt as you realize you missed the climax right as it is about to end; the runtime was on the shorter side but was very poorly used as there definitely could've been 10-20 minutes added towards the climax/resolution; the symbolism and themes throughout the movie are very romantic/hopeful as it makes you believe in a heavenly body experience as you romanticize about baseball"
  overall: "Overall, a Decent to Pretty Good movie that makes you root for the characters and gets very emotional at times as you go through a baseball themed adventure but is very overrated as the film does not use its runtime effectively and stems away from the subject/purpose of the movie"
}
release_year: 1989
review_date: "08/16/2021"
redux: false
