title: "Ford v. Ferrari"
rating: 8.6
review: "Great Acting, Good Story, Great technicals, Good screenplay, fun plot, good movie to watch overall, nothing extremely stellar except for technicals."
release_year: 2019
review_date: "03/26/2020"
redux: false
