title: "Forrest Gump"
rating: 9.6
review {
  direction {
    director {
      name: "Robert Zemeckis"
    }
    comments: "Great to Incredible Direction (The ability to go from scene to scene while keeping the narrative going was a highlight; also, did a great job in conversation scenes and showing the vast scenary)"
  }
  acting {
    actor {
      name: "Tom Hanks"
      comments: "Incredible to Brilliant from Tom Hanks (Has the charm and ability to play someone who holds heart (even though he may be slow), also his ability to use expressions to show emotion was also a highlight)"
    }
    actor {
      name: "Robin Wright"
      comments: "Very Good from Robin Wright (though she really was the antagonist of the movie given how much struggle she makes Forrest go through at each stage of his life)"
    }
    actor {
      name: "Gary Sinise"
      comments: "Great from Gary Sinise (the ability to show trauma and overcoming it)"
    }
    actor {
      name: "Sally Field"
      comments: "Very Good to Great from Sally Field"
    }
    cast: "Good from the rest of the cast"
    comments: "Very Good to Great Acting"
  }
  story {
    writer {
      name: "Eric Roth"
    }
    comments: "Brilliant Story (with how iconic each segment of Forrest\'s life makes him who he is and the storytelling from Tom Hanks to help drive the movie forward (and not just tell what is happening))"
  }
  screenplay {
    writer {
      name: "Eric Roth"
    }
    comments: "Incredible Screenplay (filled with iconic lines)"
  }
  score {
    composer {
      name: "Alan Silvestri"
    }
    comments: "Good Score"
  }
  soundtrack: "Good to Very Good Soundtrack (to help show which time period the story was in)"
  cinematography {
    cinematographer {
      name: "Don Burgess"
    }
    comments: "Great Cinematography (especially its ability to show the vastness of many of the scenes)"
  }
  sound: "Good Sound"
  editing {
    editor {
      name: "Arthur Schmidt"
    }
    comments: "Great to Incredible Editing (especially its ability to go between different parts of the story)"
  }
  visual_effects: "Pretty Good Visual Effects (Pretty Good use of CGI (though it was a bit over-the-top at times))"
  plot_structure: "Plot Structure was incredibly unique as each segment in the first 3/4 of the movie were more used as vignettes into Forrest\'s life and the final quarter is meant more to show the present and show what Forrest\'s future will be (however, the overarching plot structure does a great job in still introducing character, introducing some conflict, and showing character development through passage of time)"
  pacing: "Pacing was good as the movie never felt like it was dragging even though it was a bit on the longer side (partly due to the nature of how the story is built with different episodes from Forrest\'s life)"
  climax: "Build to the climax was kinda abrupt but the climax itself is the epiphany moment in Forrest\'s life in what his true purpose is (despite all that he has accomplished)"
  final_notes: "the character of Forrest Gump is important to highlight as it is a true mainstay in American Society (cause even though he may not be the smartest, he had so much heart and love to where he could accomplish anything that was set in his path)"
  overall: "Overall, an incredible movie that is one of the most fun watches anyone can ever have as the audience goes through the incredible adventure of Forrest Gump\'s life to see how much someone can do despite having so little (A true testament of the importance love and heart can have as a driving factor)"
}
release_year: 1994
review_date: "11/22/2021"
redux: false
id: 228
imdb_id: "tt0109830"
