title: "Free Solo"
rating: 8.8
review: "Great Documentation of Alex\'s journey to clim El Cap, Some parts were like the generic Doc parts that have nothing to do with the event itself, extremely suspenseful (especially the final 30 minutes), Great Music, Overall very enjoyable to watch."
release_year: 2018
review_date: "06/06/2019"
redux: false
