title: "Friendship"
rating: 0.1
review {
  direction {
    director {
      name: "Andrew DeYoung"
    }
    rating: "TODO"
    comments: "macroscale is; microscale is; storytelling is; tension is"
  }
  acting {
    performance {
      actor {
        name: "Tim Robinson"
      }
      rating: "TODO"
      comments: "TODO"
    }
    performance {
      actor {
        name: "Paul Rudd"
      }
      rating: "TODO"
      comments: "TODO"
    }
    performance {
      actor {
        name: "Kate Mara"
      }
      rating: "TODO"
      comments: "TODO"
    }
    performance {
      actor {
        name: "Jack Dylan Grazer"
      }
      rating: "TODO"
      comments: "TODO"
    }
    performance {
      actor {
        name: "Josh Segarra"
      }
      rating: "TODO"
      comments: "TODO"
    }
    performance {
      actor {
        name: "Billy Bryk"
      }
      rating: "TODO"
      comments: "TODO"
    }
    cast {
      rating: "TODO"
      comments: "TODO"
    }
    rating: "TODO"
  }
  story {
    writer {
      name: "Andrew DeYoung"
    }
    rating: "TODO"
    comments: "The concept is; the plot structure is; character writing is"
  }
  screenplay {
    writer {
      name: "Andrew DeYoung"
    }
    rating: "TODO"
    comments: "The dialogue is; the humor is; the symbolism is; the foreshadowing is"
  }
  score {
    composer {
      name: "Keegan DeWitt"
    }
    rating: "TODO"
    comments: "TODO"
  }
  soundtrack {
    rating: "TODO"
    comments: "TODO"
  }
  cinematography {
    cinematographer {
      name: "Andy Rydzewski"
    }
    rating: "TODO"
    comments: "TODO"
  }
  editing {
    editor {
      name: "Sophie Corra"
    }
    rating: "TODO"
    comments: "TODO"
  }
  sound {
    rating: "TODO"
    comments: "TODO"
  }
  visual_effects {
    rating: "TODO"
    comments: "TODO"
  }
  production_design {
    rating: "TODO"
    comments: "TODO"
  }
  makeup {
    rating: "TODO"
    comments: "TODO"
  }
  costumes {
    rating: "TODO"
    comments: "TODO"
  }
  pacing: "Pacing "
  climax: "Climax "
  tone: "Tone "
  final_notes: ""
  overall: "Overall, "
}
release_year: 2024
review_date: "03/11/2025"
redux: false
id: 550
imdb_id: "tt30505698"
