title: "Game Night"
rating: 6.8
review {
  direction {
    director {
      name: "John Francis Daley"
    }
    director {
      name: "Jonathan Goldstein"
    }
    rating: "Decent to Pretty Good"
    comments: "The direction on a macroscale cultivates a very silly, action-comedy that is overall entertaining; the direction on a microscale is very silly and this is where the comedy comes out; the storytelling is a bit convoluted because they try to have too many twists to make the movie somewhat of a parody but it ends up just making the movie more confusing"
  }
  acting {
    performance {
      actor {
        name: "Jason Bateman"
      }
      rating: "Pretty Good"
      comments: "He plays his typical straight man in a comedy role he is known for; there was a reason he was hired, as this is a role he is very comfortable with"
    }
    performance {
      actor {
        name: "Rachel McAdams"
      }
      rating: "Pretty Good"
      comments: "Her experience in comedies makes her performance feel natural; she has pretty good chemistry with Bateman"
    }
    performance {
      actor {
        name: "Jesse Plemons"
      }
      rating: "Good"
      comments: "Still wondering how that could be profitable for Frito-Lay"
    }
    cast {
      rating: "Decent"
      comments: "Everyone seems like they are having fun; a lot of the performances are what you would get in an action-comedy"
    }
    rating: "Pretty Good"
  }
  story {
    writer {
      name: "Mark Perez"
    }
    rating: "Decent to Pretty Good"
    comments: "The concept is very silly and goofy, as it mixes a light-hearted idea like Game Night with espionage; the plot structure is fine for the most part, but the ending gets a bit convoluted with all the intentional twists and turns; character writing is funny for Jesse Plemons\' character because he is just someone who really wants to be in Game Night"
  }
  screenplay {
    writer {
      name: "Mark Perez"
    }
    rating: "Decent to Pretty Good"
    comments: "The dialogue is very silly and dumb, but that\'s what makes it funny because there are many memorable moments; the foreshadowing is a little all over the place because the movie tries to subvert our expectations with many twists, but it ends up making the movie more convoluted"
  }
  score {
    composer {
      name: "Cliff Martinez"
    }
    rating: "Decent"
    comments: "Helps set the tone"
  }
  cinematography {
    cinematographer {
      name: "Barry Peterson"
    }
    rating: "Decent to Pretty Good"
    comments: "Pretty typical for an action comedy, but I did like the shots that make the world look like a board game"
  }
  editing {
    editor {
      name: "Jamie Gross"
    }
    editor {
      name: "Gregory Plotkin"
    }
    editor {
      name: "David Egan"
    }
    rating: "Decent"
    comments: "Typical of an action comedy"
  }
  sound {
    rating: "Decent"
    comments: "Typical of an action comedy"
  }
  visual_effects {
    rating: "Decent to Pretty Good"
    comments: "Typical of an over-the-top action-comedy, but I enjoyed the shots where they made the world look like a board game"
  }
  pacing: "Pacing is a little too fast, as if they are breezing through the story"
  climax: "Climax is a little too convoluted because of all the twists they try to include, but the ending itself was pretty predictable"
  tone: "The tone is very typical of a silly action-comedy"
  final_notes: ""
  overall: "Overall, a silly action-comedy that makes you wonder, \"how could that be profitable for Frito-Lay\""
}
release_year: 2018
review_date: "02/15/2025"
redux: false
id: 538
imdb_id: "tt2704998"
