title: "Get Out"
rating: 8.8
review: "Movie comes around full circle, the shift in the middle explains for the uncomfortable and bad acting in the beginning of the movie, good acting, great story, natural but awkward screenplay, more of a thriller than horror movie, great last 3rd, Movie makes you feel very uncomfortable but the movie makes clear why it does this."
release_year: 2017
review_date: "03/26/2017"
redux: false
