title: "Good Will Hunting"
rating: 9.6
review: "Great Acting by top 2 1/2, Brilliant Screenplay, Great Story, Score complements the emotions of the scenes, Great Character development"
release_year: 1997
review_date: "06/13/2017"
redux: false
