title: "Good Time"
rating: 8.1
review: "Great Acting by Robert Pattinson, Very weird but interesting plot, Great Screenplay, Good acting by the cast but not extras, Great visuals and cinematography, Pacing was very fast paced but some of the plot details were kinda wtf and not needed, not anxiety driven as it was meant to be, good relationship between brothers, Good direction, good score."
release_year: 2017
review_date: "01/24/2020"
redux: false
id: 129
imdb_id: "tt4846232"
