title: "Gook"
rating: 8.2
review: "Great Story, Good Screenplay (Sometimes not that good though), Good Acting, Good Direction, was in black in white (stylistic choice so cannot hate)."
release_year: 2017
review_date: "09/20/2019"
redux: false
id: 104
imdb_id: "tt6057032"
