title: "Groundhog Day"
rating: 8.6
review: "Funny to Very Funny movie (Especially Bill Murray), Iconic story, good screenplay, Movie is kinda about nothing but thats pretty much the point, the character development is shown but its kinda rushed towards the end against doing it throughout the movie, Good acting by the cast (very good by murray). Overall, classic comedy movie that is a great movie to watch on February 2nd"
release_year: 1993
review_date: "08/23/2020"
redux: false
