title: "Halloween"
rating: 7.9
review {
  direction {
    director {
      name: "John Carpenter"
    }
    rating: "Good"
  }
  acting {
    cast {
      rating: "Pretty Good to Good"
      comments: "Especially for the younger, inexperienced actors"
    }
    rating: "Pretty Good to Good"
  }
  story {
    writer {
      name: "John Carpenter"
    }
    writer {
      name: "Debra Hill"
    }
    rating: "Very Good/Iconic"
  }
  screenplay {
    writer {
      name: "John Carpenter"
    }
    writer {
      name: "Debra Hill"
    }
    rating: "Good"
    comments: "Good use of suspense and no major flows in the dialogue"
  }
  score {
    composer {
      name: "John Carpenter"
    }
    rating: "Very Good/Iconic"
  }
  cinematography {
    cinematographer {
      name: "Dean Cundey"
    }
    rating: "Very Good"
    comments: "Really liked the POV shots and thought it overall very well executed especially with such a low budget"
  }
  sound {
    rating: "Good"
    comments: "Good use of sound effects to help build suspense"
  }
  plot_structure: "Plot Structure was pretty poor as it felt that the first hour of the movie is the exposition and the final 30 minutes was the real horror and suspenseful parts of the movie (although the transition/build between these two parts was very well executed)"
  pacing: "Pacing was very slow overall as the entire movie felt it was dragging up until the final 30 minutes (there were moments where you could tell they were filling time, especially with the panning shots)"
  climax: "Climax of the movie was very well executed as there was much suspense and misdirection that gave Halloween and Michael Myers their household names"
  final_notes: ""
  overall: "Overall, a fun, iconic horror movie that made the most that it could from its very low budget by creating iconic moments and characters, even though it suffers from a poorly constructed plot structure that spends the first hour in dragging, exposition moments"
}
release_year: 1978
review_date: "10/21/2021"
redux: false
id: 221
imdb_id: "tt0077651"
