title: "Harold & Kumar Go to White Castle"
rating: 8.3
review: "Great Story, pretty funny, Great acting from big three characters, good message on Asian representation, Plot flows nicely and is pacing."
release_year: 2004
review_date: "11/21/2019"
redux: false
id: 109
imdb_id: "tt0366551"
