title: "Her"
rating: 9.2
review: "Incredible Screenplay at times and great at other times, Great acting by the cast (especially Joaquin Phoenix and Scarlett Johansson), great story, great direction, good score, movie was a little too sexual at times, final 1/4 was very good, incredible cinematography, incredible ending sequence."
release_year: 2013
review_date: "06/04/2020"
redux: false
