title: "Holland"
rating: 0.1
review {
  direction {
    director {
      name: "Mimi Cave"
    }
    rating: "TODO"
    comments: "macroscale is; microscale is; storytelling is; tension is"
  }
  acting {
    performance {
      actor {
        name: "Nicole Kidman"
      }
      rating: "TODO"
      comments: "TODO"
    }
    performance {
      actor {
        name: "Matthew Macfadyen"
      }
      rating: "TODO"
      comments: "TODO"
    }
    performance {
      actor {
        name: "Jude Hill"
      }
      rating: "TODO"
      comments: "TODO"
    }
    performance {
      actor {
        name: "Gael Garc\303\255a Bernal"
      }
      rating: "TODO"
      comments: "TODO"
    }
    cast {
      rating: "TODO"
      comments: "TODO"
    }
    rating: "TODO"
  }
  story {
    writer {
      name: "Andrew Sodorski[1]"
    }
    rating: "TODO"
    comments: "The concept is; the plot structure is; character writing is"
  }
  screenplay {
    writer {
      name: "Andrew Sodorski[1]"
    }
    rating: "TODO"
    comments: "The dialogue is; the humor is; the symbolism is; the foreshadowing is"
  }
  score {
    composer {
      name: "Alex Somers"
    }
    rating: "TODO"
    comments: "TODO"
  }
  soundtrack {
    rating: "TODO"
    comments: "TODO"
  }
  cinematography {
    cinematographer {
      name: "Pawel Pogorzelski[3]"
    }
    rating: "TODO"
    comments: "TODO"
  }
  editing {
    editor {
      name: "Martin Pensa"
    }
    rating: "TODO"
    comments: "TODO"
  }
  sound {
    rating: "TODO"
    comments: "TODO"
  }
  visual_effects {
    rating: "TODO"
    comments: "TODO"
  }
  production_design {
    rating: "TODO"
    comments: "TODO"
  }
  makeup {
    rating: "TODO"
    comments: "TODO"
  }
  costumes {
    rating: "TODO"
    comments: "TODO"
  }
  pacing: "Pacing "
  climax: "Climax "
  tone: "Tone "
  final_notes: ""
  overall: "Overall, "
}
release_year: 2025
review_date: "03/10/2025"
redux: false
id: 547
imdb_id: "tt3045628"
