title: "Honey Boy"
rating: 9.3
review: "Incredible Acting by the main cast (especially Shia LaBeouf), Great Screenplay (Incredible for scenes featuring shia and Noah, Very good for scenes featuring Lucas, and decent to good for scenes featuring noah and the girl), Great Story, Great Direction, Brilliant displaying of emotions and chemistry between Shia and Noah, Incredible Cinematography, Character Development was not well displayed (Even though it was present) because of the short runtime, Great to Incredible Editing, Very short runtime makes final 1/4 and the ending very rushed and unable to come full circle even though it tries to."
release_year: 2019
review_date: "07/06/2020"
redux: false
