title: "Hood Witch"
rating: 5.9
review: "Overall, a decent french movie that is executed well on a macroscale with its cinematography and direction, but the conflict and writing is a little too convoluted with how fast the movie goes. Saw the North American Premiere at SXSW."
release_year: 2023
review_date: "03/16/2024"
redux: false
id: 434
imdb_id: "tt27797160"
