title: "Horrible Bosses"
rating: 5.9
review {
  direction {
    director {
      name: "Seth Gordon"
    }
    rating: "Decent"
    comments: "Comedic elements were decently executed and it was pretty similar in feel to that of comedies from that timeframe"
  }
  acting {
    cast {
      rating: "Good"
      comments: "The whole ensemble cast was very experienced and each played to their strengths very well (like Kevin Spacey, Jamie Foxx, and Charlie Day (Who was just playing Charlie Kelly from It\'s Always Sunny in Philadelphia))"
    }
    rating: "Good"
  }
  story {
    writer {
      name: "Michael Markowitz"
    }
    rating: "Pretty Bad"
    comments: "The actual concept of the movie as pretty interesting, it is just the plot itself was very simplistic, predictable, and unrealistic to how it favored the heros to win"
  }
  screenplay {
    writer {
      name: "Michael Markowitz"
    }
    writer {
      name: "John Francis Daley"
    }
    writer {
      name: "Jonathan Goldstein"
    }
    rating: "Decent"
    comments: "A movie with funny/enjoyable moments but is overall very simplistic and has bland dialogue"
  }
  plot_structure: "Plot Structure was too predictable and simple"
  pacing: "Pacing was good as it kept a consistent pace for the most part (Nothing to really add or cut)"
  climax: "Build to climax was very typical of movies from this time; climax was very dumb in how it tried to make the heros win (something that is very typical of movies from this era)"
  tone: "Tone was very similar to other comedies from the time"
  final_notes: ""
  overall: "Overall, an enjoyable movie with funny performances from the experienced cast, but is overall very simple and bland in terms of writing"
}
release_year: 2011
review_date: "07/25/2022"
redux: false
id: 282
imdb_id: "tt1499658"
