title: "Hustlers"
rating: 8.0
review: "Acting by Jennifer Lopez and Constance Wu was very good, Story was good but ending was kinda meh and very rushed, pacing was not very consistent, Very enjoyable and entertaining movie."
release_year: 2019
review_date: "12/22/2019"
redux: false
