title: "Inception "
rating: 9.7
review: "This movie is perfect except for the fast pacing in the beginning, the idea of limbo and security, and what equates to a Kick."
release_year: 2010
review_date: "08/15/2017"
redux: false
