title: "Indiana Jones and the Dial of Destiny"
rating: 6.8
review {
  direction {
    director {
      name: "James Mangold"
    }
    rating: "Pretty Good"
    comments: "Does a good on the macro-scale as the big chase scenes and adventure sequences are very Indiana Jones-esque, but the more interpersonal scenes do miss the mark at times (especially some of the scenes between Ford and Waller-Bridge)"
  }
  acting {
    performance {
      actor {
        name: "Harrison Ford"
      }
      rating: "Pretty Good to Good"
      comments: "Pulls a lot from experience as you can tell there are moments were he really does enjoy being Indiana Jones but there are many others where it feels like he is checked out and only doing this for the paycheck"
    }
    performance {
      actor {
        name: "Phoebe Waller-Bridge"
      }
      rating: "Decent to Pretty Good"
      comments: "A lot of her quirk and charm that she is known for was very hit or miss at moments (but I cannot say I did not like it as a whole); though, her chemistry with Ford was very lacking throughout the movie and kinda brought the movie down a bit"
    }
    performance {
      actor {
        name: "Mads Mikkelsen"
      }
      rating: "Good to Very Good"
      comments: "It was as if the role was written for him as he uses his signature villian charm to create a very menacing Indiana Jones villian"
    }
    cast {
      rating: "Decent"
      comments: "It really was on a spectrum as some actors were pretty good and did a good job but some missed the mark by a lot"
    }
    rating: "Decent to Pretty Good"
  }
  story {
    writer {
      name: "Jez Butterworth"
    }
    writer {
      name: "John-Henry Butterworth"
    }
    writer {
      name: "David Koepp"
    }
    writer {
      name: "James Mangold"
    }
    rating: "Decent"
    comments: "The overarching story as a whole was fine as it follows the pretty standard Indiana Jones template (with homages to the previous films), but the ending was very bad to where it felt that neither the movie nor the trilogy was closed off well"
  }
  screenplay {
    writer {
      name: "Jez Butterworth"
    }
    writer {
      name: "John-Henry Butterworth"
    }
    writer {
      name: "David Koepp"
    }
    writer {
      name: "James Mangold"
    }
    rating: "Decent to Pretty Good"
    comments: "The dialogue was fine (but did not feel like it had the typical Indiana Jones charm), the humor was decent (with some jokes hitting but others missing), the symbolism was pretty prevelant but pretty surface level in its meaning, the foreshadowing was more predictable then subverting expectations (as if they were trying to make it as more open-ending than closing the story)"
  }
  score {
    composer {
      name: "John Williams"
    }
    rating: "Very Good to Great"
    comments: "The only element of the movie that has the original Indiana Jones charm as it is used very well throughout the movie"
  }
  cinematography {
    cinematographer {
      name: "Phedon Papamichael"
    }
    rating: "Very Good"
    comments: "Especially in the action sequences"
  }
  editing {
    editor {
      name: "Michael McCusker"
    }
    editor {
      name: "Andrew Buckland"
    }
    editor {
      name: "Dirk Westervelt"
    }
    rating: "Good"
  }
  sound {
    rating: "Decent to Pretty Good"
    comments: "Very Good in the action sequences but it felt like the mixing of dialogue was Pretty Bad as it was hard to hear the cast sometimes"
  }
  visual_effects {
    rating: "Pretty Bad to Decent"
    comments: "It was very evident when they were using CGI as none of it felt really embedded into the movie; the Deep-fake scenes were really in the uncanny valley"
  }
  production_design {
    rating: "Good"
  }
  costumes {
    rating: "Good"
    comments: "Really helped pay homage to the original Indiana Jones costume"
  }
  plot_structure: "Plot Structure was fine as it was very formulaic and that of other Indiana Jones movies; the climax was very short though and could have used like 10-15 more minutes (especially in the second half of the climax)"
  pacing: "Pacing was fine for the most part (not too fast or slow)"
  climax: "Climax was the worst part of the movie as the first half was fine but the second half was very stupid and not necessary at all (with it dealing with topics/motifs that really playing to more current trends)"
  tone: "Tone was similiar to that of other Indiana Jones movies (but felt pretty off as it tried to be more humorous than it needed to be)"
  final_notes: ""
  overall: "Overall, a pretty lackluster sendoff for one of the best characters/franchises in cinema history as many moments are entertaining to see (like the action sequences and Harrison Ford being Indiana Jones), but the lack of chemistry between the two leads and the very bad ending do not do Indiana Jones justice in what is his final ride"
}
release_year: 2023
review_date: "06/28/2023"
redux: false
id: 353
imdb_id: "tt1462764"
