title: "Indiana Jones and the Raiders of the Lost Ark"
rating: 9.6
review: "Great Acting, Brilliant Story, Great Screenplay, Great Score, Extremely Iconic, Indy\'s girl did not act that well."
release_year: 1981
review_date: "05/22/2019"
redux: false
id: 94
imdb_id: "tt0082971"
