title: "Inglourious Basterds"
rating: 9.3
review: "Incredible acting by Laurent and Waltz, ok acting by rest of the cast, Incredible Screenplay, Incredible Story, Great violence, great music, hard to keep track some of the storylines that all happened at once. "
release_year: 2009
review_date: "05/21/2017"
redux: false
