title: "Inside Out"
rating: 0.1
review {
  direction {
    director {
      name: "Pete Docter"
    }
    rating: "TODO"
    comments: "macroscale is; microscale is; direction of actors is; storytelling is; tension is"
  }
  acting {
    performance {
      actor {
        name: "Amy Poehler"
      }
      rating: "TODO"
      comments: "TODO"
    }
    performance {
      actor {
        name: "Phyllis Smith"
      }
      rating: "TODO"
      comments: "TODO"
    }
    performance {
      actor {
        name: "Richard Kind"
      }
      rating: "TODO"
      comments: "TODO"
    }
    performance {
      actor {
        name: "Bill Hader"
      }
      rating: "TODO"
      comments: "TODO"
    }
    performance {
      actor {
        name: "Lewis Black"
      }
      rating: "TODO"
      comments: "TODO"
    }
    performance {
      actor {
        name: "Mindy Kaling"
      }
      rating: "TODO"
      comments: "TODO"
    }
    performance {
      actor {
        name: "Kaitlyn Dias"
      }
      rating: "TODO"
      comments: "TODO"
    }
    performance {
      actor {
        name: "Diane Lane"
      }
      rating: "TODO"
      comments: "TODO"
    }
    performance {
      actor {
        name: "Kyle MacLachlan"
      }
      rating: "TODO"
      comments: "TODO"
    }
    cast {
      rating: "TODO"
      comments: "TODO"
    }
    rating: ""
  }
  story {
    writer {
      name: "Pete Docter"
    }
    writer {
      name: "Ronnie del Carmen"
    }
    rating: "TODO"
    comments: "The concept is; the plot structure is; flow between sequences is; character writing is"
  }
  screenplay {
    writer {
      name: "Pete Docter"
    }
    writer {
      name: "Meg LeFauve"
    }
    writer {
      name: "Josh Cooley"
    }
    rating: "TODO"
    comments: "The dialogue is; the humor is; the symbolism is; the foreshadowing is"
  }
  score {
    composer {
      name: "Michael Giacchino"
    }
    rating: "TODO"
    comments: "TODO"
  }
  cinematography {
    cinematographer {
      name: "Patrick Lin (camera)"
    }
    cinematographer {
      name: "Kim White (lighting)"
    }
    rating: "TODO"
    comments: "TODO"
  }
  editing {
    editor {
      name: "Kevin Nolting"
    }
    rating: "TODO"
    comments: "TODO"
  }
  sound {
    rating: "TODO"
    comments: "TODO"
  }
  visual_effects {
    rating: "TODO"
    comments: "TODO"
  }
  production_design {
    rating: "TODO"
    comments: "TODO"
  }
  makeup {
    rating: "TODO"
    comments: "TODO"
  }
  costumes {
    rating: "TODO"
    comments: "TODO"
  }
  pacing: "Pacing "
  climax: "Climax "
  tone: "Tone "
  final_notes: ""
  overall: "Overall, "
}
release_year: 2015
review_date: "06/15/2024"
redux: false
id: 458
imdb_id: "tt2096673"
