title: "It"
rating: 6.4
review: "Entertaining movie, jokes were funny at times, acting was Decent, Cinematography was good, not really scary, marketing made it more a horror than comedy which is not cool, score was there, story was good, Screenplay was Decent."
release_year: 2017
review_date: "10/20/2017"
redux: false
id: 48
imdb_id: "tt1396484"
