title: "It Comes at Night"
rating: 6.0
review: "Terrible Acting besides Joel, Great Cinemagraphy, Not Scary at all, Disappointing, Score was good, Ok screenplay, ok story, Very one dimensional, Liked the concept of the ending but was not shot and executed well. "
release_year: 2017
review_date: "07/27/2018"
redux: false
