title: "It Ends with Us"
rating: 0.1
review {
  direction {
    director {
      name: "Justin Baldoni"
    }
    rating: "TODO"
    comments: "macroscale is; microscale is; direction of actors is; storytelling is; tension is"
  }
  acting {
    performance {
      actor {
        name: "Blake Lively"
      }
      rating: "TODO"
      comments: "TODO"
    }
    performance {
      actor {
        name: "Justin Baldoni"
      }
      rating: "TODO"
      comments: "TODO"
    }
    performance {
      actor {
        name: "Jenny Slate"
      }
      rating: "TODO"
      comments: "TODO"
    }
    performance {
      actor {
        name: "Hasan Minhaj"
      }
      rating: "TODO"
      comments: "TODO"
    }
    performance {
      actor {
        name: "Brandon Sklenar"
      }
      rating: "TODO"
      comments: "TODO"
    }
    cast {
      rating: "TODO"
      comments: "TODO"
    }
    rating: "TODO"
  }
  story {
    writer {
      name: "Christy Hall"
    }
    rating: "TODO"
    comments: "The concept is; the plot structure is; flow between sequences is; character writing is"
  }
  screenplay {
    writer {
      name: "Christy Hall"
    }
    rating: "TODO"
    comments: "The dialogue is; the humor is; the symbolism is; the foreshadowing is"
  }
  score {
    composer {
      name: "Rob Simonsen"
    }
    composer {
      name: "Duncan Blickenstaff"
    }
    rating: "TODO"
    comments: "TODO"
  }
  cinematography {
    cinematographer {
      name: "Barry Peterson"
    }
    rating: "TODO"
    comments: "TODO"
  }
  editing {
    editor {
      name: "Oona Flaherty"
    }
    editor {
      name: "Robb Sullivan"
    }
    rating: "TODO"
    comments: "TODO"
  }
  sound {
    rating: "TODO"
    comments: "TODO"
  }
  visual_effects {
    rating: "TODO"
    comments: "TODO"
  }
  production_design {
    rating: "TODO"
    comments: "TODO"
  }
  makeup {
    rating: "TODO"
    comments: "TODO"
  }
  costumes {
    rating: "TODO"
    comments: "TODO"
  }
  pacing: "Pacing "
  climax: "Climax "
  tone: "Tone "
  final_notes: ""
  overall: "Overall, "
}
release_year: 2024
review_date: "08/31/2024"
redux: false
id: 482
imdb_id: "tt10655524"
