title: "It\'s a Wonderful Life"
rating: 8.4
review {
  direction {
    director {
      name: "Frank Capra"
    }
    rating: "Very Good"
  }
  acting {
    performance {
      actor {
        name: "James Stewart"
      }
      rating: "Incredible"
      comments: "Especially his ability to go through different emotions throughout the movie and take command of every scene"
    }
    performance {
      actor {
        name: "Donna Reed"
      }
      rating: "Good to Very Good"
      comments: "A good companion performance to Stewart\'s"
    }
    performance {
      actor {
        name: "Lionel Barrymore"
      }
      rating: "Good to Very Good"
    }
    performance {
      actor {
        name: "Henry Travers"
      }
      rating: "Good to Very Good"
    }
    cast {
      rating: "Good"
    }
    rating: "Good to Very Good"
  }
  story {
    writer {
      name: "Frances Goodrich"
    }
    writer {
      name: "Albert Hackett"
    }
    writer {
      name: "Frank Capra"
    }
    rating: "Good to Very Good"
    comments: "While the concepts, elements, and the \'retelling\' of \'A Christmas Carol\' was very good/iconic, the movie spends too much of the story on the exposition to where the more memorable parts are barely a part of the movie"
  }
  screenplay {
    writer {
      name: "Frances Goodrich"
    }
    writer {
      name: "Albert Hackett"
    }
    writer {
      name: "Frank Capra"
    }
    rating: "Very Good"
    comments: "Helps propel some of the more intense, emotional scenes"
  }
  score {
    composer {
      name: "Dimitri Tiomkin"
    }
    rating: "Pretty Good"
  }
  cinematography {
    cinematographer {
      name: "Joseph Walker"
    }
    cinematographer {
      name: "Joseph Biroc"
    }
    rating: "Great"
  }
  editing {
    editor {
      name: "William Hornbeck"
    }
    rating: "Decent to Pretty Good"
    comments: "Especially for the time, though there were some noticeable editing jumps from poor cutting"
  }
  sound {
    rating: "Great"
  }
  visual_effects {
    rating: "Incredible"
    comments: "Especially for the time, with the animation and the snow"
  }
  plot_structure: "Plot Structure was not good (the first hour and 20 minutes is all exposition to set up the life of George Bailey, the conflict is really only presented with only 30-40 minutes left in the movie; the Christmas element of the movie is only really presented towards the last 30-40 minutes of the movie)"
  pacing: "Pacing is not great as the first 3/4 of the movie is pretty slow while the last 1/4 the pace is pretty quick to make up for the fact at how much exposition there is"
  climax: "Build to the climax ramps up the pace of the movie as the movie shifts to the part it is known for; climax is great as we get to see what George Bailey is truly missing with contemplating his life"
  final_notes: "The themes of suicide were pretty taboo at the time so it was great to see a movie like this tackle it in the 1940s; the actual christmas elements of the movie only show up in the final 40-45 minutes (so while it technically is a Christmas movie, Christmas is more of a part of this movie rather than a key element (at least for the first 3/4))"
  overall: "Overall, a good watch that stands the test of time as we get to see George Bailey find out the true importance of life and how valuable it really is in this Christmas classic, even though it falters in its plot structure taking away from its best elements"
}
release_year: 1946
review_date: "12/30/2021"
redux: false
id: 236
imdb_id: "tt0038650"
