title: "John Wick: Chapter 3 - Parabellum"
rating: 6.8
review {
  direction {
    director {
      name: "Chad Stahelski"
    }
    comments: "Decent Direction (The choreography of action sequences was very well done (Back to being on par with the first film), and there is an improvement in storytelling and the performance by the actors (showing the growth in the director this time around))"
  }
  acting {
    actor {
      name: "Keanu Reeves"
      comments: "Pretty Good from Keanu Reeves (Able to handle the action sequences in a great way and is a strong prominent figure throughout the movie (With some good moments in dramatic acting), but still has some of those questionable moments that take his performances back in the franchise (mostly due to how reserved the character is))"
    }
    actor {
      name: "Halle Berry"
      comments: "Pretty Good from Halle Berry (Holds her own well and is a prominent figure in the scenes she is in)"
    }
    actor {
      name: "Laurence Fishburne"
      comments: "Pretty Good from Laurence Fishburne (Takes up where he left off from the previous film as he is a very dynamic character that can show some range of emotion)"
    }
    cast: "Pretty Bad to Decent from the rest of the cast"
    comments: "Decent Acting"
  }
  story {
    writer {
      name: "Derek Kolstad"
    }
    comments: "Good Story (Creates a very captivating story this time around as the constant chase John Wick has to go through throughout the movie really helps build the character and show how much of an unstoppable force he is; the construction is also better this time (but still follows a lot of the same flaws the previous movies had))"
  }
  screenplay {
    writer {
      name: "Derek Kolstad"
    }
    writer {
      name: "Shay Hatten"
    }
    writer {
      name: "Chris Collins"
    }
    writer {
      name: "Marc Abrams"
    }
    comments: "Decent Screenplay (A big cleanup in the dialog this time around as it sounds a bit more natural; there is also present symbolism and foreshadowing unlike the previous films)"
  }
  score {
    composer {
      name: "Tyler Bates"
    }
    composer {
      name: "Joel J. Richard"
    }
    comments: "Decent to Pretty Good Score"
  }
  cinematography {
    cinematographer {
      name: "Dan Laustsen"
    }
    comments: "Good to Very Good Cinematography"
  }
  sound: "Good to Very Good Sound"
  editing {
    editor {
      name: "Evan Schiff"
    }
    comments: "Good Editing"
  }
  visual_effects: "Very Good Visual Effects (Really uses the visuals to help paint the picture of the story)"
  production_design: "Very Good Production Design (Felt like they used an increase budget well to help paint very exotic and futuristic scenes)"
  makeup: "Good Makeup (showed the grit and blood of the scenes very well)"
  plot_structure: "Plot Structure was laid out pretty well as there is a goal in mind with the character trying to combat it (followed by a climax)"
  pacing: "Pacing was a bit slower this time as there is a bit too many plot elements (they could\'ve cut the runtime down 10-15 minutes in order to make the movie feel a bit faster)"
  climax: "Climax was well executed as it was grand shootout between John and an army (with him really showing off what he can do in this part of the movie)"
  tone: "Tone of the movie was very dark and grungy (adds to that John Wick feel); but it still suffers from that dryness feel that the previous two movies had"
  final_notes: "The action sequences were back on par to the first movie this time around and is still well choreographed (a key reason to watch this movie)"
  overall: "Overall, an improvement in storytelling and direction in this installment of the franchise as the movie is a bit more polished than its predecessors but still keeps the level of action that makes it a memorable franchise, but it still has a ways to go in terms of writing, acting, and directing as there are still flaws"
}
release_year: 2019
review_date: "04/18/2023"
redux: false
id: 336
imdb_id: "tt6146586"
