title: "Jojo Rabbit"
rating: 9.3
review: "Extremely Funny (All the jokes hit and they hit really hard), Great Story, Great Acting by the entire cast (Especially the children, Scarlett Johansson, and Sam Rockwell), Great Screenplay, Very fun movie to watch, Great Direction, There were scenes that were cut towards the end that really created gaps in the story, Very well made movie, A mix of Borat and Life is Beautiful."
release_year: 2019
review_date: "01/21/2020"
redux: false
