title: "Joker"
rating: 9.6
review: "Brilliant Acting, Brilliant Score (Especially how it works with the story and scenes), Incredible Story, Incredible twists, Good direction and Art Design, Great Screenplay, Some scenes were not shot very well and can be seen that they are just Arthur\'s imagination."
release_year: 2019
review_date: "10/27/2019"
redux: false
