title: "Juno"
rating: 7.2
review {
  direction {
    director {
      name: "Jason Reitman"
    }
    rating: "Pretty Good"
    comments: "Did a fine job in moving the story forward, and the cut of the movie was fine, but nothing was really spectacle with the acting between the cast or showing the symbolism"
  }
  acting {
    performance {
      actor {
        name: "Elliot Page"
      }
      rating: "Pretty Good to Good"
      comments: "Showed Good moments, but for the most part played the pretentious teenager who is filled with angst and overly blurts 00s slang"
    }
    performance {
      actor {
        name: "Michael Cera"
      }
      rating: "Pretty Good"
      comments: "Just played the Michael Cera character"
    }
    performance {
      actor {
        name: "Jennifer Garner"
      }
      rating: "Decent to Pretty Good"
    }
    performance {
      actor {
        name: "Jason Bateman"
      }
      rating: "Decent to Pretty Good"
    }
    performance {
      actor {
        name: "Allison Janney"
      }
      rating: "Decent to Pretty Good"
    }
    performance {
      actor {
        name: "J. K. Simmons"
      }
      rating: "Pretty Good"
    }
    cast {
      rating: "Decent"
    }
    rating: "Pretty Good"
  }
  story {
    writer {
      name: "Diablo Cody"
    }
    rating: "Decent to Pretty Good"
    comments: "The generic coming of age story about an angsty girl, with the backdrop of the teenage pregnancy"
  }
  screenplay {
    writer {
      name: "Diablo Cody"
    }
    rating: "Decent"
    comments: "Some of the jokes were decently funny, but there was an exaggeration of how teens talked in the 00s (especially with them cramming in way too much of the slang; also, the angsty parts were annoying to watch)"
  }
  score {
    composer {
      name: "Mateo Messina"
    }
    rating: "Pretty Good"
  }
  soundtrack {
    rating: "Pretty Good"
  }
  cinematography {
    cinematographer {
      name: "Eric Steelberg"
    }
    rating: "Decent"
  }
  plot_structure: "Plot Structure was clear and clean as segment of the story was effectively shown"
  pacing: "Pacing was good as the short runtime was effectively used to convey everything that was needed to be said (there was no need to add more time)"
  climax: "The build to the climax was pretty good with the actual climax really showing the true nature of all the characters"
  final_notes: ""
  overall: "Overall, a decent to pretty good movie that was a generic coming-of-age story that was masked with the backdrop of the teenage pregnancy and annoying, angsty moments"
}
release_year: 2007
review_date: "12/01/2021"
redux: false
id: 232
imdb_id: "tt0467406"
