title: "Jurassic Park"
rating: 9.5
review: "Great Direction, Great Acting by the entire cast, Incredible Story, Great Screenplay, Incredible/Iconic Score, Jokes are funny and hit (Very few misses), Incredible Production Design, Incredible Sound Editing/Mixing (Especially with the dinosaurs), Incredible Visual Effects for the time, Good Cinematography, Great Pacing, Great Characters and character development, One of the best Blockbuster Films of all time and iconic to setting up a great franchise with great characters, Spielberg had himself a year in 1993 (Released Schindler's List the same year)."
release_year: 1993
review_date: "08/04/2020"
redux: false
