title: "Kind of Kindness"
rating: 0.1
review {
  direction {
    director {
      name: "Yorgos Lanthimos"
    }
    rating: "TODO"
    comments: "macroscale is; microscale is; direction of actors is; storytelling is; tension is"
  }
  acting {
    performance {
      actor {
        name: "Emma Stone"
      }
      rating: "TODO"
      comments: "TODO"
    }
    performance {
      actor {
        name: "Jesse Plemons"
      }
      rating: "TODO"
      comments: "TODO"
    }
    performance {
      actor {
        name: "Willem Dafoe"
      }
      rating: "TODO"
      comments: "TODO"
    }
    performance {
      actor {
        name: "Margaret Qualley"
      }
      rating: "TODO"
      comments: "TODO"
    }
    performance {
      actor {
        name: "Hong Chau"
      }
      rating: "TODO"
      comments: "TODO"
    }
    performance {
      actor {
        name: "Joe Alwyn"
      }
      rating: "TODO"
      comments: "TODO"
    }
    performance {
      actor {
        name: "Mamoudou Athie"
      }
      rating: "TODO"
      comments: "TODO"
    }
    performance {
      actor {
        name: "Hunter Schafer"
      }
      rating: "TODO"
      comments: "TODO"
    }
    cast {
      rating: "TODO"
      comments: "TODO"
    }
    rating: ""
  }
  story {
    writer {
      name: "Yorgos Lanthimos"
    }
    writer {
      name: "Efthimis Filippou"
    }
    rating: "TODO"
    comments: "The concept is; the plot structure is; flow between sequences is; character writing is"
  }
  screenplay {
    writer {
      name: "Yorgos Lanthimos"
    }
    writer {
      name: "Efthimis Filippou"
    }
    rating: "TODO"
    comments: "The dialogue is; the humor is; the symbolism is; the foreshadowing is"
  }
  score {
    composer {
      name: "Jerskin Fendrix"
    }
    rating: "TODO"
    comments: "TODO"
  }
  cinematography {
    cinematographer {
      name: "Robbie Ryan"
    }
    rating: "TODO"
    comments: "TODO"
  }
  editing {
    editor {
      name: "Yorgos Mavropsaridis"
    }
    rating: "TODO"
    comments: "TODO"
  }
  sound {
    rating: "TODO"
    comments: "TODO"
  }
  visual_effects {
    rating: "TODO"
    comments: "TODO"
  }
  production_design {
    rating: "TODO"
    comments: "TODO"
  }
  makeup {
    rating: "TODO"
    comments: "TODO"
  }
  costumes {
    rating: "TODO"
    comments: "TODO"
  }
  pacing: "Pacing "
  climax: "Climax "
  tone: "Tone "
  final_notes: ""
  overall: "Overall, "
}
release_year: 2024
review_date: "06/26/2024"
redux: false
id: 464
imdb_id: "tt22408160"



Feels like they rushed production

Direciton on a macroscale was good (Yorgos + Kubrick)

Direciton on a microscale was bad, a lot of the line delivery was monotonous and bad and it felt like they were acting in silohs

Cheep production design (Movie budget was 15 mil)

Stories were bloated and dragged, could have been cut 15-20 minutes minutes each and it would have been the same movie. Or at least give exposition if you wanted to make a more complete short story (but not having any is a stylistic choice itsefl)