title: "Kneecap"
rating: 0.1
review {
  direction {
    director {
      name: "Rich Peppiatt"
    }
    rating: "TODO"
    comments: "macroscale is; microscale is; direction of actors is; storytelling is; tension is"
  }
  acting {
    performance {
      actor {
        name: "Naoise \303\223 Caireall\303\241in"
      }
      rating: "TODO"
      comments: "TODO"
    }
    performance {
      actor {
        name: "Liam \303\223g \303\223 Hannaidh"
      }
      rating: "TODO"
      comments: "TODO"
    }
    performance {
      actor {
        name: "JJ \303\223 Dochartaigh"
      }
      rating: "TODO"
      comments: "TODO"
    }
    performance {
      actor {
        name: "Josie Walker"
      }
      rating: "TODO"
      comments: "TODO"
    }
    performance {
      actor {
        name: "Fionnuala Flaherty"
      }
      rating: "TODO"
      comments: "TODO"
    }
    performance {
      actor {
        name: "Jessica Reynolds"
      }
      rating: "TODO"
      comments: "TODO"
    }
    performance {
      actor {
        name: "Adam Best"
      }
      rating: "TODO"
      comments: "TODO"
    }
    performance {
      actor {
        name: "Simone Kirby"
      }
      rating: "TODO"
      comments: "TODO"
    }
    performance {
      actor {
        name: "Michael Fassbender"
      }
      rating: "TODO"
      comments: "TODO"
    }
    cast {
      rating: "TODO"
      comments: "TODO"
    }
    rating: "TODO"
  }
  story {
    writer {
      name: "Rich Peppiatt"
    }
    writer {
      name: "Liam \303\223g \303\223 hAnnaidh"
    }
    writer {
      name: "Naoise \303\223 Caireall\303\241in"
    }
    writer {
      name: "JJ \303\223 Dochartaigh"
    }
    rating: "TODO"
    comments: "The concept is; the plot structure is; flow between sequences is; character writing is"
  }
  screenplay {
    writer {
      name: "Rich Peppiatt"
    }
    rating: "TODO"
    comments: "The dialogue is; the humor is; the symbolism is; the foreshadowing is"
  }
  score {
    composer {
      name: "Michael \"Mikey J\" Asante"
    }
    rating: "TODO"
    comments: "TODO"
  }
  cinematography {
    cinematographer {
      name: "Ryan Kernaghan"
    }
    rating: "TODO"
    comments: "TODO"
  }
  editing {
    editor {
      name: "Julian Ulrichs"
    }
    editor {
      name: "Chris Gill"
    }
    rating: "TODO"
    comments: "TODO"
  }
  sound {
    rating: "TODO"
    comments: "TODO"
  }
  visual_effects {
    rating: "TODO"
    comments: "TODO"
  }
  production_design {
    rating: "TODO"
    comments: "TODO"
  }
  makeup {
    rating: "TODO"
    comments: "TODO"
  }
  costumes {
    rating: "TODO"
    comments: "TODO"
  }
  pacing: "Pacing "
  climax: "Climax "
  tone: "Tone "
  final_notes: ""
  overall: "Overall, "
}
release_year: 2024
review_date: "12/17/2024"
redux: false
id: 517
imdb_id: "tt27367464"
