title: "Knives Out"
rating: 8.9
review: "Great Screenplay, Very good modern interpretation of a who done it, Great acting by entire cast, Some very stupid decisions that were easily avoided, Good direction, Great Ending with a lot of twists (Though some of the explanation was kind done), pacing was good."
release_year: 2019
review_date: "01/17/2020"
redux: false
