title: "La La Land"
rating: 9.6
review: "Incredible acting by both actors, Great chemistry, Incredible music, Incredible Story, Incredible Screenplay, Movie comes around full circle, Unpredictable ending, Ryan cannot sing, some points are kinda pointless"
release_year: 2016
review_date: "01/10/2017"
redux: false
