title: "Lady Bird"
rating: 5.0
review: "Very boring movie, not good acting except for the mother, not good screenplay, OK story, Very pretencious and annoying, the final 20 mins of the movie is enjoyable though"
release_year: 2017
review_date: "03/04/2018"
redux: false
