title: "Leaving Las Vegas"
rating: 4.9
review {
  direction {
    director {
      name: "Mike Figgis"
    }
    comments: "Decent Direction"
  }
  acting {
    actor {
      name: "Nicolas Cage"
      comments: "Very Good to Great from Nicolas Cage (In a Nic Cage Way; the most Nic Cage performance I have ever seen)"
    }
    actor {
      name: "Elisabeth Shue"
      comments: "Good from Elisabeth Shue (Dull in terms of execution of dialogue but very good in terms of actions and gestures)"
    }
    cast: "Bad from the rest of the cast"
    comments: "Pretty Bad Acting"
  }
  story {
    writer {
      name: "Mike Figgis"
    }
    comments: "Pretty Good Story (I like the way it flows and how the story is told from the perspective of the end)"
  }
  screenplay {
    writer {
      name: "Mike Figgis"
    }
    comments: "Pretty Bad Screenplay (The dialogue was very poorly written but the actual actions the characters take were good; no major symbolism)"
  }
  score {
    composer {
      name: "Anthony Marinelli"
    }
    composer {
      name: "Mike Figgis"
    }
    comments: "Score/Songs were very Vegas-esque with this jazzy sound and not necessarily bad but were just way extremely overbearing in the film and took away from the story"
  }
  cinematography {
    cinematographer {
      name: "Declan Quinn"
    }
    comments: "Decent Cinematography (especially for it being super low budge)"
  }
  sound: "Terrible Sound (I did not like how overbearing the score/music was in the story and how it made it incredibly hard to hear the dialogue at times)"
  editing {
    editor {
      name: "John Smith"
    }
    comments: "Good Editing (I liked some of the metaphors it placed with the different cuts)"
  }
  pacing: "Pacing was very bad and incredibly slow (the first 10-20 minutes of the movie were meant to be the prologue but was just way to long and slow in terms of developing the story and characters); the runtime was at just under 2 hours but definitely could have cut the movie by like 30 minutes to make the movie have a better pace and remove a lot of unnecessary scenes"
  climax: "The build to the climax was like not really there but kinda there (not executed that well overall)"
  final_notes: "The relationship that the two leads have is decent and not bad but like its too formulaic and safe; Nic Cage's character is a decent character but was just way too Nic Cage in terms of its mannerisms and acting (you will know when you see it) but the portrayal of an suicidal alcoholic was not that bad; the movie was completely formulaic overall (Scene of dialogue and action -> Overbearing Jazz score that pans to the either Vegas of the characters -> Songs with the same panning -> Fades to black to the next sequence)"
  overall: "Overall, a bad movie as its only saving grace is to see the performance that won Nic Cage an Oscar (In the most Nic Cage way he could do it) and nothing else because the entire movie would have been awful if it was not for him as this low budget film really could not have been saved by the material (which was not that great to begin with)"
}
release_year: 1995
review_date: "07/25/2021"
redux: false
