title: "Legally Blonde"
rating: 5.5
review: "A watchable movie. The pacing was incredibly off. Huge skips in time that do not fit the structure. Kinda funny, decent concept, Ending was alright, not good screenplay or direction, ok acting"
release_year: 2001
review_date: "03/16/2019"
redux: false
