title: "Little Miss Sunshine"
rating: 8.7
review: "Incredible Acting by the entire cast, Great screenplay, Great story, good score, great pacing, good direction, besides acting the movie does not go above and beyond in anyway and would be a great family movie if it was not rated R"
release_year: 2006
review_date: "03/16/2019"
redux: false
