title: "Little Women"
rating: 5.9
review: "Extremely Boring, Acting was good (Florence was best, Emma Watson did not know what accent she wanted to use for the film), score was good, screenplay was decent, Story was very boring and this movie was just not meant for me."
release_year: 2019
review_date: "05/29/2020"
redux: false
id: 131
imdb_id: "tt3281548"
