title: "Logan"
rating: 8.8
review: "Very Good Acting, Great Action, some parts were unnecessary, great how everyone dies, Decent Score, great story."
release_year: 2017
review_date: "04/17/2017"
redux: false
