title: "Logan Lucky "
rating: 7.3
review: "Entertaining, ok acting, good story but clich\303\251, ok screenplay, sorta funny, some points were meh "
release_year: 2017
review_date: "09/18/2017"
redux: false
