title: "Lost in Translation"
rating: 5.9
review {
  direction {
    director {
      name: "Sofia Coppola"
    }
    rating: "Decent"
    comments: "With its best moments being the conversations between Scarjo and Murray"
  }
  acting {
    performance {
      actor {
        name: "Bill Murray"
      }
      rating: "Very Good"
    }
    performance {
      actor {
        name: "Scarlett Johansson"
      }
      rating: "Good to Very Good"
    }
    cast {
      rating: "Decent"
      comments: "There really wasn\'t a supporting cast for the movie"
    }
    rating: "Good to Very Good"
  }
  story {
    writer {
      name: "Sofia Coppola"
    }
    rating: "Pretty Bad to Decent"
    comments: "The story was a decent concept but really nothing happens in this movie"
  }
  screenplay {
    writer {
      name: "Sofia Coppola"
    }
    rating: "Pretty Bad to Decent"
    comments: "The screenplay was meant to be awkward and being \'lost in translation\' and it did capture that well, but I also felt that it made the movie very boring and dull because of it"
  }
  cinematography {
    cinematographer {
      name: "Lance Acord"
    }
    rating: "Good"
    comments: "For the equipment and budget they had (But could be a bit off at times)"
  }
  pacing: "Pacing was constant and slow so nothing to complain"
  final_notes: "The entire movie was basically just panning shots mixed with close ups of the actors faces plus improv dialogue in conversations; The symbolism and capturing the loneliness of being in a foreign country and finding love when you already have it was not as well captured as people say it is for this movie because I definitely feel that it was not displayed well enough (even if it was subtle)"
  overall: "Overall, a movie that is pretty overrated as the movie is basically just shots of Japan that is mixed with good dialogue and scenes between Bill Murray and Scarjo, but in the end falters from its lack of story and very dull presentation (as it fails to capture to true aspects of loneliness)"
}
release_year: 2003
review_date: "05/24/2021"
redux: false
id: 189
imdb_id: "tt0335266"
