title: "Manchester by the Sea"
rating: 8.9
review: "Very good Acting, Incredible Character development, Incredible Writing, A little Slow at times, Great ending, Decent Score"
release_year: 2016
review_date: "02/19/2017"
redux: false
