title: "Marriage Story"
rating: 9.1
review: "Incredible Acting by Driver and Johannson, Great Acting by supporting cast, Great Screenplay, Great Story, Good score, Good Pacing and plot, Good Cinematography, Well Made Movie overall, Extremely Over-the-top and noticeable it is Oscar Bait."
release_year: 2019
review_date: "12/24/2019"
redux: false
id: 119
imdb_id: "tt7653254"
