title: "Maxxxine"
rating: 0.1
review {
  direction {
    director {
      name: "Ti West"
    }
    rating: "TODO"
    comments: "The direction on a macroscale is decent as they show the dicotomy of 1980s LA with the glamour of Hollywood and the Fear of the Nightstalker, but he does a bad job with a bigger budget and the more responsiblities that come with it; the direction on a microscale is bad as a lot of the performances feel phoned in and the interpersonal scenes do not feel like they move the story at all; the storytelling is not good as it does not feel like the movie is moving towards anything, and this is only further supported in the climax; they build tension decently well through the visions, but not as good as the first two movies"
  }
  acting {
    performance {
      actor {
        name: "Mia Goth"
      }
      rating: "Pretty Good"
      comments: "Uses her experience in the franchise to help portray the chracter, but her performace feels more phoned in this time around as I didn't believe her internal conflict"
    }
    performance {
      actor {
        name: "Elizabeth Debicki"
      }
      rating: "Decent"
      comments: "Plays a stubborn character that is very neautral to Goth"
    }
    performance {
      actor {
        name: "Moses Sumney"
      }
      rating: "Decent"
      comments: "Does a decent job supporting Goth in their scenes"
    }
    performance {
      actor {
        name: "Michelle Monaghan"
      }
      rating: "Pretty Bad"
      comments: "Feels like there is no effort put into this performance and really falls apart in the climax"
    }
    performance {
      actor {
        name: "Bobby Cannavale"
      }
      rating: "Pretty Bad"
      comments: "So over the top and bad that its more laughable than believable"
    }
    performance {
      actor {
        name: "Halsey"
      }
      rating: "Bad"
      comments: "She has like two lines in the movie, and in those two lines, she has bad line delivery"
    }
    performance {
      actor {
        name: "Lily Collins"
      }
      rating: "Very Bad"
      comments: "She's in the movie for like one scene, and in that one scene she keeps on switching between an English and Irish accent mid-sentence"
    }
    performance {
      actor {
        name: "Giancarlo Esposito"
      }
      rating: "Pretty Bad"
      comments: "Feels very forced and does not have good chemistry with Goth"
    }
    performance {
      actor {
        name: "Kevin Bacon"
      }
      rating: "Bad"
      comments: "Feels incredibly forced with his bad accent and does not do a good job in his scenes with Goth"
    }
    cast {
      rating: "Bad"
      comments: "There are so many minor characters that just has poor line delievery and do a bad job supporting the main cast"
    }
    rating: "Bad to Pretty Bad"
  }
  story {
    writer {
      name: "Ti West"
    }
    rating: "Bad"
    comments: "The concept is not interesting as it does a bad job showing how the external conflict is effecting Maxine; Maxine's internal conflict is fine, but it feels like it doesn't build from her last film; the plot structure is poorly managed, especially in the final 40 minutes; the character writing is not good becasue it does a bad job providing any depth to Maxine, but it does a decent job showing the trauma she experienced from the last movie"
  }
  screenplay {
    writer {
      name: "Ti West"
    }
    rating: "TODO"
    comments: "The dialogue is corny and unnatural that its geninuely laughable how it made it into the movie; the symbolism is somewhat prevelant as it movie deals with struggling artists in Hollywood and how trauma effects an individual; the foreshadowing is somewhat prevelant"
  }
  score {
    composer {
      name: "Tyler Bates"
    }
    rating: "Decent to Pretty Good"
    comments: "Helps set the 1980s tone"
  }
  soundtrack {
    rating: "Pretty Good"
    comments: "Helps set the 1980s tone"
  }
  cinematography {
    cinematographer {
      name: "Eliot Rockett"
    }
    rating: "Good"
    comments: "Helped with building the world and creating suspense"
  }
  editing {
    editor {
      name: "Ti West"
    }
    rating: "Good"
    comments: "Helped with building the world and creating suspense"
  }
  sound {
    rating: "Pretty Good"
    comments: "Help with creating suspense and tension"
  }
  visual_effects {
    rating: "Pretty Bad"
    comments: "Somehow the kills feel cheaper this time around despite a bigger budget"
  }
  production_design {
    rating: "Good"
    comments: "They did a good job showing the glitz and glamour of 1980s Hollywood and did a good job incorprating the Warner Bros lot"
  }
  pacing: "Pacing faulters from the plot being very mismanaged"
  climax: "Climax is poorly executed as it feels like it is completely disjoint from the rest of the movie (and there are some moments that are just so funny at how they even got inclueded); the movie should have just ended at the climax because the exposition was actually pointless"
  tone: "Tone is very 1980s mixed with slasher elemetns"
  final_notes: "This is a strong step back from the previous two movies as this movie feels more like a spirtual successor rather than a sequel to '\X\'; the biggest issue from this movie is conflict as it geninuely ruins how the rest of the movie turns out; all these issues stem from the fact that it has an increased budget and that removed the charm these movies had"
  overall: "Overall, a substantial step back from the previous two movies in the \'X\' trilogy as all of its issues stem from that fact that an increased budget made this movie lose its charm"
}
release_year: 2024
review_date: "07/07/2024"
redux: false
id: 467
imdb_id: "tt22048412"
