title: "Memento"
rating: 9.4
review: "Great Direction, Brilliant Story, Brilliant Screenplay (Both in dialogue and how pieces are laid out through different scenes coming together), Good Acting by the entire cast, Decent Score, Great Editing, Great Pacing, I usually hate narration but this is the best I have seen it used, Ending climax and twist is incredible, Reverse Narrative style is iconic and done incredibly, the best major debut film by a director (A little biased though)."
release_year: 2000
review_date: "08/05/2020"
redux: false
