title: "Mickey 17"
rating: 0.1
review {
  direction {
    director {
      name: "Bong Joon-ho"
    }
    rating: "TODO"
    comments: "macroscale is; microscale is; storytelling is; tension is"
  }
  acting {
    performance {
      actor {
        name: "Robert Pattinson"
      }
      rating: "TODO"
      comments: "TODO"
    }
    performance {
      actor {
        name: "Naomi Ackie"
      }
      rating: "TODO"
      comments: "TODO"
    }
    performance {
      actor {
        name: "Steven Yeun"
      }
      rating: "TODO"
      comments: "TODO"
    }
    performance {
      actor {
        name: "Toni Collette"
      }
      rating: "TODO"
      comments: "TODO"
    }
    performance {
      actor {
        name: "Mark Ruffalo"
      }
      rating: "TODO"
      comments: "TODO"
    }
    cast {
      rating: "TODO"
      comments: "TODO"
    }
    rating: "TODO"
  }
  story {
    writer {
      name: "Bong Joon-ho"
    }
    rating: "TODO"
    comments: "The concept is; the plot structure is; character writing is"
  }
  screenplay {
    writer {
      name: "Bong Joon-ho"
    }
    rating: "TODO"
    comments: "The dialogue is; the humor is; the symbolism is; the foreshadowing is"
  }
  score {
    composer {
      name: "Jung Jae-il"
    }
    rating: "TODO"
    comments: "TODO"
  }
  soundtrack {
    rating: "TODO"
    comments: "TODO"
  }
  cinematography {
    cinematographer {
      name: "Darius Khondji"
    }
    rating: "TODO"
    comments: "TODO"
  }
  editing {
    editor {
      name: "Yang Jin-mo"
    }
    rating: "TODO"
    comments: "TODO"
  }
  sound {
    rating: "TODO"
    comments: "TODO"
  }
  visual_effects {
    rating: "TODO"
    comments: "TODO"
  }
  production_design {
    rating: "TODO"
    comments: "TODO"
  }
  makeup {
    rating: "TODO"
    comments: "TODO"
  }
  costumes {
    rating: "TODO"
    comments: "TODO"
  }
  pacing: "Pacing "
  climax: "Climax "
  tone: "Tone "
  final_notes: ""
  overall: "Overall, "
}
release_year: 2025
review_date: "03/06/2025"
redux: false
id: 542
imdb_id: "tt12299608"

- Bad character writing
  - Made such a composite dicator chacter that they forgot to give him any unique personality
- The dialogue was bad
- The symbolism was way too overt
- There are definitely scenes and shots that remind you that this is from an Auter like Bong Joon-Ho, but it is more on a macroscale and not on a microscale
- I have not seen his other English Language projects, but I always see this problem when non-native speakers write dialogue for a language they do not understand because it is not natural