title: "Molly\'s Game"
rating: 8.5
review: "Good Direction (Great during the High intensity/Poker Sequences and decent during the emotional moments), Very Good Screenplay (Though Not a fan of the very meta moments unless that was actually how the story was told in the book), Very Good Acting, Great Story, Pacing was good but the movie was a bit long, Score was decent, Visual Effects were good when describing the poker scenes, Good Editing except towards the end with when Molly began to lose the game, Movie kinda falls apart towards the end and the wrap up seems rushed and not well made."
release_year: 2017
review_date: "06/27/2020"
redux: false
id: 142
imdb_id: "tt4209788"
