title: "Moneyball"
rating: 9.3
review {
  direction {
    director {
      name: "Bennett Miller"
    }
    rating: "Very Good to Great"
    comments: "Nothing extraordinary about the directing style but does a very good job at moving the story forward and getting the most out of the actors (Plays a lot into dramatic tropes in directing)"
  }
  acting {
    performance {
      actor {
        name: "Brad Pitt"
      }
      rating: "Great"
      comments: "A very calculated performance as he used his experience as a leading man to drive the movie forward"
    }
    performance {
      actor {
        name: "Jonah Hill"
      }
      rating: "Very Good"
      comments: "A very soft-spoken role that is a departure from his previous work, but he does a very good job in playing off of Pitt throughout the movie (especially capturing the anxious/nerdy parts of the character); the main issue with the performance is that it is very limiting (so Jonah Hill really cannot show that much off)"
    }
    performance {
      actor {
        name: "Philip Seymour Hoffman"
      }
      rating: "Good to Very Good"
      comments: "Uses experience to play this role as his character seems more like a cameo than a central figure (but he does a very good job in holding his own and building tension with Pitt)"
    }
    cast {
      rating: "Good to Very Good"
      comments: "Everyone plays their role very well as they all come together to be this island of misfit toys that can be pushed to greatness"
    }
    rating: "Very Good"
  }
  story {
    writer {
      name: "Stan Chervin"
    }
    rating: "Great"
    comments: "Story is laid out incredibly as it chooses the right elements to focus on; the main issue with the story is its factual inaccuracies as it deviates from the truth for no reason (as simple searches will show where they are making things up); Great character writing as it does a great job exploring the demons of every character and how almost everyone has something to prove"
  }
  screenplay {
    writer {
      name: "Steven Zaillian"
    }
    writer {
      name: "Aaron Sorkin"
    }
    rating: "Great to Incredible"
    comments: "The dialogue flows incredibly well and is very iconic (but there are some lines that are a bit questionable), the symbolism is incredibly profound as it helps with driving the message forward; foreshadowing was good as a biopic could be"
  }
  score {
    composer {
      name: "Mychael Danna"
    }
    rating: "Great"
    comments: "An iconic theme that is used very well throughout the movie"
  }
  cinematography {
    cinematographer {
      name: "Wally Pfister"
    }
    rating: "Great"
    comments: "The best moment is during the streak but overall captures the movie very well"
  }
  editing {
    editor {
      name: "Christopher Tellefsen"
    }
    rating: "Great"
    comments: "Really enjoyed how they used the grainy TV screen for flashbacks and how they interpolated old footage into the film"
  }
  sound {
    rating: "Very Good"
    comments: "The pop off the ball helps with portraying some symbols and elements of the movie"
  }
  costumes {
    rating: "Very Good"
  }
  plot_structure: "Plot Structure was incredible as it does a great job at setting up the different plot elements and uses the individual story elements very well to help with driving the movie forward"
  pacing: "Pacing was a bit on the slower side (but this is more from the tone); runtime is fine as every scene is used well"
  climax: "Climax was great as the movie ends how it is supposed to end as this helps with showing its meaning"
  tone: "Tone was a bit on the blander side as there is just a bit of some dead-air (though overall it can combat this with great writing and great scenes)"
  final_notes: ""
  overall: "Overall, my favorite pure sports movie as this incredible underdog story uses writing, acting, and score to help make the audience feel invested in the team\'s journey, though its tone and historical inaccuracies hold it back from being incredible"
}
release_year: 2011
review_date: "08/15/2023"
redux: true
id: 28
imdb_id: "tt1210166"
