title: "Monty Python\'s Life of Brian"
rating: 7.9
review: "Pretty Funny Movie (Some of the jokes were well thought out but some of them were pretty cheap imo but were still funny), Decent story and satire on Christianity and socialism, Funny acting by some of the characters, A movie that uses its short runtime very well as pacing is very good. Overall, a film that uses its R rating to have a lot of boundary pushing comedy, but one where the jokes are kinda cheap (Not a outright recommendation but still enjoyed watching it)."
release_year: 1979
review_date: "09/09/2020"
redux: false
