title: "Moonlight"
rating: 4.5
review: "Some acting was good some acting was OK (The best actor in the movie is only in it for like 10 mins and Harris does an ok job), Good Writing, good Artistic Vision, Great Score. No plot whatsoever. No clear character development which was the point of the movie"
release_year: 2016
review_date: "02/25/2017"
redux: false
