title: "Murder Mystery"
rating: 5.6
review: "A watchable movie, at best. Adam Sandler is you know.....Adam Sandler. Its a coherrent story. I laughed, a couple of times. "
release_year: 2019
review_date: "07/31/2019"
redux: false
