title: "Murder Mystery"
rating: 5.2
review: "A watchable movie, at best, Adam Sandler is you know.....Adam Sandler. Its a coherent story, I laughed, a couple of times."
release_year: 2019
review_date: "07/31/2019"
redux: false
id: 102
imdb_id: "tt1618434"
