title: "My Week with Marilyn"
rating: 7.8
review: "Great Acting performances by Michelle Williams and Kenneth Branagh, Good story, good screenplay, very safe movie in terms of no risks taken, very enjoyable movie overall "
release_year: 2011
review_date: "12/22/2019"
redux: false
