title: "Nickel Boys"
rating: 8.5
review {
  direction {
    director {
      name: "RaMell Ross"
    }
    rating: "Very Good"
    comments: "The direction on a macroscale is very experimental, as the movie uses non-traditional storytelling methods to help move the story forward; The direction on a microscale is very good, as the interpersonal scenes really bring the most out of these characters, as they do an amazing job at showing the trauma they experience in such a subtle, non-verbal way; The storytelling is very non-traditional and definitely makes this movie feel unique and experimental; He builds tension in an amazing way, as you feel a great sense of anxiety and fear for what the characters experience or are about to experience, and this is fundamental to the story as it keeps you engaged in their struggle as you root for them to succeed"
  }
  acting {
    performance {
      actor {
        name: "Ethan Herisse"
      }
      rating: "Pretty Good"
      comments: "He plays his character well, as you can see how shy and anxious he is because he does not belong at the school; He does a good job showing the character\'s aspirations; He has good chemistry with Wilson"
    }
    performance {
      actor {
        name: "Brandon Wilson"
      }
      rating: "Good"
      comments: "Plays the elder brother, friend character well; there are moments where he does an amazing job showing the trauma responses his character experiences; despite saying so little"
    }
    performance {
      actor {
        name: "Hamish Linklater"
      }
      rating: "Pretty Good to Good"
      comments: "He plays his role well, as you really despise him, despite never seeing him actually commit abuse onscreen"
    }
    performance {
      actor {
        name: "Fred Hechinger"
      }
      rating: "Decent to Pretty Good"
      comments: "Plays his role well;"
    }
    performance {
      actor {
        name: "Daveed Diggs"
      }
      rating: "Pretty Good"
      comments: "Shows how trauma has affected the character well"
    }
    performance {
      actor {
        name: "Aunjanue Ellis-Taylor"
      }
      rating: "Very Good"
      comments: "Plays grandmother role well, as you can tell how caring she is for her grandson and how much of a nurturing figure she is for him"
    }
    cast {
      rating: "Decent to Pretty Good"
      comments: "Everyone plays their role well and helps tell this horrific story by saying so little"
    }
    rating: "Pretty Good"
  }
  story {
    writer {
      name: "RaMell Ross"
    }
    writer {
      name: "Joslyn Barnes"
    }
    rating: "Very Good"
    comments: "The concept is very good as it brings to life a real-life story on how abusive these Southern boys\' schools were, especially for people of color; The plot structure is nonlinear, and this supports the experimental style of the movie; Character writing is good as the dynamic between the two leads makes this movie interesting, as you really care for the characters and want them to succeed, and you get very personally hurt when something happens to them"
  }
  screenplay {
    writer {
      name: "RaMell Ross"
    }
    writer {
      name: "Joslyn Barnes"
    }
    rating: "Pretty Good"
    comments: "The movie is not really dialogue-heavy, as it is more action-based, visual storytelling; The humor is decent, as they do a good job lightening up the mood with jokes; The symbolism is profound, as the movie has strong messages about racism during the Civil Rights era and the effect abuse has on children; The foreshadowing is not the best, because they kind of give away the ending when they jump to the future and not in a way you expect"
  }
  score {
    composer {
      name: "Alex Somers"
    }
    composer {
      name: "Scott Alario"
    }
    rating: "Pretty Good"
    comments: "Helps with setting the tone"
  }
  cinematography {
    cinematographer {
      name: "Jomo Fray"
    }
    rating: "Great"
    comments: "Helps make this movie what it is; the decision to make this movie in the first person really brings in a new way to tell stories; we see it from the character\'s lens, as if we are actually characters in this movie"
  }
  editing {
    editor {
      name: "Nicholas Monsour"
    }
    rating: "Very Good"
    comments: "The editing is very experimental and makes this movie what it is"
  }
  sound {
    rating: "Good"
    comments: "Helps build tension"
  }
  production_design {
    rating: "Good"
    comments: "Emulates the actual Dozier School for the boys"
  }
  pacing: "Pacing is fine, as the movie\'s nonlinear, experimental style actually speeds things up when the movie starts to drag"
  climax: "The climax is good and well-executed, but I kind of knew what was going to happen because of some minor flaws they forgot to hide"
  tone: "The tone feels very coming-of-age, but also feels very experimental at the same time;"
  final_notes: "I really respect them making this movie PG-13, as it never shows the horrors on screen to sensationalize them, allowing you to do your own research afterward; they use a lot of subtlety and action rather than dialogue, which I thought was well executed"
  overall: "Overall, a very good movie that is told through a first-person, experimental style; this film does an amazing job subtly showing the trauma and abuse these characters experience as it makes you feel personally impacted by what these characters go through, making you want them to succeed"
}
release_year: 2024
review_date: "01/09/2025"
redux: false
id: 530
imdb_id: "tt23055660"
