title: "Nightbitch"
rating: 0.1
review {
  direction {
    director {
      name: "Marielle Heller"
    }
    rating: "TODO"
    comments: "macroscale is; microscale is; direction of actors is; storytelling is; tension is"
  }
  acting {
    performance {
      actor {
        name: "Amy Adams"
      }
      rating: "TODO"
      comments: "TODO"
    }
    performance {
      actor {
        name: "Scoot McNairy"
      }
      rating: "TODO"
      comments: "TODO"
    }
    performance {
      actor {
        name: "Arleigh Snowden"
      }
      rating: "TODO"
      comments: "TODO"
    }
    performance {
      actor {
        name: "Emmett Snowden"
      }
      rating: "TODO"
      comments: "TODO"
    }
    performance {
      actor {
        name: "Zo\303\253 Chao"
      }
      rating: "TODO"
      comments: "TODO"
    }
    performance {
      actor {
        name: "Mary Holland"
      }
      rating: "TODO"
      comments: "TODO"
    }
    performance {
      actor {
        name: "Ella Thomas"
      }
      rating: "TODO"
      comments: "TODO"
    }
    performance {
      actor {
        name: "Archana Rajan"
      }
      rating: "TODO"
      comments: "TODO"
    }
    performance {
      actor {
        name: "Jessica Harper"
      }
      rating: "TODO"
      comments: "TODO"
    }
    cast {
      rating: "TODO"
      comments: "TODO"
    }
    rating: "TODO"
  }
  story {
    writer {
      name: "Marielle Heller"
    }
    rating: "TODO"
    comments: "The concept is; the plot structure is; flow between sequences is; character writing is"
  }
  screenplay {
    writer {
      name: "Marielle Heller"
    }
    rating: "TODO"
    comments: "The dialogue is; the humor is; the symbolism is; the foreshadowing is"
  }
  score {
    composer {
      name: "Nate Heller"
    }
    rating: "TODO"
    comments: "TODO"
  }
  cinematography {
    cinematographer {
      name: "Brandon Trost"
    }
    rating: "TODO"
    comments: "TODO"
  }
  editing {
    editor {
      name: "Anne McCabe"
    }
    rating: "TODO"
    comments: "TODO"
  }
  sound {
    rating: "TODO"
    comments: "TODO"
  }
  visual_effects {
    rating: "TODO"
    comments: "TODO"
  }
  pacing: "Pacing "
  climax: "Climax "
  tone: "Tone "
  final_notes: ""
  overall: "Overall, "
}
release_year: 2024
review_date: "10/30/2024"
redux: false
id: 507
imdb_id: "tt12810074"

* Premeire at Austin Film Festival