title: "Office Space"
rating: 8.8
review: "Incredibly funny and relatable, Great Story, For how short the movie is it really uses its time well, Would have liked to have seen more of the relationship and more of the movie as a whole though."
release_year: 1999
review_date: "03/19/2019"
redux: false
