title: "Once Upon a Time in Hollywood"
rating: 8.7
review: "The Acting was Incredible by the Main Cast, The Production Direction was Incredible, The Cinematography was Incredible, The Direction was good, Very funny, Way too long of a movie, The movie does not have a plot, Its a wandering movie exploring the end of the Hollywood Golden Age, The ending was extremely confusing but makes sense the more you think about it."
release_year: 2019
review_date: "07/31/2019"
redux: false
id: 101
imdb_id: "tt7131622"
