title: "Paranormal Activity"
rating: 5.5
review: "Decent Acting, The first hour of the movie was extremely boring, Decent story, Decent screenplay, Plot/conflict development was terrible as it does not go into why any of the supernatural is happening even though they allude to it begin a reason for Katie, final 15 mins of the movie were pretty scary but relied too much on jump scare tactics."
release_year: 2007
review_date: "07/06/2020"
redux: false
