title: "Popstar: Never Stop Never Stopping "
rating: 5.9
review: "Entertaining movie but not that funny, Andy Samberg is really annoying, liked the documentary format and some points were funny with what they did with it, good story, would not re-watch."
release_year: 2016
review_date: "07/22/2017"
redux: false
id: 37
imdb_id: "tt3960412"
