title: "Project X"
rating: 4.9
review {
  direction {
    director {
      name: "Nima Nourizadeh"
    }
    rating: "Pretty Bad to Decent"
    comments: "While the execution of party scenes was well done, the actual direction of people and the other scenes were really hard to watch at times and very poorly executed"
  }
  acting {
    performance {
      actor {
        name: "Thomas Mann"
      }
      rating: "Bad"
      comments: "Just a very cringy performance and clearly shows inexperience"
    }
    performance {
      actor {
        name: "Oliver Cooper"
      }
      rating: "Decent"
      comments: "The best of the main characters as he tries to be the comedic relief character that the movie tries to pent up as, but kinda hits sideways a lot as his inexperience shows"
    }
    performance {
      actor {
        name: "Miles Teller"
      }
      rating: "Decent to Pretty Good"
      comments: "Actually showed some talent in this minor performance and really shows how he is capable of being a star in the future"
    }
    cast {
      rating: "Bad"
      comments: "Just showed so much inexperience and felt very cringy at times"
    }
    rating: "Bad"
  }
  story {
    writer {
      name: "Michael Bacall"
    }
    rating: "Pretty Good"
    comments: "The actual plot was very poorly structured but the different themes and ideas used went on to be very iconic and play a major role in the youth at the time"
  }
  screenplay {
    writer {
      name: "Matt Drake"
    }
    writer {
      name: "Michael Bacall"
    }
    rating: "Bad"
    comments: "The lines/jokes were stuff that middle schoolers were saying in 2012 (not high schoolers) and the other parts of the screenplay were so predictable and corny/cringy"
  }
  cinematography {
    cinematographer {
      name: "Ken Seng"
    }
    rating: "Great to Incredible"
    comments: "The cin\303\251ma v\303\251rit\303\251 style/found footage really was what stole the show as it was well done (not nauseating like other files of this style) and really made it so it felt that the audience was at the party"
  }
  editing {
    editor {
      name: "Jeff Groth"
    }
    rating: "Very Good"
    comments: "Especially during the party montages"
  }
  sound {
    rating: "Good"
  }
  visual_effects {
    rating: "Good to Very Good"
    comments: "The pyro for the movie was well done"
  }
  plot_structure: "Plot Structure was so poorly managed (the exposition and rising action is like only 20 minutes of the movie as it places way more emphasis on the party, and because of this the actual party feels like it drags for so long because it really does not build up that much)"
  pacing: "Pacing was incredibly fast as they really try to fit so much in (they should have added 30 minutes to before the party to help build it up)"
  climax: "Build to climax was poorly executed as it is a by-product of a poorly structured plot; because the movie focuses too much on the party it really cannot build up that much (though it does try); climax was decent but is kinda a mess as it is just chaos at the end of the party-goers and really does not get that much done"
  tone: "Tone was the typical high school comedy movie"
  final_notes: "Very Good to Great Score/Soundtrack (really paved the way into being the party soundtrack of the early 2010s as many of these songs are still used today for partying (really showing the impact this movie had)); the movie does have impact (given how much it was talked about and discussed by the youth when it came out and how much impact it has on parties and clubs today with the music and movie references) but it is a blatant copy of Superbad (it stars the same three characters (though they are all poorly written versions of those three) who try to become popular by having a party and end-up screwing up with the people they love as they reconcile towards the end (the only difference with this movie is that it is more about the actual party rather than the journey))"
  overall: "Overall, an impactful movie for its time that is shot very well but is so poorly written that it is really hard to watch at times, and the movie is a copy of Superbad and it really shows"
}
release_year: 2012
review_date: "06/17/2022"
redux: false
id: 265
imdb_id: "tt1636826"
