title: "Psycho"
rating: 8.8
review {
  direction {
    director {
      name: "Alfred Hitchcock"
    }
    rating: "Great"
    comments: "Was able to manage the use of different angles and scenes to help tell and move the story forward; gets a lot out of his actors"
  }
  acting {
    performance {
      actor {
        name: "Anthony Perkins"
      }
      rating: "Great"
      comments: "Does a great job in showing the anxiety and demented nature of the character"
    }
    performance {
      actor {
        name: "Vera Miles"
      }
      rating: "Good"
      comments: "Very 60s style acting"
    }
    performance {
      actor {
        name: "John Gavin"
      }
      rating: "Good"
      comments: "Very over-the-top 60s style of acting"
    }
    performance {
      actor {
        name: "Martin Balsam"
      }
      rating: "Good"
    }
    performance {
      actor {
        name: "John McIntire"
      }
      rating: "Good"
    }
    performance {
      actor {
        name: "Janet Leigh"
      }
      rating: "Very Good"
      comments: "Really holds her own and plays the female lead well, uses facial expressions and emotions to share the state of the character"
    }
    cast {
      rating: "Good"
      comments: "Very 60s"
    }
    rating: "Good to Very Good"
  }
  story {
    writer {
      name: "Joseph Stefano"
    }
    rating: "Great"
    comments: "Laid out well (though focuses a bit too much on exposition), has a lot of twists and turns to help make it a horror/mystery class, and has great character writing when it comes to the two leads (especially Norman)"
  }
  screenplay {
    writer {
      name: "Joseph Stefano"
    }
    rating: "Very Good"
    comments: "The dialogue is very fitting for the time, the humor was decent and kept it a bit light-hearted; the horror elements were very iconic and helped lay the groundwork for future slasher movies; uses allusions and symbols to help keep the audience guessing the mystery; foreshadowing was really good (especially to help lay the groundwork for the twist at the end)"
  }
  score {
    composer {
      name: "Bernard Herrmann"
    }
    rating: "Great"
    comments: "Iconic and helps with building suspense"
  }
  cinematography {
    cinematographer {
      name: "John L. Russell"
    }
    rating: "Very Good"
    comments: "Especially the use of multiple camera angles and techniques to give illusions of fear and movement; a bit dated though compared to modern technology"
  }
  editing {
    editor {
      name: "George Tomasini"
    }
    rating: "Very Good"
    comments: "Helps with transitioning between scenes and camera angles"
  }
  sound {
    rating: "Good"
    comments: "Very evident with the use of Foley effects, but helps will building suspense; good for the time"
  }
  production_design {
    rating: "Good"
    comments: "Mostly for the iconic Bates Motel"
  }
  plot_structure: "Plot Structure was good as all points were laid out; the movie spends a bit too much time on the exposition and the resolution (while iconic) was a bit convoluted for no reason"
  pacing: "Pacing was good for the most part (although there were a lot of filler shots that could be cut into a quarter of the time just to fill space (like Norman cleaning or Marion\'s sister walking up the stairs))"
  climax: "Climax was the most suspenseful and some of the best parts of the movie (and the build to the climax was also executed well)"
  tone: "Tone was more of a mystery/thriller than it was a horror movie; helped lay the groundwork for future slasher movies (but still feels limited given when it was released)"
  final_notes: "The character of Norman Bates is incredibly written as it shows the effects isolation and jealousy can have on an individual to descend into madness (with Perkins capturing this essence very well through his mannerisms and acting); the elements of horror as not necessarily the focal point of the movie as the film after the first hour is more a constant suspense rather than murders"
  overall: "Overall, a classic in the horror genre that lives up to the name as many iconic elements of the movie make Psycho a must-watch for the slasher genre (especially considering how ahead of its time it was), even though it does have a good amount of filler elements and the exposition and resolution could have been worked on a bit"
}
release_year: 1960
review_date: "10/18/2023"
redux: true
id: 224
imdb_id: "tt0054215"
