title: "Queer"
rating: 0.1
review {
  direction {
    director {
      name: "Luca Guadagnino"
    }
    rating: "TODO"
    comments: "macroscale is; microscale is; direction of actors is; storytelling is; tension is"
  }
  acting {
    performance {
      actor {
        name: "Daniel Craig"
      }
      rating: "TODO"
      comments: "TODO"
    }
    performance {
      actor {
        name: "Drew Starkey"
      }
      rating: "TODO"
      comments: "TODO"
    }
    performance {
      actor {
        name: "Jason Schwartzman"
      }
      rating: "TODO"
      comments: "TODO"
    }
    performance {
      actor {
        name: "Henrique Zaga"
      }
      rating: "TODO"
      comments: "TODO"
    }
    performance {
      actor {
        name: "Lesley Manville"
      }
      rating: "TODO"
      comments: "TODO"
    }
    cast {
      rating: "TODO"
      comments: "TODO"
    }
    rating: "TODO"
  }
  story {
    writer {
      name: "Justin Kuritzkes"
    }
    rating: "TODO"
    comments: "The concept is; the plot structure is; flow between sequences is; character writing is"
  }
  screenplay {
    writer {
      name: "Justin Kuritzkes"
    }
    rating: "TODO"
    comments: "The dialogue is; the humor is; the symbolism is; the foreshadowing is"
  }
  score {
    composer {
      name: "Trent Reznor"
    }
    composer {
      name: "Atticus Ross"
    }
    rating: "TODO"
    comments: "TODO"
  }
  cinematography {
    cinematographer {
      name: "Sayombhu Mukdeeprom"
    }
    rating: "TODO"
    comments: "TODO"
  }
  editing {
    editor {
      name: "Marco Costa"
    }
    rating: "TODO"
    comments: "TODO"
  }
  sound {
    rating: "TODO"
    comments: "TODO"
  }
  visual_effects {
    rating: "TODO"
    comments: "TODO"
  }
  production_design {
    rating: "TODO"
    comments: "TODO"
  }
  makeup {
    rating: "TODO"
    comments: "TODO"
  }
  costumes {
    rating: "TODO"
    comments: "TODO"
  }
  pacing: "Pacing "
  climax: "Climax "
  tone: "Tone "
  final_notes: ""
  overall: "Overall, "
}
release_year: 2024
review_date: "12/15/2024"
redux: false
id: 516
imdb_id: "tt24176060"

- Surrealist
- Boring
- Slow 
- Really enjoyed the visuals