title: "Raging Bull"
rating: 5.2
review: "Good acting, not good story, So many plot holes, music was OK, not relatable at all, Extremely slow, disgusting at time to watch, Screenplay was OK, why does everyone like this movie "
release_year: 1980
review_date: "06/30/2017"
redux: false
