title: "Raging Bull"
rating: 4.8
review: "Good acting, Bad story, So many plot holes, Decent Score/Soundtrack, not relatable at all, Extremely slow, disgusting at time to watch, Screenplay was OK, why does everyone like this movie."
release_year: 1980
review_date: "06/30/2017"
redux: false
id: 35
imdb_id: "tt0081398"
