title: "Ravens"
rating: 0.1
review {
  direction {
    director {
      name: "Mark Gill"
    }
    rating: "TODO"
    comments: "macroscale is; microscale is; direction of actors is; storytelling is; tension is"
  }
  acting {
    performance {
      actor {
        name: "Tadanobu Asano"
      }
      rating: "TODO"
      comments: "TODO"
    }
    performance {
      actor {
        name: "Sôsuke Ikematsu"
      }
      rating: "TODO"
      comments: "TODO"
    }
    performance {
      actor {
        name: "Kumi Takiuchi"
      }
      rating: "TODO"
      comments: "TODO"
    }
    performance {
      actor {
        name: "Kanji Furutachi"
      }
      rating: "TODO"
      comments: "TODO"
    }
    performance {
      actor {
        name: "Gô Jibiki"
      }
      rating: "TODO"
      comments: "TODO"
    }
    cast {
      rating: "TODO"
      comments: "TODO"
    }
    rating: "TODO"
  }
  story {
    writer {
      name: "Mark Gill"
    }
    rating: "TODO"
    comments: "The concept is; the plot structure is; flow between sequences is; character writing is"
  }
  screenplay {
    writer {
      name: "Mark Gill"
    }
    rating: "TODO"
    comments: "The dialogue is; the humor is; the symbolism is; the foreshadowing is"
  }
  score {
    composer {
      name: "Paul Lay"
    }
    composer {
      name: "Théophile Moussouni"
    }
    rating: "TODO"
    comments: "TODO"
  }
  cinematography {
    cinematographer {
      name: "Fernando Ruiz"
    }
    rating: "TODO"
    comments: "TODO"
  }
  editing {
    editor {
      name: "Chika Konishi"
    }
    editor {
      name: "Frank Moderna"
    }
    rating: "TODO"
    comments: "TODO"
  }
  sound {
    rating: "TODO"
    comments: "TODO"
  }
  visual_effects {
    rating: "TODO"
    comments: "TODO"
  }
  pacing: "Pacing "
  climax: "Climax "
  tone: "Tone "
  final_notes: ""
  overall: "Overall, "
}
release_year: 2024
review_date: "10/25/2024"
redux: false
id: 498
imdb_id: "tt10974574"

* World Premeire at Austin Film Festival