title: "Renfield"
rating: 1.0
review {
  direction {
    director {
      name: "Chris McKay"
    }
    comments: "Direction ()"
  }
  acting {
    actor {
      name: "Nicholas Hoult"
      comments: " from Nicholas Hoult ()"
    }
    actor {
      name: "Awkwafina"
      comments: " from Awkwafina ()"
    }
    actor {
      name: "Ben Schwartz"
      comments: " from Ben Schwartz ()"
    }
    actor {
      name: "Adrian Martinez"
      comments: " from Adrian Martinez ()"
    }
    actor {
      name: "Shohreh Aghdashloo"
      comments: " from Shohreh Aghdashloo ()"
    }
    actor {
      name: "Nicolas Cage"
      comments: " from Nicolas Cage ()"
    }
    cast: "from the rest of the cast ()"
    comments: " Acting"
  }
  story {
    writer {
      name: "Robert Kirkman"
    }
    comments: "Story ()"
  }
  screenplay {
    writer {
      name: "Ryan Ridley"
    }
    comments: "Screenplay ()"
  }
  score {
    composer {
      name: "Marco Beltrami"
    }
    comments: "Score ()"
  }
  cinematography {
    cinematographer {
      name: "Mitchell Amundsen"
    }
    comments: "Cinematography ()"
  }
  sound: "Sound ()"
  editing {
    editor {
      name: "Ryan Folsey"
    }
    editor {
      name: "Giancarlo Ganziano"
    }
    editor {
      name: "Zene Baker"
    }
    comments: "Editing ()"
  }
  visual_effects: "Visual Effects ()"
  production_design: "Production Design ()"
  makeup: "Makeup ()"
  costumes: "Costumes ()"
  plot_structure: "Plot Structure "
  pacing: "Pacing "
  climax: "Climax "
  tone: "Tone "
  final_notes: ""
  overall: "Overall, "
}
release_year: 2023
review_date: "04/17/2023"
redux: false
id: 334
imdb_id: "tt11358390"
