title: "Robot Dreams"
rating: 0.1
review {
  direction {
    director {
      name: "Pablo Berger"
    }
    rating: "Good"
    comments: "The drection on a macroscale is very cute as they create this animated animal parody world; the direction on a microscale is good as it uses a lot of action-based sequences to describe what is going on, and subtly convey the emotions of the character; the storytelling is pretty simple, but uses a lot of fake sequences to subvert the expectations of the audience"
  }
  story {
    writer {
      name: "Pablo Berger"
    }
    rating: "Pretty Good"
    comments: "The concept is very cute, but sad as they use an animated dog and robot to show the impact loneliness and companionship has on an individual; the plot structure is pretty simple, but the ending feels a bit dragged out; the character writing is good as Dog and Robot are both lonely individuals looking for companionship and acceptance"
  }
  screenplay {
    writer {
      name: "Pablo Berger"
    }
    rating: "Good"
    comments: "The lack of dialogue is profound as it amplifies the feeling of loneliness that the characters expereince; the humor is pretty playful; the symbolism is profound as the whole movie an allegory for loneliness and the importance of companionship; there is a lack of foreshadowing because they try to subvert your expectations by interweaving dream and real sequences"
  }
  score {
    composer {
      name: "Alfonso de Vilallonga"
    }
    rating: "Good"
    comments: "Very lighthearted and used well to help make the movie feel cute and playful"
  }
  soundtrack {
    rating: "Good"
    comments: "Used well to help the characters express their emotions"
  }
  editing {
    editor {
      name: "Fernando Franco"
    }
    rating: "Good"
    comments: "Felt very polished and helped show the connection between Dog and Robot despite their distance"
  }
  sound {
    rating: "Good"
    comments: "Used well to help the characters express themselves as the movie does not have any dialogue"
  }
  animation {
    rating: "Very Good"
    comments: "Very cute and helped create this parody animal Manhattan from the 1980s"
  }
  pacing: "Pacing is fine for the most part but drags a lot during the end"
  climax: "Climax is a little bit too long and really subverts your expectations; even though I was personally not a fan of the ending, I respect what they were going for because it was pretty realistic"
  tone: "Tone is very cute and playful (but very sad at the same time with what is going on)"
  final_notes: "The dream sequences got a bit too repeatitive towards the end (but I understand why there were included)"
  overall: "Overall, a very cute, but sad movie that uses a friendship between an aniamted dog and robot as an allegory for loneliness and the need for companionship"
}
release_year: 2023
review_date: "06/16/2024"
redux: false
id: 460
imdb_id: "tt13429870"
