title: "Rocky"
rating: 9.7
review: "Exellent acting by all characters, Incredible story, Incredible screenplay, Incredible music, Unpredictable ending, Can tell the crew made the best of what they could from such a low budget, Can be very slow at points "
release_year: 1976
review_date: "02/12/2017"
redux: false
