title: "Rocketman"
rating: 8.5
review: "Incredible Performance by Taren Egerton, Music was very well performed by the cast, Story was very good, Acting was good by the rest of the cast, Great celebration of Elton John\'s career and work, very funny when it needs to be and very serious when it needs to be, Time and continuity was not very good from the movie because there was not signs of when each event occurred or what year everything took place in, great costume design."
release_year: 2019
review_date: "12/22/2019"
redux: false
id: 116
imdb_id: "tt2066051"
