title: "Rogue One: A Star Wars Story"
review {
  direction {
    director {
      name: "Gareth Edwards"
    }
    comments: "Direction ()"
  }
  acting {
    actor {
      name: "Felicity Jones"
      comments: " from Felicity Jones ()"
    }
    actor {
      name: "Diego Luna"
      comments: " from Diego Luna ()"
    }
    actor {
      name: "Ben Mendelsohn"
      comments: " from Ben Mendelsohn ()"
    }
    actor {
      name: "Donnie Yen"
      comments: " from Donnie Yen ()"
    }
    actor {
      name: "Mads Mikkelsen"
      comments: " from Mads Mikkelsen ()"
    }
    actor {
      name: "Alan Tudyk"
      comments: " from Alan Tudyk ()"
    }
    actor {
      name: "Jiang Wen"
      comments: " from Jiang Wen ()"
    }
    actor {
      name: "Forest Whitaker"
      comments: " from Forest Whitaker ()"
    }
    cast: "from the rest of the cast ()"
    comments: " Acting "
  }
  story {
    writer {
      name: "John Knoll"
    }
    writer {
      name: "Gary Whitta"
    }
    comments: "Story ()"
  }
  screenplay {
    writer {
      name: "Chris Weitz"
    }
    writer {
      name: "Tony Gilroy"
    }
    comments: "Screenplay ()"
  }
  score {
    composer {
      name: "Michael Giacchino"
    }
    comments: "Score ()"
  }
  cinematography {
    cinematographer {
      name: "Greig Fraser"
    }
    comments: "Cinematography ()"
  }
  sound: "Sound ()"
  editing {
    editor {
      name: "John Gilroy"
    }
    editor {
      name: "Jabez Olssen"
    }
    editor {
      name: "Colin Goudie"
    }
    comments: "Editing ()"
  }
  visual_effects: "Visual Effects ()"
  production_design: "Production Design ()"
  makeup: "Makeup ()"
  costumes: "Costumes ()"
  plot_structure: "Plot Structure "
  pacing: "Pacing "
  climax: "climax "
  tone: "tone"
  final_notes: ""
  overall: "Overall, "
}
release_year: 2016
review_date: "1/30/2023"
redux: false
