title: "Roma"
rating: 7.3
review: "Note: Not fair for me to judge do to the fact it is a foreign film of a different taste. The story was decent, the acting was decent, the direction was very good, the cinematography was incredible, the movie dragged and was boring for the first 2/3 of the movie, The ending was good."
release_year: 2018
review_date: "02/24/2019"
redux: false
