title: "Rosemary\'s Baby"
rating: 8.8
review: "Great Direction, Great Acting by the entire cast, Good to Great Story (First half was good but boring but the second half was great), Great Screenplay (Dialogue was good to great and the symbolism and foreshadowing was subtle but prevenlant), Good Score, Pacing was a tale of two movies where the first half of the movie relied heavily on exposition and the second half of the movie had great pacing, First half of the movie relied too much on exposition and could be boring at times because of its slow pacing, the second half of the movie really hits its stride as it continues to get better and better to the point where the final 30 minutes was very suspenseful and captivating to watch, Final 30 minutes of the movie (Climax) was pretty scary"
release_year: 1968
review_date: "07/26/2020"
redux: false
