title: "Rush Hour"
rating: 6.9
review {
  direction {
    director {
      name: "Brett Ratner"
    }
    rating: "Decent to Pretty Good"
    comments: "The direction on a macroscale feels very 90s television, mixed with 90s action; the direction on a microscale is very 90s sitcom, but still enjoyable; the storytelling is pretty simple and similar to other action-comedies from the time period"
  }
  acting {
    performance {
      actor {
        name: "Jackie Chan"
      }
      rating: "Good"
      comments: "Has his signature Jackie Chan charm and has amazing chemistry with Chris Tucker"
    }
    performance {
      actor {
        name: "Chris Tucker"
      }
      rating: "Good"
      comments: "Has his signature Chris Tucker charm and has amazing chemistry with Jackie Chan"
    }
    performance {
      actor {
        name: "Tom Wilkinson"
      }
      rating: "Pretty Good"
      comments: "Standard English performance"
    }
    cast {
      rating: "Decent"
      comments: "Decent performances all around help move the story forward"
    }
    rating: "Pretty Good"
  }
  story {
    writer {
      name: "Ross LaManna"
    }
    rating: "Decent"
    comments: "The concept is a buddy cop comedy that is a cultural melting pot between Hong Kong and LA; the plot structure is a simple buddy cop; the character writing for the two leads is very good, as you can see how their chemistry is building throughout the movie"
  }
  screenplay {
    writer {
      name: "Jim Kouf"
    }
    writer {
      name: "Ross LaManna"
    }
    rating: "Pretty Good"
    comments: "The dialogue is pretty good as it injects comedy well; the humor is very good as it has an iconic edgy charm to it that makes this movie memorable; the chemistry between Chan and Tucker helps make this movie iconic; the symbolism is somewhat prevalent; the foreshadowing is pretty predictable"
  }
  score {
    composer {
      name: "Lalo Schifrin"
    }
    rating: "Decent"
  }
  soundtrack {
    rating: "Decent"
  }
  cinematography {
    cinematographer {
      name: "Adam Greenberg"
    }
    rating: "Decent"
    comments: "Felt very low-budget, 90s action movie"
  }
  editing {
    editor {
      name: "Mark Helfrich"
    }
    rating: "Decent"
  }
  sound {
    rating: "Decent"
  }
  visual_effects {
    rating: "Pretty Good"
    comments: "Used well in the action sequences"
  }
  pacing: "Pacing is good"
  climax: "The climax is executed well and shows how much trust Carter and Lee have with each other"
  tone: "Tone is very 90s action-comedy (but definitely feels rated R)"
  final_notes: ""
  overall: "Overall, a fun buddy-cop comedy that is iconic for its over-the-line humor and great chemistry between Jackie Chan and Chris Tucker, but feels incredibly formulaic and 90s"
}
release_year: 1998
review_date: "07/23/2024"
redux: false
id: 469
imdb_id: "tt0120812"
