title: "Rush Hour"
rating: 0.1
review {
  direction {
    director {
      name: "Brett Ratner"
    }
    rating: "TODO"
    comments: "macroscale is; microscale is; direction of actors is; storytelling is; tension is"
  }
  acting {
    performance {
      actor {
        name: "Jackie Chan"
      }
      rating: "TODO"
      comments: "TODO"
    }
    performance {
      actor {
        name: "Chris Tucker"
      }
      rating: "TODO"
      comments: "TODO"
    }
    performance {
      actor {
        name: "Tom Wilkinson"
      }
      rating: "TODO"
      comments: "TODO"
    }
    performance {
      actor {
        name: "Chris Penn"
      }
      rating: "TODO"
      comments: "TODO"
    }
    performance {
      actor {
        name: "Elizabeth Pe\303\261a"
      }
      rating: "TODO"
      comments: "TODO"
    }
    cast {
      rating: "TODO"
      comments: "TODO"
    }
    rating: ""
  }
  story {
    writer {
      name: "Ross LaManna"
    }
    rating: "TODO"
    comments: "The concept is; the plot structure is; flow between sequences is; character writing is"
  }
  screenplay {
    writer {
      name: "Jim Kouf"
    }
    writer {
      name: "Ross LaManna"
    }
    rating: "TODO"
    comments: "The dialogue is; the humor is; the symbolism is; the foreshadowing is"
  }
  score {
    composer {
      name: "Lalo Schifrin"
    }
    rating: "TODO"
    comments: "TODO"
  }
  cinematography {
    cinematographer {
      name: "Adam Greenberg"
    }
    rating: "TODO"
    comments: "TODO"
  }
  editing {
    editor {
      name: "Mark Helfrich"
    }
    rating: "TODO"
    comments: "TODO"
  }
  sound {
    rating: "TODO"
    comments: "TODO"
  }
  visual_effects {
    rating: "TODO"
    comments: "TODO"
  }
  production_design {
    rating: "TODO"
    comments: "TODO"
  }
  makeup {
    rating: "TODO"
    comments: "TODO"
  }
  costumes {
    rating: "TODO"
    comments: "TODO"
  }
  pacing: "Pacing "
  climax: "Climax "
  tone: "Tone "
  final_notes: ""
  overall: "Overall, "
}
release_year: 1998
review_date: "07/23/2024"
redux: false
id: 469
imdb_id: "tt0120812"
