title: "Rush"
rating: 8.6
review {
  direction {
    director {
      name: "Ron Howard"
    }
    comments: "Good Direction"
  }
  acting {
    actor {
      name: "Daniel Brühl"
      comments: "Great from Daniel Brühl"
    }
    cast: "Good from the rest of the cast"
    comments: "Good to Very Good Acting"
  }
  story {
    writer {
      name: "Peter Morgan"
    }
    comments: "Good to Very Good Story (Pretty true to the story)"
  }
  cinematography {
    cinematographer {
      name: "Anthony Dod Mantle"
    }
    comments: "Good Cinematography"
  }
  sound: "Good Sound"
  editing {
    editor {
      name: "Daniel Hanley"
    }
    editor {
      name: "Mike Hill"
    }
    comments: "Good Editing (Very unique editing sequences that were good at times and very extra at others)"
  }
  final_notes: "The movie felt very short and rushed a lot in terms of the plot (no pun intended)"
  overall: "Overall, a good movie that I will compare a lot to Ford v. Ferrari where this movie had a better story and was more serious while the other movie is more of a fun watch with better technicals"
}
release_year: 2013
review_date: "05/11/2021"
redux: false
