title: "Santosh"
rating: 0.1
review {
  direction {
    director {
      name: "Sandhya Suri"
    }
    rating: "TODO"
    comments: "macroscale is; microscale is; direction of actors is; storytelling is; tension is"
  }
  acting {
    performance {
      actor {
        name: "Shahana Goswami"
      }
      rating: "TODO"
      comments: "TODO"
    }
    performance {
      actor {
        name: "Sunita Rajwar"
      }
      rating: "TODO"
      comments: "TODO"
    }
    performance {
      actor {
        name: "Sanjay Bishnoi"
      }
      rating: "TODO"
      comments: "TODO"
    }
    performance {
      actor {
        name: "Kushal Dubey"
      }
      rating: "TODO"
      comments: "TODO"
    }
    cast {
      rating: "TODO"
      comments: "TODO"
    }
    rating: "TODO"
  }
  story {
    writer {
      name: "Sandhya Suri"
    }
    rating: "TODO"
    comments: "The concept is; the plot structure is; flow between sequences is; character writing is"
  }
  screenplay {
    writer {
      name: "Sandhya Suri"
    }
    rating: "TODO"
    comments: "The dialogue is; the humor is; the symbolism is; the foreshadowing is"
  }
  score {
    composer {
      name: "Luisa Gerstein"
    }
    rating: "TODO"
    comments: "TODO"
  }
  cinematography {
    cinematographer {
      name: "Lennert Hillege"
    }
    rating: "TODO"
    comments: "TODO"
  }
  editing {
    editor {
      name: "Maxime Pozzi-Garcia"
    }
    rating: "TODO"
    comments: "TODO"
  }
  sound {
    rating: "TODO"
    comments: "TODO"
  }
  pacing: "Pacing "
  climax: "Climax "
  tone: "Tone "
  final_notes: ""
  overall: "Overall, "
}
release_year: 2024
review_date: "10/29/2024"
redux: false
id: 504
imdb_id: "tt30444418"

* Premeire at Austin Film Festival