title: "Saw"
rating: 6.5
review {
  direction {
    director {
      name: "James Wan"
    }
    rating: "Pretty Bad"
    comments: "Direction for traps and plot elements was good but was horrible besides that (especially with dialogue and interpersonal scenes)"
  }
  acting {
    rating: "Terrible"
  }
  story {
    writer {
      name: "James Wan"
    }
    writer {
      name: "Leigh Whannell"
    }
    rating: "Great"
    comments: "Has very iconic elements to it that are filled with twists and turns that are not expected"
  }
  screenplay {
    writer {
      name: "Leigh Whannell"
    }
    rating: "Very Bad"
    comments: "Though it does had iconic lines and moments at times"
  }
  score {
    composer {
      name: "Charlie Clouser"
    }
    rating: "Great"
    comments: "Iconic score with an iconic theme"
  }
  production_design {
    rating: "Great"
    comments: "Captures a dark, dirty, and scary environment"
  }
  climax: "The buildup to the climax was gradual and fine but the actual climax really was not carried out well (Though post climax/ending was very well carried out and iconic in showing the twists of the story)"
  final_notes: "The trap scenes were very well executed to show the fear in the characters"
  overall: "Overall, for a movie with such a low budget, the creators were able to develop the most from what they could as they created an iconic story line that is a mainstay in the horror franchise, even though it may not be the best in its presentation"
}
release_year: 2004
review_date: "05/11/2021"
redux: false
id: 187
imdb_id: "tt0387564"
