title: "Schindler\'s List"
rating: 9.6
review: "Incredible Story, Great Screenplay, Very emotional, Incredible Score, Great Acting, Very true and eyeopening, IMO there was a little too much emphasis on parts that did not need to emphasized in the Schindler Storyline, Not traditional for a purpose: A movie that is not a movie but a message."
release_year: 1993
review_date: "05/22/2019"
redux: false
