title: "Se7en"
rating: 9.3
review: "Great Direction, Incredible Story, Good Screenplay, Good Acting (Kinda meh at the beginning but gets better as it goes on), Incredible Production Design, Great Cinematography, Good Score, Movie gets better as it progresses (Very meh at the beginning but gets better and better as the plot progresses), Pacing is good (Though more story heavy towards the end), Very well/iconic made climax, Great Editing."
release_year: 1995
review_date: "06/21/2020"
redux: false
id: 140
imdb_id: "tt0114369"
