title: "Shatranj Ke Khilari"
rating: 7.8
review: "Take this review with a grain of salt cause I had to watch this movie at 3x the speed. The visuals and music were very good, Great symbolism, Very comedic and funny at times, Kinda was pointless at times and very stupid at times as well, The story took elements from the written text yet made its own interpretation very clear."
release_year: 1977
review_date: "04/18/2019"
redux: false
id: 92
imdb_id: "tt0076696"
