title: "Shaun of the Dead"
rating: 8.8
review {
  direction {
    director {
      name: "Edgar Wright"
    }
    comments: "Very Good Direction (Was able to help progress the movie forward in a very distinct style that is satire of the Zombie genre, also is able to use different editing techniques to make the movie very 00s)"
  }
  acting {
    actor {
      name: "Simon Pegg"
      comments: "Good to Very Good from Simon Pegg (Played the titular character very well and is able to have other characters bounce off of him to help build jokes; also is able to show different ranges of emotion pretty well)"
    }
    actor {
      name: "Nick Frost"
      comments: "Good from Nick Frost (Plays the comic relief character pretty well)"
    }
    cast: "Pretty Good to Good from the rest of the cast"
    comments: "Good Acting"
  }
  story {
    writer {
      name: "Simon Pegg"
    }
    writer {
      name: "Edgar Wright"
    }
    comments: "Very Good Story (A nice satire of the zombie genre but is a bit too safe at times (especially the end))"
  }
  screenplay {
    writer {
      name: "Simon Pegg"
    }
    writer {
      name: "Edgar Wright"
    }
    comments: "Very Good Screenplay (the different movements and dialogue help move the satire forward and makes it for a very overall funny movie (though it is pretty simplistic in what it is))"
  }
  score {
    composer {
      name: "Pete Woodhead"
    }
    composer {
      name: "Daniel Mudford"
    }
    comments: "Pretty Good Score"
  }
  cinematography {
    cinematographer {
      name: "David M. Dunlap"
    }
    comments: "Good Cinematography (Helps with the different fast-cuts and the side-panning helps it mock the zombie genre with the staple shot)"
  }
  sound: "Good Sound"
  editing {
    editor {
      name: "Chris Dickens"
    }
    comments: "Great Editing (a very polished rendition that helped in showing why the fast-cutting/hip-hop montage were a main-stay in the early 00s)"
  }
  visual_effects: "Pretty Bad Visual Effects (Felt very low budget and not well done)"
  makeup: "Pretty Bad Makeup (Felt pretty amateur and low budget when trying to convey the zombies)"
  plot_structure: "Plot Structure was pretty simplistic and formulaic (though there really was not anything to add or cut)"
  pacing: "Pacing was consistent and steady"
  climax: "Build to climax was there and a pivotal part in how the character dealt with the apocalypse; climax was fine but felt very safe and 00s in how it ended"
  tone: "Tone was very similar to that of satires as is very light-hearted while taking elements of the zombie genre"
  overall: "Overall, a very good satire that is a fun laugh as it pokes at the zombie genre in a very unique way, though it can be very simplistic and safe at times"
}
release_year: 2004
review_date: "07/19/2022"
redux: false
