title: "Silver Linings Playbook"
rating: 9.1
review: "Incredible Acting by the cast as a whole (Especially Bradley Cooper then Jennifer Lawrence then Robert De Niro), Great Screenplay, pretty good story, Great Direction, Great mix of both comedic and dramatic moments throughout the movie, Incredible displays of mental illness by the lead characters, great indian representation, The plot was very predictable and cliche towards the end. Overall, a movie that is carried by the performances of the main cast who have to carry such a heavy topic with a great script that is filled with cliches."
release_year: 2012
review_date: "08/24/2020"
redux: false
id: 160
imdb_id: "tt1045658"
