title: "Slumdog Millionaire"
rating: 9.4
review {
  direction {
    director {
      name: "Danny Boyle"
    }
    director {
      name: "Loveleen Tandan"
    }
    rating: "Incredible to Brilliant"
  }
  acting {
    performance {
      actor {
        name: "Dev Patel"
      }
      rating: "Great"
    }
    performance {
      actor {
        name: "Freida Pinto"
      }
      rating: "Good"
    }
    performance {
      actor {
        name: "Anil Kapoor"
      }
      rating: "Great"
    }
    performance {
      actor {
        name: "Irrfan Khan"
      }
      rating: "Great"
    }
    cast {
      rating: "Pretty Good"
      comments: "Great from Kids, Good from adults, Decent from teenagers"
    }
    rating: "Very Good"
  }
  story {
    writer {
      name: "Simon Beaufoy"
    }
    rating: "Incredible"
    comments: "A mix of bollywood with hollywood in a telling of \'Indian\' Forrest Gump; also, the narrative and the story points molding together was extremely well done"
  }
  screenplay {
    writer {
      name: "Simon Beaufoy"
    }
    rating: "Great to Incredible"
    comments: "The dialogue during the non-romantic parts were incredible while the romantic parts were not as well done; the symbolism of how Jamal was able to use life experiences to be a true rags to riches was incredible"
  }
  score {
    composer {
      name: "A. R. Rahman"
    }
    rating: "Great"
  }
  soundtrack {
    rating: "Incredible"
  }
  cinematography {
    cinematographer {
      name: "Anthony Dod Mantle"
    }
    rating: "Great"
  }
  editing {
    editor {
      name: "Chris Dickens"
    }
    rating: "Incredible"
  }
  sound {
    rating: "Good"
  }
  production_design {
    rating: "Great"
    comments: "Shows the poorer parts of india (rest was also good)"
  }
  pacing: "Pacing was good but a bit inconsistent (slow during the childhood, extremely fast during the teenage years, decently fast during the adult years); runtime was a bit long but not terrible (probably could have cut out a few sequences)"
  climax: "The build to the climax was incredible with the actual climax being extremely tense and modeling how bollywood climaxes are usually; the resolution was a bit poor in its execution and the movie could have ended with the climax (though the bollywood sequence at the end was a nice touch)"
  final_notes: "The incredible nature of the movie is how the plot points throughout the movie connect at the end and during the competition (even though there aren\'t any deeper meanings in the movie); it is important to note that many of the elements of the movie is incredibly unlikely to happen (like people from the slums learning fluent English)"
  overall: "Overall, a Great to Incredible Movie that shows some of the dangerous and true natures of India while highlighting some of its beauty as Danny Boyle pulls off an incredible rendition of \'Indian Forrest Gump\' by loosely basing a story from the source material to show a bollywood rendition of the \'rags to riches\' trope in what is an incredible watch"
}
release_year: 2008
review_date: "08/01/2021"
redux: false
id: 215
imdb_id: "tt1010048"
