title: "Sorry to Bother You"
rating: 8.6
review: "Very good concept, handles race better than Get out but the twist is very weird. Good screenplay and good acting"
release_year: 2018
review_date: "10/28/2018"
redux: false
