title: "Space Jam"
rating: 7.2
review {
  direction {
    director {
      name: "Joe Pytka"
    }
    comments: "Pretty Bad Direction"
  }
  acting {
    actor {
      name: "Michael Jordan"
      comments: "Decent from Michael Jordan"
    }
    actor {
      name: "Wayne Knight"
      comments: "Pretty Good to Good from Wayne Knight"
    }
    actor {
      name: "Danny DeVito"
      comments: "Great from Danny DeVito"
    }
    cast: "Very Bad from the rest of the live acting cast; Great Voice Acting by the entire Looney Tunes cast"
    comments: "Bad Acting"
  }
  story {
    writer {
      name: "Leo Benvenuti"
    }
    writer {
      name: "Steve Rudnick"
    }
    writer {
      name: "Timothy Harris"
    }
    writer {
      name: "Herschel Weingrod"
    }
    comments: "Good Story"
  }
  screenplay {
    writer {
      name: "Leo Benvenuti"
    }
    writer {
      name: "Steve Rudnick"
    }
    writer {
      name: "Timothy Harris"
    }
    writer {
      name: "Herschel Weingrod"
    }
    comments: "Screenplay of two halves (Looney Tunes Parts were great and very similar to its traditional style, Real life parts were bad to pretty bad overall; there were some good references and jokes that I did appreciate (Mighty Ducks, Pulp Fiction, Patton, etc.))"
  }
  score {
    composer {
      name: "James Newton Howard"
    }
    comments: "Decent to Pretty Good Score (Liked how it incorporated Looney Tunes elements); Good Soundtrack"
  }
  cinematography {
    cinematographer {
      name: "Michael Chapman"
    }
    comments: "Pretty Good Cinematography (made it feel very animated)"
  }
  sound: "Decent Sound"
  editing {
    editor {
      name: "Sheldon Kahn"
    }
    comments: "Decent Editing"
  }
  visual_effects: "Pretty Good Animation and stitches with real life (especially for the time) as it gives it a pretty cartoony feel"
  production_design: "Production Design ()"
  makeup: "Makeup ()"
  costumes: "Costumes ()"
  plot_structure: "Plot Structure "
  pacing: "Pacing was very fast and really rushed between plot elements; Runtime was very short (definitely could have used 15-20 minutes in the rising action as the film goes from exposition to the climax)"
  climax: "Skips build to climax; the actual basketball game (climax) was executed very well as it was the best part of the movie and gives off a good message to the audience"
  overall: "Overall, a decent, fun watch that was geared mostly for kids as it was good to see how two icons (MJ in the NBA and Bugs Bunny in Looney Tunes) were able to come together to give off a lot of iconic moments with the battle with the monstars as the movie does not try to take itself too seriously"
}
release_year: 1996
review_date: "07/28/2021"
redux: false
