title: "Spider-Man"
rating: 8.6
review: "Iconic, great story, Decent acting, plot holes in how he became a good fighter, a childhood movie favorite, good screenplay, plays emotions pretty well, good action"
release_year: 2002
review_date: "05/21/2017"
redux: false
