title: "Spider-Man: Into the Spiderverse"
rating: 1.0
review {
  direction {
    director {
      name: "Bob Persichetti"
    }
    director {
      name: "Peter Ramsey"
    }
    director {
      name: "Rodney Rothman"
    }
    comments: "Direction ()"
  }
  acting {
    actor {
      name: "Shameik Moore"
      comments: " from Shameik Moore ()"
    }
    actor {
      name: "Jake Johnson"
      comments: " from Jake Johnson ()"
    }
    actor {
      name: "Hailee Steinfeld"
      comments: " from Hailee Steinfeld ()"
    }
    actor {
      name: "Mahershala Ali"
      comments: " from Mahershala Ali ()"
    }
    actor {
      name: "Brian Tyree Henry"
      comments: " from Brian Tyree Henry ()"
    }
    actor {
      name: "Lily Tomlin"
      comments: " from Lily Tomlin ()"
    }
    actor {
      name: "Luna Lauren V\303\251lez"
      comments: " from Luna Lauren V\303\251lez ()"
    }
    actor {
      name: "John Mulaney"
      comments: " from John Mulaney ()"
    }
    actor {
      name: "Kimiko Glenn"
      comments: " from Kimiko Glenn ()"
    }
    actor {
      name: "Nicolas Cage"
      comments: " from Nicolas Cage ()"
    }
    actor {
      name: "Liev Schreiber"
      comments: " from Liev Schreiber ()"
    }
    cast: "from the rest of the cast ()"
    comments: " Acting"
  }
  story {
    writer {
      name: "Phil Lord"
    }
    comments: "Story ()"
  }
  screenplay {
    writer {
      name: "Phil Lord"
    }
    writer {
      name: "Rodney Rothman"
    }
    comments: "Screenplay ()"
  }
  score {
    composer {
      name: "Daniel Pemberton"
    }
    comments: "Score ()"
  }
  sound: "Sound ()"
  editing {
    editor {
      name: "Robert Fisher Jr."
    }
    comments: "Editing ()"
  }
  visual_effects: "Visual Effects ()"
  production_design: "Production Design ()"
  makeup: "Makeup ()"
  costumes: "Costumes ()"
  plot_structure: "Plot Structure "
  pacing: "Pacing "
  climax: "Climax "
  tone: "Tone "
  final_notes: ""
  overall: "Overall, "
}
release_year: 2018
review_date: "06/01/2023"
redux: false
id: 348
imdb_id: "tt4633694"
