title: "Spider-Man 2"
rating: 0.1
review {
  direction {
    director {
      name: "Sam Raimi"
    }
    rating: "TODO"
    comments: "macroscale is; microscale is; direction of actors is; storytelling is; tension is"
  }
  acting {
    performance {
      actor {
        name: "Tobey Maguire"
      }
      rating: "TODO"
      comments: "TODO"
    }
    performance {
      actor {
        name: "Kirsten Dunst"
      }
      rating: "TODO"
      comments: "TODO"
    }
    performance {
      actor {
        name: "James Franco"
      }
      rating: "TODO"
      comments: "TODO"
    }
    performance {
      actor {
        name: "Alfred Molina"
      }
      rating: "TODO"
      comments: "TODO"
    }
    performance {
      actor {
        name: "Rosemary Harris"
      }
      rating: "TODO"
      comments: "TODO"
    }
    performance {
      actor {
        name: "Donna Murphy"
      }
      rating: "TODO"
      comments: "TODO"
    }
    cast {
      rating: "TODO"
      comments: "TODO"
    }
    rating: ""
  }
  story {
    writer {
      name: "Alfred Gough"
    }
    writer {
      name: "Miles Millar"
    }
    writer {
      name: "Michael Chabon"
    }
    rating: "TODO"
    comments: "The concept is; the plot structure is; flow between sequences is; character writing is"
  }
  screenplay {
    writer {
      name: "Alvin Sargent"
    }
    rating: "TODO"
    comments: "The dialogue is; the humor is; the symbolism is; the foreshadowing is"
  }
  score {
    composer {
      name: "Danny Elfman"
    }
    rating: "TODO"
    comments: "TODO"
  }
  cinematography {
    cinematographer {
      name: "Bill Pope"
    }
    rating: "TODO"
    comments: "TODO"
  }
  editing {
    editor {
      name: "Bob Murawski"
    }
    rating: "TODO"
    comments: "TODO"
  }
  sound {
    rating: "TODO"
    comments: "TODO"
  }
  visual_effects {
    rating: "TODO"
    comments: "TODO"
  }
  production_design {
    rating: "TODO"
    comments: "TODO"
  }
  makeup {
    rating: "TODO"
    comments: "TODO"
  }
  costumes {
    rating: "TODO"
    comments: "TODO"
  }
  pacing: "Pacing "
  climax: "Climax "
  tone: "Tone "
  final_notes: ""
  overall: "Overall, "
}
release_year: 2004
review_date: "04/23/2024"
redux: false
id: 442
imdb_id: "tt0316654"
