title: "Spotlight"
rating: 9.3
review: "Great to Incredible direction, Great to Incredible Screenplay (Written and made as if it was taken from a documentary), Great Story (Concepts and overarching story is incredible but narrative direction and overall plot structure was kinda dragging at times), Incredible Acting by the cast overall (Nobody stands out as everyone acts as a key piece to the story), very good score, Pacing was a little bit slow and dragging at times towards the middle but not too bad overall, Some of the choices in terms of plot direction were kinda meh, Great to Incredible drama overall and one of the best movies on newspaper journalism, a movie that should be known for its scenes to be analyzed in isolation but not in how they all come together as each scene is worth its own merit but the overall scenes coming together does not keep to that same standard."
release_year: 2015
review_date: "08/13/2020"
redux: false
id: 155
imdb_id: "tt1895587"
