title: "Stand and Deliver"
rating: 7.5
review: "Great Acting by lead, great story, pretty bad acting by the rest of the class, Decent screenplay, unnecessary dramatic acting at some points, very Asian Score"
release_year: 1988
review_date: "05/21/2017"
redux: false
