title: "Star Wars: Episode I \342\200\223 The Phantom Menace"
rating: 6.9
review: "Acting by the vetern actors was good (Liam Neeson, Ewan Mcgregor especially, Samuel L Jackson, and Yoda), the acting by those who are not experienced were either medicore or very bad, Direction was horrible, Story was great, Screenplay was terrible, Visuals were really good, Score was incredible, Production Design was great, Film aged better than most would have thought, Pacing was really off in the first half "
release_year: 1999
review_date: "12/18/2019"
redux: false
