title: "Star Wars: Episode II \342\200\223 Attack of the Clones"
rating: 7.0
review: "Started off very poor in the first 1/2, picked up in the second half. Ewan Mcgregor is still incredible, acting by Hayden and Natalie is poor, acting by vetern actors is fine, screenplay is still bad, story is great, visuals are incredible, score is incredible, Most unimportant movie of the prequels."
release_year: 2002
review_date: "12/28/2019"
redux: false
