title: "Star Wars: Episode II \342\200\223 Attack of the Clones"
rating: 6.7
review: "Started off very poor in the first 1/2 and picked up in the second half, Ewan McGregor is still incredible, acting by Hayden and Natalie is Bad, acting by veteran actors is fine, screenplay is still bad, story is great, visuals are incredible, score is incredible, Most unimportant movie of the prequels."
release_year: 2002
review_date: "12/28/2019"
redux: false
id: 112
imdb_id: "tt0121765"
