title: "Star Wars: Episode IV \342\200\223 A New Hope"
rating: 9.5
review {
  direction {
    director {
      name: "George Lucas"
    }
    rating: "Very Good"
    comments: "The actual moving of the story and making sure all pieces come together is incredibly managed and executed, it is just the actual direction of characters was pretty poorly done (which kinda reveals the truth that George Lucas is a visionary in storytelling, but not that Great in actually directing people)"
  }
  acting {
    performance {
      actor {
        name: "Mark Hamill"
      }
      rating: "Very Good"
      comments: "Really excelled at playing the naive kid who is interested in helping very well, shows a bit of inexperience but that is to be accepted when he is playing a very young character that is the hero"
    }
    performance {
      actor {
        name: "Harrison Ford"
      }
      rating: "Very Good to Great"
      comments: "The real star of the show in all his scenes as his smooth/cool nature really helps show how great of a character Han Solo really is (though there are moments that are kinda iffy with the awkwardness and silence from line deliveries)"
    }
    performance {
      actor {
        name: "Carrie Fisher"
      }
      rating: "Pretty Good"
      comments: "Her performance does not compete with the others but she does play the damsel in distress character trope very well (though it is a bit annoying when she is changing between accents as it sounds like she is putting on a fake English accent at times)"
    }
    performance {
      actor {
        name: "Peter Cushing"
      }
      rating: "Pretty Good to Good"
      comments: "Not really that much in the movie despite his high billing"
    }
    performance {
      actor {
        name: "Alec Guinness"
      }
      rating: "Great"
      comments: "Really shows his experience as an actor in this performance as he has much range in showing both care for Luke yet trauma from his past that still effects him"
    }
    performance {
      actor {
        name: "Anthony Daniels"
      }
      rating: "Very Good"
      comments: "Really brings C-3PO to life as he tries to help but panics in not knowing how much he can (the anxious nerd-savior trope); also, plays a great role in helping vocalize the relationship and friendship he has with R2-D2"
    }
    performance {
      actor {
        name: "Kenny Baker"
      }
      rating: "Incredible"
      comments: "Really brings R2 to life through the difference mannerisms the character has in sort of a comedic relief yet important way (making R2 one of the best characters in all of Star Wars); also, helps bring the flare that makes the character\'s friendship with C-3PO one of the best in pop-culture"
    }
    performance {
      actor {
        name: "Peter Mayhew"
      }
      rating: "Very Good"
      comments: "Played the adorable, yet extremely dangerous Chewie and played off his co-star very nicely, similar to the R2/C-3PO relationship"
    }
    performance {
      actor {
        name: "James Earl Jones/David Prowse"
      }
      rating: "Incredible"
      comments: "Created one of the most iconic voices in pop-culture as his menacing voice and performance showed why Darth Vader is a villain to be scared of"
    }
    cast {
      rating: "Very good"
      comments: "Very Good from the rest of the Live-Action cast; Very Good from the rest of the Vocal/Costumed-Characters cast"
    }
    rating: "Very Good"
  }
  story {
    writer {
      name: "George Lucas"
    }
    rating: "Brilliant"
    comments: "Created a world that is one of the most iconic today; the character writing is incredible as they are some of the most iconic characters in pop culture; the way the story ties all the different movies together (both prequel and later films) is very well done and visionary"
  }
  screenplay {
    writer {
      name: "George Lucas"
    }
    rating: "Very Good"
    comments: "The actual dialogue was not that well written as it felt very unnatural (as was seen from the characters trying to say the words), but where the screenplay shines is the foreshadowing to future Star Wars events, symbolism, iconic lines, and character writing to introduce the Star Wars universe as a cinematic achievement"
  }
  score {
    composer {
      name: "John Williams"
    }
    rating: "Brilliant"
    comments: "One of the most iconic scores in cinema history and is very well used throughout the movie"
  }
  cinematography {
    cinematographer {
      name: "Gilbert Taylor"
    }
    rating: "Great"
  }
  editing {
    editor {
      name: "Paul Hirsch"
    }
    editor {
      name: "Marcia Lucas"
    }
    editor {
      name: "Richard Chew"
    }
    rating: "Very Good to Great"
  }
  sound {
    rating: "Incredible"
    comments: "Especially when giving the movie a space/science-fiction feel as well as bringing the sounds of the droids (especially R2-D2) to life"
  }
  visual_effects {
    rating: "Cannot rate"
    comments: "The original Visual Effects were incredible for how revolutionary they were at the time of the release, but the added CGI from the re-release makes it very hard to watch as it just feels so forced and out of place with the original effects"
  }
  production_design {
    rating: "Incredible"
    comments: "Created some very iconic sets that are well remembered in history"
  }
  makeup {
    rating: "Incredible"
    comments: "Helped bring to life aliens that are not from this world"
  }
  costumes {
    rating: "Incredible"
    comments: "Created some of the most iconic outfits in pop-culture history, with the Darth Vader costume being one of the most well remembered in any historical context"
  }
  plot_structure: "Plot Structure was very well written as each piece builds on the previous one as everything matters in building up the movie and moving the story forward (so nothing to really add or remove)"
  pacing: "Pacing can be a bit slower at times but does maintain a very steady pace throughout the movie (pace very typical of movies from that time-period)"
  climax: "Build to climax was very well done as the movie treats the actual build as the climax (so we are building to this build very nicely throughout the movie); Climax was kinda thrown at us as in the grand scheme of things we did not build to this (we built up to the build as previously stated) but it was very well executed and really shows off the technical marvels that the original film was very groundbreaking for; moreover helps provide some insight into Luke\'s quest in finding the force and taking his first step in becoming a Jedi"
  tone: "Tone was that typical to a space opera or science fiction epic but does have some unique feel to it that makes it very Star Wars"
  final_notes: "A ground-breaking movie not only in Cinema-history but actual history as well as it ushered in a new way to view and create stories and was an inspiration for the rise in the Science-Fiction genre in the 80s and 90s"
  overall: "Overall, an important movie to watch in what created one of the most iconic franchises in the world and helped jump-start a story that is beloved by many through its technical achieves and story-writing, even though the direction is a bit lacking"
}
release_year: 1977
review_date: "06/12/2022"
redux: false
id: 263
imdb_id: "tt0076759"
