title: "Star Wars: Episode V - The Empire Strikes Back"
rating: 9.7
review {
  direction {
    director {
      name: "Irvin Kershner"
    }
    rating: "Great"
    comments: "The actual moving of the story and making sure all pieces come together is incredible managed and executed, and this movie is a definite improvement in directing people than its predecessor as the director was really able to get more out of his actors in their performances for this time around"
  }
  acting {
    performance {
      actor {
        name: "Mark Hamill"
      }
      rating: "Very Good"
      comments: "Showed the progress he has made from being a naive/hopeful kid to someone more cognizant of the present and the work he needs to put in to be a better Jedi"
    }
    performance {
      actor {
        name: "Harrison Ford"
      }
      rating: "Great"
      comments: "The real star of the show in all his scenes as he smooth/cool nature really helps show how great of a character Han Solo really is (and he really cleaned up the delivery of his lines in this movie as there are not any awkward pauses as there were last time)"
    }
    performance {
      actor {
        name: "Carrie Fisher"
      }
      rating: "Good to Very Good"
      comments: "She really improves this time around as she is given more freedom to play as opposed to last time; she also really grows as a character from being the damsel in distress to being a loving leader"
    }
    performance {
      actor {
        name: "Billy Dee Williams"
      }
      rating: "Good to Very Good"
      comments: "Really becomes a memorable presence in all the scenes he is in with his cool nature that conflicts/competes with Han, though there is some hiccups in delivery as he is still getting used to the Star Wars universe as opposed to the other members of the cast"
    }
    performance {
      actor {
        name: "Anthony Daniels"
      }
      rating: "Very Good"
      comments: "Really brings C-3PO to life as he tries to help but panics in not knowing how much he can (the anxious nerd-savior trope); also, plays a great role in helping vocalize the relationship and friendship he has with R2-D2"
    }
    performance {
      actor {
        name: "James Earl Jones/David Prowse"
      }
      rating: "Incredible"
      comments: "Created one of the most iconic voices in pop-culture as his menacing voice and performance showed why Darth Vader is a villain to be scared of"
    }
    performance {
      actor {
        name: "Kenny Baker"
      }
      rating: "Incredible"
      comments: "Really brings R2 to life through the difference mannerisms the character has in sort of a comedic relief yet important way (making R2 one of the best characters in all of Star Wars); also, helps bring the flare that makes the character\'s friendship with C-3PO one of the best in pop-culture"
    }
    performance {
      actor {
        name: "Peter Mayhew"
      }
      rating: "Very Good"
      comments: "Played the adorable, yet extremely dangerous Chewie and played off his co-star very nicely, similar to the R2/C-3PO relationship; and really grows the character to show how loving he is towards his new friends"
    }
    performance {
      actor {
        name: "Frank Oz"
      }
      rating: "Great to Incredible"
      comments: "Really brought the character of Yoda to life with the puppeteering and the vocal performance"
    }
    cast {
      rating: "Very Good"
      comments: "Good to Very Good from the rest of the Live-Action cast; Very Good from the rest of the Vocal/Costumed-Characters cast"
    }
    rating: "Very Good to Great"
  }
  story {
    writer {
      name: "George Lucas"
    }
    rating: "Incredible"
    comments: "Really sets up different elements of the universe very nicely and uses the concept of parallel storylines very well; also has some of the most iconic moments of the series and does a good job in building the downfall of the characters; the only issue this time around is that it does not have the ability to build worlds like the previous film could"
  }
  screenplay {
    writer {
      name: "Leigh Brackett"
    }
    writer {
      name: "Lawrence Kasdan"
    }
    rating: "Great"
    comments: "The dialogue this time around felt way more natural and was better written; the screenplay still shines is the foreshadowing to future Star Wars events, symbolism, iconic lines (with it having one of the most iconic lines/plot twists in cinema (or even narrative) history)"
  }
  score {
    composer {
      name: "John Williams"
    }
    rating: "Brilliant"
    comments: "Takes what was great from the previous film and adds some new themes that really make this score stand out as well"
  }
  cinematography {
    cinematographer {
      name: "Peter Suschitzky"
    }
    rating: "Great to Incredible"
    comments: "Which really stands out in the Luke vs. Vader scene"
  }
  editing {
    editor {
      name: "Paul Hirsch"
    }
    rating: "Very Good to Great"
  }
  sound {
    rating: "Very Good"
    comments: "Especially when giving the movie a space/science-fiction feel as well as bringing the sounds of the droids (especially R2-D2) to life, but there are some issues with Sound in this movie as there feels like a delayed sound with the lightsabers (which is very annoying if you have watched the prequels)"
  }
  visual_effects {
    rating: "Very Good"
    comments: "This movie does not really go overboard with the new visuals of the re-release as much as the other movies so it is easier to comment on"
  }
  production_design {
    rating: "Incredible to Brilliant"
    comments: "Created some very iconic sets that are well remembered in history, and really added to that with the Hoth/Dagobah/Bespin sets which are regarded as some of the best in all of Star Wars"
  }
  makeup {
    rating: "Incredible"
    comments: "Helped bring to life aliens that are not from this world"
  }
  costumes {
    rating: "Incredible"
    comments: "Created some of the most iconic outfits in pop-culture history, with the Darth Vader costume being one of the most well remembered in any historical context"
  }
  plot_structure: "Plot Structure was very well written as it has three major parallel story lines that all converge to the climax and the end (something that helps keep the audience engaged to see how the different arcs are coming along)"
  pacing: "Pacing was better in this movie as it felt more consistent and not as slow as the last one"
  climax: "Build to climax is done very nicely as it is really pivots the franchise into seeing who these characters really are as they have to make important decisions for the future; Climax was the best part of the movie as we get to see what Luke\'s training has come to/seeing the rest of the crew into action as we get to see how much the characters have grown yet see how far they really are to their goals in the sage; moreover one of the most important lines in history is delivered in this climax that make Star Wars a franchise memorable"
  tone: "Tone does not play as much into the space opera or science fiction epic as the last one but does have shades of it; feels more like a standout movie that really transcends genre in many ways (while still keeping the same star wars charm)"
  final_notes: "Really can be felt of as a stand alone movie (even though it leaves so much to be answered with its ending) as we get to see the rise and fall of the characters as they must continue their own individual quests to grow as characters"
  overall: "Overall, a brilliant movie that really builds on where the last movie left off and improves on it in so many ways to make it a very memorable film that is not only the best in the series but in film history as we see a more mature Star Wars in the characters that take part in it"
}
release_year: 1980
review_date: "07/03/2022"
redux: false
id: 272
imdb_id: "tt0080684"
