title: "Steve Jobs"
rating: 0.1
review {
  direction {
    director {
      name: "Danny Boyle"
    }
    rating: "TODO"
    comments: "macroscale is; microscale is; direction of actors is; storytelling is; tension is"
  }
  acting {
    performance {
      actor {
        name: "Michael Fassbender"
      }
      rating: "TODO"
      comments: "TODO"
    }
    performance {
      actor {
        name: "Kate Winslet"
      }
      rating: "TODO"
      comments: "TODO"
    }
    performance {
      actor {
        name: "Seth Rogen"
      }
      rating: "TODO"
      comments: "TODO"
    }
    performance {
      actor {
        name: "Jeff Daniels"
      }
      rating: "TODO"
      comments: "TODO"
    }
    performance {
      actor {
        name: "Michael Stuhlbarg"
      }
      rating: "TODO"
      comments: "TODO"
    }
    performance {
      actor {
        name: "Katherine Waterston"
      }
      rating: "TODO"
      comments: "TODO"
    }
    cast {
      rating: "TODO"
      comments: "TODO"
    }
    rating: ""
  }
  story {
    writer {
      name: "Aaron Sorkin"
    }
    rating: "TODO"
    comments: "The concept is; the plot structure is; flow between sequences is; character writing is"
  }
  screenplay {
    writer {
      name: "Aaron Sorkin"
    }
    rating: "TODO"
    comments: "The dialogue is; the humor is; the symbolism is; the foreshadowing is"
  }
  score {
    composer {
      name: "Daniel Pemberton"
    }
    rating: "TODO"
    comments: "TODO"
  }
  cinematography {
    cinematographer {
      name: "Alwin K\303\274chler"
    }
    rating: "TODO"
    comments: "TODO"
  }
  editing {
    editor {
      name: "Elliot Graham"
    }
    rating: "TODO"
    comments: "TODO"
  }
  sound {
    rating: "TODO"
    comments: "TODO"
  }
  visual_effects {
    rating: "TODO"
    comments: "TODO"
  }
  production_design {
    rating: "TODO"
    comments: "TODO"
  }
  makeup {
    rating: "TODO"
    comments: "TODO"
  }
  costumes {
    rating: "TODO"
    comments: "TODO"
  }
  pacing: "Pacing "
  climax: "Climax "
  tone: "Tone "
  final_notes: ""
  overall: "Overall, "
}
release_year: 2015
review_date: "07/23/2024"
redux: false
id: 470
imdb_id: "tt2080374"
