title: "Superbad"
rating: 9.7
review: "The Jokes do not miss, Incredible screenplay and story, Extremely fun to watch, Great Acting by the entire cast, some moments were meh, great starting and launching point for many of the actors in this movie, Great Direction."
release_year: 2007
review_date: "06/02/2020"
redux: false
id: 132
imdb_id: "tt0829482"
