title: "Taxi Driver"
rating: 7.6
review: "Good Acting, Good Screenplay, Good Score, Very Slow at Times, Good Ending Sequence, The buildup to the end however is pretty anticlimatic, Good depection of PTSD"
release_year: 1976
review_date: "07/09/2018"
redux: false
