title: "Tetris"
rating: 8.4
review {
  direction {
    director {
      name: "Jon S. Baird"
    }
    comments: "Good Direction (Really helps set the tone and of the movie through a more lighthearted approach to storytelling; he gets a good amount out of his actors; the movie does feel very safe and nothing extraordinary in terms of its direction)"
  }
  acting {
    actor {
      name: "Taron Egerton"
      comments: "Very Good from Taron Egerton (Does a good job in commanding the lead in the movie and showing a range of emotion throughout, the source material really limits him from going above and beyond like his other roles though)"
    }
    actor {
      name: "Toby Jones"
      comments: "Pretty Good from Toby Jones"
    }
    actor {
      name: "Nikita Yefremov"
      comments: "Pretty Good to Good from Nikita Yefremov (A bit more of a reserved performance so there is not too much to work from (not entirely his fault as that was how the character was written), but he does do a good job playing off of Egerton throughout the movie)"
    }
    cast: "Pretty Good from the rest of the cast"
    comments: "Pretty Good Acting"
  }
  story {
    writer {
      name: "Noah Pink"
    }
    comments: "Very Good Story (The overall story is well laid out, though it is a bit overt in its storytelling, and the story elements build off of each other to create suspense for the climax)"
  }
  screenplay {
    writer {
      name: "Noah Pink"
    }
    comments: "Pretty Good to Good Screenplay (A bit simplistic in the dialogue but flows well throughout; not too much symbolism because its a biopic; the humor throughout the movie was decent and helped make the film pretty lighthearted; no real foreshadowing)"
  }
  score {
    composer {
      name: "Lorne Balfe"
    }
    comments: "Good to Very Good Score (Really enjoyed how they interpolated the Tetris theme into it and used the score throughout to build suspense)"
  }
  cinematography {
    cinematographer {
      name: "Alwin H. K\303\274chler"
    }
    comments: "Good to Very Good Cinematography (Helps with placing emphasis on different subjects and was overall very professional throughout)"
  }
  sound: "Good Sound (Enjoyed how it replaced sounds with 8-bit sounds to make the movie feel more like a video game from the 80s)"
  editing {
    editor {
      name: "Martin Walsh"
    }
    editor {
      name: "Colin Goudie"
    }
    editor {
      name: "Ben Mills"
    }
    comments: "Good Editing (Really helped give that video game feel to the movie; the transitions between countries felt a bit amateurish though)"
  }
  visual_effects: "Very Good Visual Effects (Gave the movie a more 80s, NES feel when it was used in conjunction with scenes; the 8-bit animations replacing shots were pretty good but felt a bit amateur (though overall I did enjoy them))"
  plot_structure: "Plot Structure was pretty standard as it followed the standard arc (with the all parts of the plot being evident)"
  pacing: "Pacing was pretty steady with no major issues (no need to add or cut anything)"
  climax: "Climax was executed well as it was a fun rush filled with action in a movie that does not have any (though it helps suspend the disbelief if this actually happened in real life)"
  tone: "Tone was very tech as well as 80s and I felt the movie did a really good job at establishing tone; the movie did a really good job at making it a programming/CS movie as they spoke about concepts very well throughout the movie"
  final_notes: "Watched World Premiere at SXSW"
  overall: "Overall, a very entertaining movie that is a well constructed fun watch to see how Tetris escaped the Soviet Union as the tone coupled with performances help bring the audience on a fun ride, though the movie is a bit too safe in its writing and storytelling"
}
release_year: 2023
review_date: "03/19/2023"
redux: false
id: 327
imdb_id: "tt12758060"
