title: "The Wolf of Wall Street"
rating: 9.2
review: "Brilliant Acting, Incredible Screenplay, Great Story, Good Music, Extremely Funny, Editing was terrible, Way too long in that 30 mins to an hour could have been cut."
release_year: 2013
review_date: "06/18/2017"
redux: false
