title: "The Perks of Being a Wallflower"
rating: 8.4
review: "Decent Direction, Great Story, Good Screenplay on Average (Great to Incredible at some points and too meta to too angsty at others), Good Acting overall by the cast (Very believable and made me actually care about the characters, especially the main 3), Decent Cinematography, Good Symbolic shots, Pacing was very good for most of the movie but I felt the ending was a bit rushed as I would have liked to have seen another 20 minutes of it, Twist ending was good, Characters/emotions were very well written and the story and struggles makes it relatable to most of the audience being very emotional/crying at points because of how relatable the main characters struggles were, definitely one of the better coming of age stories told in recent times (And thats good considering how much I don\'t like these stories)."
release_year: 2012
review_date: "06/13/2020"
redux: false
id: 136
imdb_id: "tt1659337"
