title: "The Big Sick"
rating: 7.8
review: "The beginning is pretty boring, The movie really hits its stride when The parents come in, Has some very funny jokes but some very stupid ones too, Great story, Good screenplay, Very personal even though its paki, Acting was good by lead ok by lead girl but great by parents"
release_year: 2017
review_date: "08/15/2017"
redux: false
