title: "The Help"
rating: 6.6
review: "Good movie, acting was good (Spencer and Davis were very good), Screenplay was OK to good, story was good. "
release_year: 2011
review_date: "10/20/2017"
redux: false
