title: "The Whale"
rating: 6.9
review {
  direction {
    director {
      name: "Darren Aronofsky"
    }
    rating: "Decent to Pretty Good"
    comments: "Aronofsky falls back to a style of filmmaking he has been accustomed to (the broken character film) and pulls from a lot of his experience because of it; however, because of this, the movie does not feel very innovative and has flavors of his past films; He does not direct the actors working well together as some moments feel very choppy and it feels like the actors have a hard time playing off each other"
  }
  acting {
    performance {
      actor {
        name: "Brendan Fraser"
      }
      rating: "Great to Incredible"
      comments: "Gives the performance of his career as he fully transforms into this broken character looking for love despite not having that much time; fully embodies the struggles it takes to play someone of this size"
    }
    performance {
      actor {
        name: "Sadie Sink"
      }
      rating: "Pretty Bad"
      comments: "A very one-dimensional performance considering her character is just an angsty teen (Plays basically a poor man\'s version of Max from Stranger Things)"
    }
    performance {
      actor {
        name: "Hong Chau"
      }
      rating: "Pretty Good"
      comments: "A performance of ebbs and flows as some moments she is able to work well off of Fraser and stand on her own, and other times she has trouble working with the rest of the cast"
    }
    performance {
      actor {
        name: "Ty Simpkins"
      }
      rating: "Bad to Pretty Bad"
      comments: "A very one-dimensional performance that is not redeeming at all"
    }
    performance {
      actor {
        name: "Samantha Morton"
      }
      rating: "Pretty Bad"
      comments: "For the time she has, she really does not do that well to establish herself"
    }
    rating: "Pretty Bad"
  }
  story {
    writer {
      name: "Samuel D. Hunter"
    }
    rating: "Pretty Good"
    comments: "The construction was very tight and did make sense, there were just some plot elements that were just there really for shock (like the binge eating scenes); the ending was also a bit questionable despite how emotional it was"
  }
  screenplay {
    writer {
      name: "Samuel D. Hunter"
    }
    rating: "Decent"
    comments: "The actual dialogue was very lackluster and surface level; the subtext for loneliness and the symbols they presented for it are actually very good and help keep the audience engaged with Charlie\'s life; there is also a bit of foreshadowing that does play well in helping execute the climax"
  }
  score {
    composer {
      name: "Rob Simonsen"
    }
    rating: "Great"
    comments: "Is used very nicely throughout the movie to set the tone"
  }
  cinematography {
    cinematographer {
      name: "Matthew Libatique"
    }
    rating: "Decent"
    comments: "Very typical to other low-budget A24 movies"
  }
  editing {
    editor {
      name: "Andrew Weisblum"
    }
    rating: "Pretty Bad"
    comments: "The movie just feels very choppy at times"
  }
  sound {
    rating: "Decent"
  }
  makeup {
    rating: "Great"
    comments: "Especially with the prosthetics they used on Fraser"
  }
  plot_structure: "Plot Structure was laid out very nicely and pretty standard to other narratives"
  pacing: "Pacing was a bit on the slower side but was a non-issue throughout the movie"
  climax: "Climax of the movie was incredibly touching as everything seems to be coming to an end with characters you get so closely attached to (but the final shot of the movie was very dumb and really ruins something beautiful they were building towards)"
  tone: "Tone was very somber and depressing (and the director uses different elements very well to help with creating this)"
  final_notes: ""
  overall: "Overall, a movie that is carried by Fraser\'s performance with a story that is very heartbreaking, but feels very similar to other Aronofsky films (like Black Swan and The Wrestler) which takes away at something great they could have had, coupled with a hit-or-miss screenplay and questionable performances from the rest of the cast"
}
release_year: 2022
review_date: "01/04/2023"
redux: false
id: 307
imdb_id: "tt13833688"
