title: "The Pact"
rating: 1.6
review: "One of the worst horror movies I\'ve seen, Terrible screenplay, Terrible story, Terrible acting, not even that scary, more funny than scary, couple parts are creepy."
release_year: 2012
review_date: "02/26/2017"
redux: false
id: 13
imdb_id: "tt2040560"
