title: "The Usual Suspects"
rating: 8.5
review: "Good Direction, Great Acting by Spacey (Rest of the cast was decent except for Del Toro and Pete Postlethwaite), Good Story, Very Good Screenplay, Score was decent (Did not feel it fit the movie though), Fun movie to watch, Kinda some lapses in plot that made the narrative a bit confusing, Funny dialogue and dynamic of the entire group, action scenes were good and choreographed well, Twist Ending was iconic and Incredible to see how the movie is a lying narrative and who Keyser Soze is."
release_year: 1995
review_date: "06/23/2020"
redux: false
