title: "The Shape of Water"
rating: 7.7
review: "Good Story, Incredible Production Design, Mediocre Acting, Decent Screenplay, Good Score, Very slow at times, A lot of missed opportunities."
release_year: 2017
review_date: "03/04/2018"
redux: false
id: 60
imdb_id: "tt5580390"
