title: "The Hangover"
rating: 9.0
review: "Extremely Funny, Great Comedic Acting, Incredible Story, Funny Screenplay."
release_year: 2009
review_date: "9/16/2018"
redux: false
id: 72
imdb_id: "tt1119646"
