title: "The Lord of the Rings: The Fellowship of the Ring"
rating: 9.3
review {
  direction {
    director {
      name: "Peter Jackson"
    }
    comments: "Direction ()"
  }
  acting {
    actor {
      name: "Elijah Wood"
      comments: " from Elijah Wood ()"
    }
    actor {
      name: "Ian McKellen"
      comments: " from Ian McKellen ()"
    }
    actor {
      name: "Liv Tyler"
      comments: " from Liv Tyler ()"
    }
    actor {
      name: "Viggo Mortensen"
      comments: " from Viggo Mortensen ()"
    }
    actor {
      name: "Sean Astin"
      comments: " from Sean Astin ()"
    }
    actor {
      name: "Cate Blanchett"
      comments: " from Cate Blanchett ()"
    }
    actor {
      name: "John Rhys-Davies"
      comments: " from John Rhys-Davies ()"
    }
    actor {
      name: "Billy Boyd"
      comments: " from Billy Boyd ()"
    }
    actor {
      name: "Dominic Monaghan"
      comments: " from Dominic Monaghan ()"
    }
    actor {
      name: "Orlando Bloom"
      comments: " from Orlando Bloom ()"
    }
    actor {
      name: "Christopher Lee"
      comments: " from Christopher Lee ()"
    }
    actor {
      name: "Hugo Weaving"
      comments: " from Hugo Weaving ()"
    }
    actor {
      name: "Sean Bean"
      comments: " from Sean Bean ()"
    }
    actor {
      name: "Ian Holm"
      comments: " from Ian Holm ()"
    }
    actor {
      name: "Andy Serkis"
      comments: " from Andy Serkis ()"
    }
    cast: "from the rest of the cast ()"
    comments: " Acting "
  }
  story {
    writer {
      name: "Fran Walsh"
    }
    writer {
      name: "Philippa Boyens"
    }
    writer {
      name: "Peter Jackson"
    }
    comments: "Story ()"
  }
  screenplay {
    writer {
      name: "Fran Walsh"
    }
    writer {
      name: "Philippa Boyens"
    }
    writer {
      name: "Peter Jackson"
    }
    comments: "Screenplay ()"
  }
  score {
    composer {
      name: "Howard Shore"
    }
    comments: "Score ()"
  }
  cinematography {
    cinematographer {
      name: "Andrew Lesnie"
    }
    comments: "Cinematography ()"
  }
  sound: "Sound ()"
  editing {
    editor {
      name: "John Gilbert"
    }
    comments: "Editing ()"
  }
  visual_effects: "Visual Effects ()"
  production_design: "Production Design ()"
  makeup: "Makeup ()"
  costumes: "Costumes ()"
  plot_structure: "Plot Structure "
  pacing: "Pacing "
  climax: "climax "
  tone: "tone"
  final_notes: ""
  overall: "Overall, "
}
release_year: 2001
review_date: "05/30/2022"
redux: false
