title: "The Blair Witch Project"
rating: 2.0
review: "Not scary at all, Terrible Acting, Story was not even scary, Everyone is whining, Good job for them to have such a shitty movie make enough publicity to make the amount of money they made."
release_year: 1999
review_date: "06/02/2017"
redux: false
id: 26
imdb_id: "tt0185937"
