title: "The Town"
rating: 0.1
review {
  direction {
    director {
      name: "Ben Affleck"
    }
    rating: "TODO"
    comments: "macroscale is; microscale is; direction of actors is; storytelling is; tension is"
  }
  acting {
    performance {
      actor {
        name: "Ben Affleck"
      }
      rating: "TODO"
      comments: "TODO"
    }
    performance {
      actor {
        name: "Rebecca Hall"
      }
      rating: "TODO"
      comments: "TODO"
    }
    performance {
      actor {
        name: "Jon Hamm"
      }
      rating: "TODO"
      comments: "TODO"
    }
    performance {
      actor {
        name: "Jeremy Renner"
      }
      rating: "TODO"
      comments: "TODO"
    }
    performance {
      actor {
        name: "Blake Lively"
      }
      rating: "TODO"
      comments: "TODO"
    }
    performance {
      actor {
        name: "Titus Welliver"
      }
      rating: "TODO"
      comments: "TODO"
    }
    performance {
      actor {
        name: "Pete Postlethwaite"
      }
      rating: "TODO"
      comments: "TODO"
    }
    performance {
      actor {
        name: "Chris Cooper"
      }
      rating: "TODO"
      comments: "TODO"
    }
    cast {
      rating: "TODO"
      comments: "TODO"
    }
    rating: ""
  }
  story {
    writer {
      name: "Peter Craig"
    }
    writer {
      name: "Ben Affleck"
    }
    writer {
      name: "Aaron Stockard"
    }
    rating: "TODO"
    comments: "The concept is; the plot structure is; flow between sequences is; character writing is"
  }
  screenplay {
    writer {
      name: "Peter Craig"
    }
    writer {
      name: "Ben Affleck"
    }
    writer {
      name: "Aaron Stockard"
    }
    rating: "TODO"
    comments: "The dialogue is; the humor is; the symbolism is; the foreshadowing is"
  }
  score {
    composer {
      name: "David Buckley"
    }
    composer {
      name: "Harry Gregson-Williams"
    }
    rating: "TODO"
    comments: "TODO"
  }
  cinematography {
    cinematographer {
      name: "Robert Elswit"
    }
    rating: "TODO"
    comments: "TODO"
  }
  editing {
    editor {
      name: "Dylan Tichenor"
    }
    rating: "TODO"
    comments: "TODO"
  }
  sound {
    rating: "TODO"
    comments: "TODO"
  }
  visual_effects {
    rating: "TODO"
    comments: "TODO"
  }
  production_design {
    rating: "TODO"
    comments: "TODO"
  }
  makeup {
    rating: "TODO"
    comments: "TODO"
  }
  costumes {
    rating: "TODO"
    comments: "TODO"
  }
  pacing: "Pacing "
  climax: "Climax "
  tone: "Tone "
  final_notes: ""
  overall: "Overall, "
}
release_year: 2010
review_date: "04/20/2024"
redux: true
id: 156
imdb_id: "tt0840361"
