title: "The Order"
rating: 8.1
review {
  direction {
    director {
      name: "Justin Kurzel"
    }
    rating: "Good"
    comments: "The direction on a macroscale feels grand as they have these big panning shots to show the beauty in the seclusion of the Pacific Northwest, and he does a good job building the thrilling nature of the action scenes; the direction on a microscale is good as these moments are where you really get to know the characters and their relationships with each other; the storytelling is good as it follows events that really happened, but uses your emotional investment with these characters to make you care about what happens next; he builds tension very well as this is what makes the action sequences feel very thrilling"
  }
  acting {
    performance {
      actor {
        name: "Jude Law"
      }
      rating: "Good"
      comments: "Commands the movie with his presence and carries himself well in the action sequences; builds chemistry well with his castmates"
    }
    performance {
      actor {
        name: "Nicholas Hoult"
      }
      rating: "Good"
      comments: "Plays the antagonist well, as you get a sense of who the character was in real life"
    }
    performance {
      actor {
        name: "Tye Sheridan"
      }
      rating: "Pretty Good"
      comments: "Plays the sidekick role well and has good chemistry with Law"
    }
    cast {
      rating: "Pretty Good"
      comments: "Everyone plays their role well and helps support moving the story forward and the main cast"
    }
    rating: "Pretty Good to Good"
  }
  story {
    writer {
      name: "Zach Baylin"
    }
    rating: "Pretty Good to Good"
    comments: "The concept is good, as is a historical crime thriller on \"The Order\", a white nationalist group that is not really heard of that much; the plot structure is good, as it goes through the rise and fall of \"The Order\"; character writing is good for the real-life characters, as it does a good job accurately depicting how they were in real life, but pretty bad for the composite characters, as they are pretty void of anything that makes you care for them"
  }
  screenplay {
    writer {
      name: "Zach Baylin"
    }
    rating: "Pretty Good to Good"
    comments: "The dialogue is good and crisp, and does a good job in painting who these people actually were, but feels a bit overt when they are trying to make modern references to storming the capital; the biopic does a good job in bringing to light the rise in white nationalism in the 1980s, \"The Order,\" and \"The Turner Diaries,\" and the parallels between this and January 6th; the foreshadowing is good, but mostly follows what happened in real life"
  }
  score {
    composer {
      name: "Jed Kurzel"
    }
    rating: "Good"
    comments: "It is used very well in conjunction with the cinematic nature shots to show the seclusion in the environment, and helps make the thriller tense in the more action-based scenes"
  }
  cinematography {
    cinematographer {
      name: "Adam Arkapaw"
    }
    rating: "Good to very Good"
    comments: "It had really beautiful shots to help show the seclusion of the Pacific Northwest and used them well in the action sequences"
  }
  editing {
    editor {
      name: "Nick Fenton"
    }
    rating: "Good"
    comments: "Felt polished and helped put together the action sequences"
  }
  sound {
    rating: "Very Good"
    comments: "Felt very clear and authentic to the action sequences and helped make the thriller tense in the right moments; helped also show the seclusion in some moments"
  }
  visual_effects {
    rating: "Good"
    comments: "Good use of practical effects in the action sequences"
  }
  production_design {
    rating: "Good"
    comments: "Really helped show the beauty and seclusion of the Pacific Northwest"
  }
  pacing: "Pacing is good"
  climax: "The climax is executed well as it feels like a culmination of all the tension that was building throughout the movie"
  tone: "Tone is similar to that of a historical crime thriller, which is what this movie is"
  final_notes: "I saw the premiere at the Austin Film Festival"
  overall: "Overall, good historical crime thriller that exposes the unknown history of \"The Order\" in the 1980s;  the film does a very good job showcasing the beauty of the Pacific Northwest through its cinematography and creates an engaging thriller based on real events, but the movie is held back by its pretty shallow composite characters and overt parallels to modern-day events"
}
release_year: 2024
review_date: "10/27/2024"
redux: false
id: 502
imdb_id: "tt26625693"
