title: "The Social Network"
rating: 9.5
review: "Incredible Direction, Incredible Acting by the cast overall (Really enjoyed Andrew Garfield\'s performance more than Jesse Eisenberg\'s), Incredible to Brilliant Screenplay, Incredible Story, Brilliant Score, Great Cinematography, Great Editing, The pacing is good for the first half but becomes very rushed in the second half (Feels fast but just mimics the nature of a startup) but the ending is very abrupt (Though that is how it is in the book it is based off of so I cannot fully fault), There is a build to a very abrupt ending that is kinda anticlimactic. Overall, Incredible representation of startup culture and college entrepreneurship overall as this movie will become a classic worth studying in the future."
release_year: 2010
review_date: "08/23/2020"
redux: false
