title: "The Order"
rating: 0.1
review {
  direction {
    director {
      name: "Justin Kurzel"
    }
    rating: "TODO"
    comments: "macroscale is; microscale is; direction of actors is; storytelling is; tension is"
  }
  acting {
    performance {
      actor {
        name: "Jude Law"
      }
      rating: "TODO"
      comments: "TODO"
    }
    performance {
      actor {
        name: "Nicholas Hoult"
      }
      rating: "TODO"
      comments: "TODO"
    }
    performance {
      actor {
        name: "Tye Sheridan"
      }
      rating: "TODO"
      comments: "TODO"
    }
    performance {
      actor {
        name: "Jurnee Smollett"
      }
      rating: "TODO"
      comments: "TODO"
    }
    performance {
      actor {
        name: "Alison Oliver"
      }
      rating: "TODO"
      comments: "TODO"
    }
    performance {
      actor {
        name: "Marc Maron"
      }
      rating: "TODO"
      comments: "TODO"
    }
    cast {
      rating: "TODO"
      comments: "TODO"
    }
    rating: "TODO"
  }
  story {
    writer {
      name: "Zach Baylin"
    }
    rating: "TODO"
    comments: "The concept is; the plot structure is; flow between sequences is; character writing is"
  }
  screenplay {
    writer {
      name: "Zach Baylin"
    }
    rating: "TODO"
    comments: "The dialogue is; the humor is; the symbolism is; the foreshadowing is"
  }
  score {
    composer {
      name: "Jed Kurzel"
    }
    rating: "TODO"
    comments: "TODO"
  }
  cinematography {
    cinematographer {
      name: "Adam Arkapaw"
    }
    rating: "TODO"
    comments: "TODO"
  }
  editing {
    editor {
      name: "Nick Fenton"
    }
    rating: "TODO"
    comments: "TODO"
  }
  sound {
    rating: "TODO"
    comments: "TODO"
  }
  visual_effects {
    rating: "TODO"
    comments: "TODO"
  }
  production_design {
    rating: "TODO"
    comments: "TODO"
  }
  costumes {
    rating: "TODO"
    comments: "TODO"
  }
  pacing: "Pacing "
  climax: "Climax "
  tone: "Tone "
  final_notes: ""
  overall: "Overall, "
}
release_year: 2024
review_date: "10/27/2024"
redux: false
id: 502
imdb_id: "tt26625693"

* Premeire at Austin Film Festival