title: "The Big Short"
rating: 8.1
review: "Very good acting from core members, very good story, good screenplay, very entertaining, Tries to be very educational but falls at times it needs to be, only after a while do u understand what\'s going on."
release_year: 2015
review_date: "09/18/2017"
redux: false
