title: "The Truman Show"
rating: 9.5
review: "Excellent Movie. Incredible Screenplay, Incredible Acting, Decent Score, The best Cinematography out of any movie I have ever seen. Incredible Story and Ending."
release_year: 1998
review_date: "10/28/2018"
redux: false
id: 75
imdb_id: "tt0120382"
