title: "The Seed of the Sacred Fig"
rating: 0.1
review {
  direction {
    director {
      name: "Mohammad Rasoulof"
    }
    rating: "TODO"
    comments: "macroscale is; microscale is; direction of actors is; storytelling is; tension is"
  }
  acting {
    performance {
      actor {
        name: "Soheila GolestaniMissagh ZarehMahsa RostamiSetareh MalekiNiousha AkhshiAmineh Arani"
      }
      rating: "TODO"
      comments: "TODO"
    }
    cast {
      rating: "TODO"
      comments: "TODO"
    }
    rating: "TODO"
  }
  story {
    writer {
      name: "Mohammad Rasoulof"
    }
    rating: "TODO"
    comments: "The concept is; the plot structure is; flow between sequences is; character writing is"
  }
  screenplay {
    writer {
      name: "Mohammad Rasoulof"
    }
    rating: "TODO"
    comments: "The dialogue is; the humor is; the symbolism is; the foreshadowing is"
  }
  score {
    composer {
      name: "Karzan Mahmood"
    }
    rating: "TODO"
    comments: "TODO"
  }
  cinematography {
    cinematographer {
      name: "Pooyan Aghababaei"
    }
    rating: "TODO"
    comments: "TODO"
  }
  editing {
    editor {
      name: "Andrew Bird"
    }
    rating: "TODO"
    comments: "TODO"
  }
  sound {
    rating: "TODO"
    comments: "TODO"
  }
  pacing: "Pacing "
  climax: "Climax "
  tone: "Tone "
  final_notes: ""
  overall: "Overall, "
}
release_year: 2024
review_date: "10/28/2024"
redux: false
id: 503
imdb_id: "tt32178949"

* Premeire at Austin Film Festival