title: "The Silence of the Lambs"
rating: 8.4
review: "Incredible Acting, Great Story, Great Screenplay, Score clashed with the movie, Not that Scary."
release_year: 1991
review_date: "07/27/2018"
redux: false
id: 68
imdb_id: "tt0102926"
