title: "The Spongebob Squarepants Movie"
rating: 9.9
review: "The embodiment and magnum opus of Spongebob Squarepants that has some of the happiest and saddest moments (You know the scene) witnessed during my childhood."
release_year: 2004
review_date: "05/28/2021"
redux: false
id: 194
imdb_id: "tt0345950"
