title: "The Texas Chain Saw Massacre"
rating: 5.0
review: "Extremely Boring, Acting very bad, Story not that good, Not scary at all, Very predictable scares, No coherent plot, Very short, The only good scene of the movie was the very last scene (and this is more iconic than great)"
release_year: 1974
review_date: "11/21/2019"
redux: false
