title: "The Two Popes"
rating: 8.7
review: "Great Acting and Chemistry by the two leads, Great Screenplay, Great Cinematography as it had the feel of a Documentary, The movie really has no plot as it can be boiled down into 3 scenes, Good Direction"
release_year: 2019
review_date: "01/05/2020"
redux: false
