title: "The Lord of the Rings: The Fellowship of the Ring"
rating: 9.3
review {
  direction {
    director {
      name: "Peter Jackson"
    }
    rating: "Great to Incredible"
    comments: "Really moves the story forward and gets the best out of his actors as it drives the audience to be enticed with what happens next throughout the story"
  }
  acting {
    cast {
      rating: "Great"
      comments: "No one performance stands out as everyone acts as a unit to progress the story forward"
    }
    rating: "Great"
  }
  story {
    writer {
      name: "Fran Walsh"
    }
    writer {
      name: "Philippa Boyens"
    }
    writer {
      name: "Peter Jackson"
    }
    rating: "Great to Incredible"
    comments: "Really captivating on seeing how the journey progresses as we see the Fellowship go on this quest to Mordor, also the different elements of the story are very important as they comeback to play a role in the film"
  }
  screenplay {
    writer {
      name: "Fran Walsh"
    }
    writer {
      name: "Philippa Boyens"
    }
    writer {
      name: "Peter Jackson"
    }
    rating: "Great"
    comments: "While the very \"Middle English\"-esque text is hard to follow sometimes, the actual dialogue is very well written as we see the director use it well to help tell the story (especially in the narration parts); also, the symbolism throughout the movie (specifically, about a boy who is trying to grow up and be a hero trope)"
  }
  score {
    composer {
      name: "Howard Shore"
    }
    rating: "Great"
    comments: "With memorable themes"
  }
  cinematography {
    cinematographer {
      name: "Andrew Lesnie"
    }
    rating: "Pretty Good"
    comments: "While for the most part it was very good at capturing the scenes, I found the slow-shaky shots incredibly annoying"
  }
  editing {
    editor {
      name: "John Gilbert"
    }
    rating: "Very Good"
  }
  sound {
    rating: "Very Good"
  }
  visual_effects {
    rating: "Great"
    comments: "While there were some hiccups, the CGI was incredible for its time"
  }
  production_design {
    rating: "Great"
  }
  makeup {
    rating: "Great"
  }
  costumes {
    rating: "Very Good"
  }
  plot_structure: "Plot Structure was well laid out as it is about a 1/3 of a full-length story (and treats it as such with all the elements of a solo movie, yet still taking into account there is more to go)"
  pacing: "Pacing was very fast (especially for a movie that is 3 hours long) as it felt like they were trying to fit so much in (which does make sense given how dense the books are)"
  climax: "Build to climax was good as we get to see them embark on one arc of their journey to Mordor; climax was well executed as we get to see the sacrifices the characters have to make to go on their quest"
  tone: "Tone was stereotypical of the fantasy genre (as it treated as such)"
  final_notes: "Given this movie is the first of three parts Peter Jackson does a great job in setting the story and the conflict that the other movies will take off from as we see the internal struggles present in all the characters and the importance of what is needed to be done from the quest (so it is acceptable to treat the movie as an overall exposition even though it has elements of a solo movie)"
  overall: "Overall, a great introduction into the Lord of the Rings Trilogy as the execution and different parts are well done to start this epic story off as the audience is left wanting more from the characters and the story as they transition into the next part"
}
release_year: 2001
review_date: "05/30/2022"
redux: false
id: 259
imdb_id: "tt0120737"
