title: "The Favourite"
rating: 7.8
review: "Both one of the best movies of the year and one of the worst movies of the year. Incredible Acting, Funny wit and humor, story has like no continuity, at times very dry, Great pacing up until the end."
release_year: 2018
review_date: "02/23/2019"
redux: false
id: 82
imdb_id: "tt5083738"
