title: "The Master"
rating: 9.1
review: "Incredible Acting by the entire case (Especially Joaquin Phoenix and Philip Seymour Hoffman), Great Screenplay, Good Story, Great Direction, Great Score, Incredible Cinematography, Very Surface level in terms of its meanings as I would like it to have gone a bit deeper in its symbolism and its criticisms of the cult, Lot of unnecessarily weird dialogue."
release_year: 2012
review_date: "06/07/2020"
redux: false
id: 135
imdb_id: "tt1560747"
