title: "The Virgin Suicides"
rating: 4.7
review: "Very Stupid Movie, Decent Acting, Bad Story, Bad Screenplay, Plot is pointless considering it sets up things that are just never revisited or solved, Narrative was inconsistent with its storytelling and structure, with the point of the movie to rationalize the suicides and the narrator saying he did not know it was pretty obvious to why they killed themselves, very boring overall in terms of the plot and story, inaccurate portrayal of mental illness, has Danny Devito though."
release_year: 1999
review_date: "06/17/2020"
redux: false
id: 138
imdb_id: "tt0159097"
