title: "The Fast and the Furious: Tokyo Drift"
rating: 4.2
review: "Decent Story, Terrible Acting except for Sung Kang, Terrible Screenplay, action scenes were ok, the Only incredible thing about this movie was the song Toyko Drift."
release_year: 2006
review_date: "11/21/2019"
redux: false
id: 107
imdb_id: "tt0463985"
