title: "The Full Monty"
rating: 9.0
review: "Very Funny, Great Acting by the main cast (Great Chemsitry between all the members), Decent acting by supporting cast, Very Good Direction, Great Screenplay, Good Story, Great thematic elements of real world issues disgused in a Comedy, Good score, pacing felt very rushed and completely off because this movie was too short (I would have liked to see 15-20 more mins of the movie), The plot structure was way too focused on the final 40 minutes because of the shortness of the movie."
release_year: 1997
review_date: "06/29/2020"
redux: false
