title: "The Irishman"
rating: 8.8
review: "Incredible Acting by the cast as a whole (Best was top 3 and Pacino especially), Great Direction, Great Screenplay, Great Story, Movie is Way too long, The pace is both slow and fast at the same time (The actual pace of the movie is very slow but the details of the movie are presented very fast), it is a very dense movie and is a very slow burn, Great Movie overall."
release_year: 2019
review_date: "01/03/2020"
redux: false
