title: "The Social Dilemma"
review: "Great Topics that are complex but presented in a very simple manner that makes it easy to digest, Expert tesitmony of the documentary is very good as it brings in a lot of industry experience and credibility to persuade the audience to change how they view social media and technology, I felt they brushed on topics they should've discussed more (Like mental health), the skits were very poorly written and acted and they really drew away from the message of the documentary as they were very unrealistic, the message of the documentary was a little too pessimistic of what may actually happen. Overall, thought the ideas were very well presented but the skits and ending message really hold this documentary back from making a strong impact on the relationship between social media and society."
release_year: 2020
review_date: "11/22/2020"
redux: false
