title: "The Lord of the Rings: The Two Towers"
rating: 8.5
review {
  direction {
    director {
      name: "Peter Jackson"
    }
    comments: "Very Good to Great Direction (Takes a step back from the previous movie as this movie is more about moving the story forward (which is does a great job at) but introduces many new things in this film that it is a bit hard to follow at times)"
  }
  acting {
    cast: "All the performances still act as pieces to a larger part but they are not as powerful as they were in the first film (specifically Gandolf) but Gollum did improve in this movie substantially"
    comments: "Very Good Acting"
  }
  story {
    writer {
      name: "Fran Walsh"
    }
    writer {
      name: "Philippa Boyens"
    }
    writer {
      name: "Stephen Sinclair"
    }
    writer {
      name: "Peter Jackson"
    }
    comments: "Good to Very Good Story (The story is still very captivating but there are so many parallel plots going that introduce new story elements so quickly that is a bit confusing at times on what is happening)"
  }
  screenplay {
    writer {
      name: "Fran Walsh"
    }
    writer {
      name: "Philippa Boyens"
    }
    writer {
      name: "Stephen Sinclair"
    }
    writer {
      name: "Peter Jackson"
    }
    comments: "Great Screenplay (Similar to the first film; while the very \"Middle English\"-esque text is hard to follow sometimes, the actual dialogue is very well written as we see the director use it well to help tell the story (especially in the narration parts); also, the symbolism throughout the movie (specifically, about a boy who is trying to grow-up and be a hero trope))"
  }
  score {
    composer {
      name: "Howard Shore"
    }
    comments: "Great Score (with memorable themes, and actually may be a bit better this movie)"
  }
  cinematography {
    cinematographer {
      name: "Andrew Lesnie"
    }
    comments: "Very Good Cinematography (An improvement from the last film as there are more grandiose shots that are well executed)"
  }
  sound: "Great Sound"
  editing {
    editor {
      name: "Michael J. Horton"
    }
    comments: "Very Good to Great Editing"
  }
  visual_effects: "Very Good Visual Effects (For the most part the CGI is good but there are more noticeable hiccups in this movie than the previous (especially in the mix between Live-Action and CGI))"
  production_design: "Great Production Design"
  makeup: "Great Makeup"
  costumes: "Very Good Costumes"
  plot_structure: "Plot Structure just feels like it is moving the story forward and not like a separate film in the trilogy (like the first film) so there really is no typical plot structure"
  pacing: "Pacing was very fast (especially for a movie that is 3 hours long) as it felt like they were trying to fit so much in (which does make sense given how dense the books are) but unlike the last film I do not think it does as good of a job as it did in the previous one"
  climax: "Build to climax was good as it builds up to different epic battles that the characters must fight; climax was well executed as it goes between the different story line climaxes very well to keep the audience engaged"
  tone: "Tone was stereotypical of the fantasy genre (as it treated as such)"
  final_notes: "This movie feels more like it is moving the story forward in the trilogy (the rising action/building the overall conflict) so it should be treated as such (making it less of a stand alone movie as the previous one)"
  overall: "Overall, a movie that is more about building the story in the trilogy rather than being experienced on its own with it more concerned about transitioning to the next part to see how the trilogy concludes (which makes it not hit the mark as well as the previous one)"
}
release_year: 2002
review_date: "06/28/2022"
redux: false
id: 269
imdb_id: "tt0167261"
