title: "The Help"
rating: 6.3
review: "Good movie, acting was good (Spencer and Davis were very good), Screenplay was Pretty Good, story was good."
release_year: 2011
review_date: "10/20/2017"
redux: false
id: 49
imdb_id: "tt1454029"
