title: "The Brutalist"
rating: 0.1
review {
  direction {
    director {
      name: "Brady Corbet"
    }
    rating: "TODO"
    comments: "macroscale is; microscale is; direction of actors is; storytelling is; tension is"
  }
  acting {
    performance {
      actor {
        name: "Adrien Brody"
      }
      rating: "TODO"
      comments: "TODO"
    }
    performance {
      actor {
        name: "Felicity Jones"
      }
      rating: "TODO"
      comments: "TODO"
    }
    performance {
      actor {
        name: "Guy Pearce"
      }
      rating: "TODO"
      comments: "TODO"
    }
    performance {
      actor {
        name: "Joe Alwyn"
      }
      rating: "TODO"
      comments: "TODO"
    }
    performance {
      actor {
        name: "Raffey Cassidy"
      }
      rating: "TODO"
      comments: "TODO"
    }
    performance {
      actor {
        name: "Stacy Martin"
      }
      rating: "TODO"
      comments: "TODO"
    }
    performance {
      actor {
        name: "Emma Laird"
      }
      rating: "TODO"
      comments: "TODO"
    }
    performance {
      actor {
        name: "Isaach de Bankol\303\251"
      }
      rating: "TODO"
      comments: "TODO"
    }
    performance {
      actor {
        name: "Alessandro Nivola"
      }
      rating: "TODO"
      comments: "TODO"
    }
    cast {
      rating: "TODO"
      comments: "TODO"
    }
    rating: "TODO"
  }
  story {
    writer {
      name: "Brady Corbet"
    }
    writer {
      name: "Mona Fastvold"
    }
    rating: "TODO"
    comments: "The concept is; the plot structure is; flow between sequences is; character writing is"
  }
  screenplay {
    writer {
      name: "Brady Corbet"
    }
    writer {
      name: "Mona Fastvold"
    }
    rating: "TODO"
    comments: "The dialogue is; the humor is; the symbolism is; the foreshadowing is"
  }
  score {
    composer {
      name: "Daniel Blumberg"
    }
    rating: "TODO"
    comments: "TODO"
  }
  cinematography {
    cinematographer {
      name: "Lol Crawley"
    }
    rating: "TODO"
    comments: "TODO"
  }
  editing {
    editor {
      name: "D\303\241vid Jancs\303\263"
    }
    rating: "TODO"
    comments: "TODO"
  }
  sound {
    rating: "TODO"
    comments: "TODO"
  }
  visual_effects {
    rating: "TODO"
    comments: "TODO"
  }
  production_design {
    rating: "TODO"
    comments: "TODO"
  }
  makeup {
    rating: "TODO"
    comments: "TODO"
  }
  costumes {
    rating: "TODO"
    comments: "TODO"
  }
  pacing: "Pacing "
  climax: "Climax "
  tone: "Tone "
  final_notes: ""
  overall: "Overall, "
}
release_year: 2024
review_date: "10/26/2024"
redux: false
id: 500
imdb_id: "tt8999762"

* Premeire at Austin Film Festival
* Modern Day Godfather