title: "The Notebook"
rating: 5.1
review: "Bad direction, Pretty good story, very bad screenplay, Acting was pretty bad overall (Only the elder characters were decent while everyone else was very bad), Pretty Bad score, Zero chemistry between the two leads which shows how there is barely any emotion from the flashback scenes, elderly couple shows decent chemistry and emotion which is a saving grace for the film (But like barely), the movie lays out as if there is going to be a twist but then spoils it midway through the movie which makes it very wasted, decent pacing, Movie was probably made by an angsty teen who wanted to get into NYU film school couldn\'t."
release_year: 2004
review_date: "08/07/2020"
redux: false
id: 152
imdb_id: "tt0332280"
