title: "This is the End"
rating: 9.2
review {
  direction {
    director {
      name: "Seth Rogen"
    }
    director {
      name: "Evan Goldberg"
    }
    comments: "Direction ()"
  }
  acting {
    actor {
      name: "James Franco"
      comments: " from James Franco ()"
    }
    actor {
      name: "Jonah Hill"
      comments: " from Jonah Hill ()"
    }
    actor {
      name: "Seth Rogen"
      comments: " from Seth Rogen ()"
    }
    actor {
      name: "Jay Baruchel"
      comments: " from Jay Baruchel ()"
    }
    actor {
      name: "Danny McBride"
      comments: " from Danny McBride ()"
    }
    actor {
      name: "Craig Robinson"
      comments: " from Craig Robinson ()"
    }
    actor {
      name: "Michael Cera"
      comments: " from Michael Cera ()"
    }
    actor {
      name: "Emma Watson"
      comments: " from Emma Watson ()"
    }
    cast: "from the rest of the cast ()"
    comments: " Acting "
  }
  story {
    writer {
      name: "Seth Rogen"
    }
    writer {
      name: "Evan Goldberg"
    }
    comments: "Story ()"
  }
  screenplay {
    writer {
      name: "Seth Rogen"
    }
    writer {
      name: "Evan Goldberg"
    }
    comments: "Screenplay ()"
  }
  score {
    composer {
      name: "Henry Jackman"
    }
    comments: "Score ()"
  }
  cinematography {
    cinematographer {
      name: "Brandon Trost"
    }
    comments: "Cinematography ()"
  }
  sound: "Sound ()"
  editing {
    editor {
      name: "Zene Baker"
    }
    comments: "Editing ()"
  }
  visual_effects: "Visual Effects ()"
  production_design: "Production Design ()"
  makeup: "Makeup ()"
  costumes: "Costumes ()"
  plot_structure: "Plot Structure "
  pacing: "Pacing "
  climax: "climax "
  tone: "tone"
  final_notes: ""
  overall: "Overall, "
}
release_year: 2013
review_date: "03/16/2022"
redux: false
