title: "Thor: Love and Thunder"
rating: 5.0
review {
  direction {
    director {
      name: "Taika Waititi"
    }
    rating: "Bad"
    comments: "Really tries too hard to be funny and really is chaotic with trying to progress the story forward"
  }
  acting {
    performance {
      actor {
        name: "Chris Hemsworth"
      }
      rating: "Very Good"
      comments: "Really shows the experience he has with the character and effortlessly is able to command every scene he is in"
    }
    performance {
      actor {
        name: "Christian Bale"
      }
      rating: "Very Good"
      comments: "Really shows the level of dedication he goes through as an actor as he is very captivating even in this villainous role"
    }
    performance {
      actor {
        name: "Tessa Thompson"
      }
      rating: "Pretty Good"
      comments: "A good comedic relief that is menacing this time around and picks up where she left off from the previous film"
    }
    performance {
      actor {
        name: "Taika Waititi"
      }
      rating: "Decent to Pretty Good"
      comments: "Plays the comedic relief character and has his ups and down given the script he wrote"
    }
    performance {
      actor {
        name: "Russell Crowe"
      }
      rating: "Pretty bad"
      comments: "Really was not that convincing as Zeus as his acting was not there and his accent really did not sit right (which is surprising because this role was really written for him)"
    }
    performance {
      actor {
        name: "Natalie Portman"
      }
      rating: "Decent to Pretty Good"
      comments: "Tries a bit too hard in this performance and really falters when it comes to the emotional side of the character (something that is surprising to me given her experience)"
    }
    performance {
      actor {
        name: "Matt Damon"
      }
      rating: "Very Good"
      comments: "It was really funny how he is able to carry on his cameo from the previous movie and have such a small role even though how big he is"
    }
    cast {
      rating: "Pretty Bad to Decent"
      comments: "Though Good from the Guardians of the Galaxy (really just stayed on brand for their characters given how short of screen time they had)"
    }
    rating: "Pretty Good to Good"
  }
  story {
    writer {
      name: "Taika Waititi"
    }
    writer {
      name: "Jennifer Kaytin Robinson"
    }
    rating: "Pretty Bad"
    comments: "The overarching story was not that bad as it deals with Thor post Avengers as he is trying to come to terms with unfinished love, it is just not that well structured and the ending really is not that good; plus the general breaks from the narrative were really sloppy and not well executed (given that it was amateur style and it really was not that funny); also, for a movie that is meant to be about Thor and Jane\'s relationship it does a real bad job in helping develop it (we are kinda just thrown into what happens)"
  }
  screenplay {
    writer {
      name: "Taika Waititi"
    }
    writer {
      name: "Jennifer Kaytin Robinson"
    }
    rating: "Pretty Bad"
    comments: "The movie tries way too hard to be funny and because of it only 1/3 jokes really hit in the movie, plus most of the lines are really predictable and bland"
  }
  score {
    composer {
      name: "Michael Giacchino (score and themes)"
    }
    composer {
      name: "Nami Melumad (score)"
    }
    rating: "Pretty Good"
  }
  soundtrack {
    rating: "Pretty Good"
    comments: "Though it is really annoying how much they play Sweet Child o\' Mine throughout the movie"
  }
  cinematography {
    cinematographer {
      name: "Barry Idoine"
    }
    rating: "Good"
  }
  editing {
    editor {
      name: "Matthew Schmidt"
    }
    editor {
      name: "Peter S. Elliot"
    }
    editor {
      name: "Tim Roche"
    }
    editor {
      name: "Jennifer Vecchiarello"
    }
    rating: "Pretty Good"
  }
  sound {
    rating: "Decent"
  }
  visual_effects {
    rating: "Very Bad"
    comments: "Given the budget for the movie it is really alarming how unfinished and cartoonish it looks, it looks like they did not spend any effort to change this up before the release"
  }
  costumes {
    rating: "Good"
    comments: "Did a good job in the Asgardian armor"
  }
  plot_structure: "Plot Structure was a real mess as the movie tries to follow a simplistic Marvel structure but tries to be quirky with it with different breaks and changes that it really hurts with the execution; also the rising action in the character arcs was really poorly done and the resolution really is thrown at the audience and the ending really takes away at what it was trying to build"
  pacing: "Pacing was incredibly fast (and this is from the short runtime; the movie could have really benefited from 20-30 minutes added to help with developing and building character relationships)"
  climax: "Build to climax was fine and pretty typical of Marvel; climax was incredible formulaic and predictable to any Marvel movie"
  tone: "Tone was pretty 80s and i think he did a good job in helping build this (but is too meta at times with how it is like this)"
  final_notes: ""
  overall: "Overall, a movie that is poorly executed and cannot be saved with Thor\'s charm as it tries too hard to be funny with its meta jokes and constant volume of jokes (even when it mostly does not work) as this takes away from actually building a storyline that should really be developed, the relationship between Thor and Jane and how Thor comes to terms with being at the end of his character arc"
}
release_year: 2022
review_date: "07/15/2022"
redux: false
id: 279
imdb_id: "tt10648342"
