title: "Three Billboards outside Ebbing, Missouri "
rating: 8.1
review: "Great Screenplay, Incredible Acting, Great Score, Great Story, A two half film: First half is very good and the second half falls off a lot, ending was very anti-climatic."
release_year: 2017
review_date: "03/04/2018"
redux: false
