title: "Together"
rating: 0.1
review {
  direction {
    director {
      name: "Michael Shanks"
    }
    rating: "TODO"
    comments: "macroscale is; microscale is; storytelling is; tension is"
  }
  acting {
    performance {
      actor {
        name: "Dave Franco"
      }
      rating: "TODO"
      comments: "TODO"
    }
    performance {
      actor {
        name: "Alison Brie"
      }
      rating: "TODO"
      comments: "TODO"
    }
    performance {
      actor {
        name: "Damon Herriman"
      }
      rating: "TODO"
      comments: "TODO"
    }
    cast {
      rating: "TODO"
      comments: "TODO"
    }
    rating: "TODO"
  }
  story {
    writer {
      name: "Michael Shanks"
    }
    rating: "TODO"
    comments: "The concept is; the plot structure is; character writing is"
  }
  screenplay {
    writer {
      name: "Michael Shanks"
    }
    rating: "TODO"
    comments: "The dialogue is; the humor is; the symbolism is; the foreshadowing is"
  }
  score {
    composer {
      name: "Cornel Wilczek"
    }
    rating: "TODO"
    comments: "TODO"
  }
  soundtrack {
    rating: "TODO"
    comments: "TODO"
  }
  cinematography {
    cinematographer {
      name: "Germain McMicking"
    }
    rating: "TODO"
    comments: "TODO"
  }
  editing {
    editor {
      name: "Sean Lahiff"
    }
    rating: "TODO"
    comments: "TODO"
  }
  sound {
    rating: "TODO"
    comments: "TODO"
  }
  visual_effects {
    rating: "TODO"
    comments: "TODO"
  }
  production_design {
    rating: "TODO"
    comments: "TODO"
  }
  makeup {
    rating: "TODO"
    comments: "TODO"
  }
  costumes {
    rating: "TODO"
    comments: "TODO"
  }
  pacing: "Pacing "
  climax: "Climax "
  tone: "Tone "
  final_notes: ""
  overall: "Overall, "
}
release_year: 2025
review_date: "03/07/2025"
redux: false
id: 543
imdb_id: "tt31184028"
