title: "Trainspotting"
rating: 8.8
review: "This movie is basically Scottish Requiem for a dream or if catcher and the rye was told by a heroin addict. Incredible Acting, Great screenplay, Great Story, Pacing was great but would\'ve like to have seen more time added for the falling action of the movie."
release_year: 1996
review_date: "03/19/2019"
redux: false
id: 89
imdb_id: "tt0117951"
