title: "Train to Busan"
rating: 9.2
review: "Incredible Story, Great Direction, Great Translation, Incredible Emotion displayed by case and writing, Great Acting by Healthy (Infected was good but like could\'ve been better), Effects were decent (but were kinda tacky at times), Pacing was good and the final 40 minutes feel like there is just so much story that happens, Exposition could\'ve been better at setting up the prediction of an infection, Cried at the ending for how emotional it was, Good Score."
release_year: 2016
review_date: "06/20/2020"
redux: false
