title: "Uncut Gems"
rating: 9.4
review: "Incredible Acting by Adam Sandler, Incredible Direction, Incredible Screenplay, Great Story, Incredible conveying of emotion, Starts off kinda rough but the final hour of the movie was incredible, Emotions and Anxiety were conveyed incredibly, Ending was Incredible, Pacing was very fast and hectic (But I loved that), Ending was very hectic and fast cuts (liked that), The only bad thing about the movie is the score is pretty bad and only works well for the high intensity moments, Some shots and scenes were not acted well and bad."
release_year: 2019
review_date: "01/21/2020"
redux: false
