title: "Under the Skin"
rating: 1.0
review {
  direction {
    director {
      name: "Jonathan Glazer"
    }
    comments: "Direction ()"
  }
  acting {
    actor {
      name: "Scarlett Johansson"
      comments: " from Scarlett Johansson ()"
    }
    cast: "from the rest of the cast ()"
    comments: " Acting"
  }
  story {
    writer {
      name: "Walter Campbell"
    }
    writer {
      name: "Jonathan Glazer"
    }
    comments: "Story ()"
  }
  screenplay {
    writer {
      name: "Walter Campbell"
    }
    writer {
      name: "Jonathan Glazer"
    }
    comments: "Screenplay ()"
  }
  score {
    composer {
      name: "Mica Levi"
    }
    comments: "Score ()"
  }
  cinematography {
    cinematographer {
      name: "Daniel Landin"
    }
    comments: "Cinematography ()"
  }
  sound: "Sound ()"
  editing {
    editor {
      name: "Paul Watts"
    }
    comments: "Editing ()"
  }
  visual_effects: "Visual Effects ()"
  production_design: "Production Design ()"
  makeup: "Makeup ()"
  costumes: "Costumes ()"
  plot_structure: "Plot Structure "
  pacing: "Pacing (incredibly slow)"
  climax: "Climax (Intense but also anticlimactic)"
  tone: "Tone "
  final_notes: ""
  overall: "Overall, "
}
release_year: 2013
review_date: "10/18/2023"
redux: false
id: 375
imdb_id: "tt1441395"
