title: "Under the Skin"
rating: 4.5
review {
  direction {
    director {
      name: "Jonathan Glazer"
    }
    rating: "Pretty Bad"
    comments: "Good on a macro scale, bad on a micro-scale (especially with directing actors who weren\'t ScarJo), does a pretty bad job at moving the story forward as the style is just too subtle that the movie is not engaging at all"
  }
  acting {
    performance {
      actor {
        name: "Scarlett Johansson"
      }
      rating: "Pretty Good"
      comments: "More about her experiencing her world than her delivery of dialogue (though she perfected her accent), does a good job in showing someone void of emotions and experiencing emotions for the first time"
    }
    cast {
      rating: "Very Bad"
      comments: "Just a lot of inexperience and unintelligible moments, none of the actors work well off of ScarJo at all (even though it can be argued that is the point)"
    }
    rating: "Pretty Bad"
  }
  story {
    writer {
      name: "Walter Campbell"
    }
    writer {
      name: "Jonathan Glazer"
    }
    rating: "Pretty Bad"
    comments: "The story is pretty absent and really open to interpretation (which is kinda a flaw cause it is a little too empty); the movie fills a lot of time with dead space to show the protagonist experiencing her world (but this comes with the expensive of keeping the film tighter and engaging); the mystery of the main character is nice cause it helps with keeping the interpretation of the movie open"
  }
  screenplay {
    writer {
      name: "Walter Campbell"
    }
    writer {
      name: "Jonathan Glazer"
    }
    rating: "Pretty Bad to Decent"
    comments: "Very little dialogue (which really hurts with building the world but adds mystery); the dialogue that is present is not good and really unintelligible; symbolism is incredibly subtle and really open for interpretation as it uses actions and imagery to display the meaning rather than words (the entire movie is about what it means to be a human and punishing temptation); foreshadowing was present as it kinda mirrors the beginning"
  }
  score {
    composer {
      name: "Mica Levi"
    }
    rating: "Pretty Good"
    comments: "Used well in helping build suspense, and its absence also helps with building tension as well"
  }
  cinematography {
    cinematographer {
      name: "Daniel Landin"
    }
    rating: "Decent to Pretty Good"
    comments: "Good in a lot of the macro shots showing the world (or the protagonist\'s world/viewpoint), the micro shots were decent; the lighting was pretty bad as it was hard to see any of the images on scene sometimes"
  }
  editing {
    editor {
      name: "Paul Watts"
    }
    rating: "Pretty Good"
    comments: "Good when it used in the more tense and artsy scenes; the cut could\'ve been tighter as some of the scenes were way longer than it should\'ve been"
  }
  sound {
    rating: "Decent"
    comments: "A bit cheap but the movie\'s amplified sound during moments without score helps with building tension, the sound mixing of dialogue was very bad cause it was so hard to hear what anyone was saying (which may be because they were Scottish)"
  }
  visual_effects {
    rating: "Pretty Good"
    comments: "Given how low the budget was"
  }
  makeup {
    rating: "Decent"
    comments: "Especially during the \'Under the Skin\' scenes"
  }
  plot_structure: "Plot Structure was a big issue because it felt like nothing was going on (it was just the protagonist experiencing the world)"
  pacing: "Pacing was incredibly slow as the movie was very experimental in storytelling (so there was no dialogue or actions that help move the story at a reasonable pace); the runtime really could\'ve been cut by 20-30 minutes (but then that would\'ve taken away from the experimental nature of the movie)"
  climax: "Climax was intense but also anticlimactic as the scene was serious but the movie just abruptly ends"
  tone: "Tone was very ominous and sci-fi (as it helps add the mystery and experimental nature of the movie)"
  final_notes: "The movie is more of an experimental art piece about humanity than it was a narrative film"
  overall: "Overall, a very experimental movie that is an art piece about humanity and temptation told through the eyes of Scarlett Johansson\'s performance, although trading in the narrative format sacrificed the movie being engaging as there are no plot elements to drive the story forward because the movie is way too open for interpretation (and it does not help that all the performances besides the lead\'s were very bad)"
}
release_year: 2013
review_date: "10/18/2023"
redux: false
id: 373
imdb_id: "tt1441395"
