title: "Vice"
rating: 7.7
review: "Incredible Acting, Terrible Pacing, Very Sloppy structure, had an incorrect fact but for the most part was pretty spot on, good score, very funny, most disappointing movie of the year because of the potential it had."
release_year: 2018
review_date: "12/31/2018"
redux: false
id: 79
imdb_id: "tt6266538"
