title: "War for the Planet of the Apes "
rating: 9.0
review: "Very good acting (especially from Andy Serkis), very few wasted minutes of the movie, the girl really is useless in the movie, Great action, Incredible Visual Effects and Motion Capture, Great Screenplay, Very Emotional movie, Need to watch first two for story to make sense."
release_year: 2017
review_date: "07/22/2017"
redux: false
