title: "War Dogs"
rating: 7.3
review: "Like a shitter yet still entertaining Wolf of Wall Street, Miles Teller in very Miles Teller fashion, Jonah Hill steals the show like always and is very good, great story, good screenplay, ending just falls apart as it\'s forced and is dragged out. "
release_year: 2016
review_date: "07/22/2017"
redux: false
