title: "War Dogs"
rating: 7.3
review: "Like a shittier yet still entertaining Wolf of Wall Street, Miles Teller in very Miles Teller in fashion, Jonah Hill steals the show like always and is very good, great story, good screenplay, ending just falls apart as it\'s forced and is dragged out."
release_year: 2016
review_date: "07/22/2017"
redux: false
id: 38
imdb_id: "tt2005151"
