title: "We're All Gonna Die"
rating: 5.4
review: "Overall, this movie just feels as if YouTubers made a movie, which it is. The direction and writing were very similar to what you’d see from 2010s YouTube videos. The acting was very forced and inexperienced. The technicals and visual effects were very similar to 2010s YouTube videos. Saw the World Premiere at SXSW."
release_year: 2024
review_date: "03/10/2024"
redux: false
id: 425
imdb_id: "tt28055078"
