title: "Whiplash"
rating: 9.7
review {
  direction {
    director {
      name: "Damien Chazelle"
    }
    rating: "Incredible"
  }
  acting {
    performance {
      actor {
        name: "Miles Teller"
      }
      rating: "Great"
    }
    performance {
      actor {
        name: "J. K. Simmons"
      }
      rating: "Brilliant"
    }
    cast {
      rating: "Good"
    }
    rating: "Very Good to Great"
  }
  story {
    writer {
      name: "Damien Chazelle"
    }
    rating: "Brilliant"
  }
  screenplay {
    writer {
      name: "Damien Chazelle"
    }
    rating: "Brilliant"
  }
  score {
    composer {
      name: "Justin Hurwitz"
    }
    rating: "Incredible"
  }
  cinematography {
    cinematographer {
      name: "Sharone Meir"
    }
    rating: "Great"
    comments: "Brilliant use of lighting to establish mood and themes"
  }
  editing {
    editor {
      name: "Tom Cross"
    }
    rating: "Incredible"
  }
  pacing: "Pacing is Great to Incredible as it gives it a very artsy feel that slowly builds to a brilliant climax"
  climax: "climax is brilliant as it is filled with symbolism till the very last shot as JKs mouth is covered showing his recognition is all that Andrew needed to think he is one of the greats"
  final_notes: ""
  overall: "Overall, one of, if not the best, movies to show the obsession of an artist that wants to make it to the top, stopping at nothing to get there, as they are pushed past their mental breaking point to achieve their goal"
}
release_year: 2014
review_date: "12/24/2020"
redux: false
id: 172
imdb_id: "tt2582802"
