title: "Whiplash"
rating: 0.1
review {
  direction {
    director {
      name: "Damien Chazelle"
    }
    rating: "Incredible"
    comments: "macroscale is; microscale is; direction of actors is; storytelling is; tension is"
  }
  acting {
    performance {
      actor {
        name: "Miles Teller"
      }
      rating: "TODO"
      comments: "TODO"
    }
    performance {
      actor {
        name: "J. K. Simmons"
      }
      rating: "TODO"
      comments: "TODO"
    }
    performance {
      actor {
        name: "Paul Reiser"
      }
      rating: "TODO"
      comments: "TODO"
    }
    cast {
      rating: "TODO"
      comments: "TODO"
    }
    rating: "TODO"
  }
  story {
    writer {
      name: "Damien Chazelle"
    }
    rating: "TODO"
    comments: "The concept is; the plot structure is; flow between sequences is; character writing is"
  }
  screenplay {
    writer {
      name: "Damien Chazelle"
    }
    rating: "TODO"
    comments: "The dialogue is; the humor is; the symbolism is; the foreshadowing is"
  }
  score {
    composer {
      name: "Justin Hurwitz"
    }
    rating: "TODO"
    comments: "TODO"
  }
  cinematography {
    cinematographer {
      name: "Sharone Meir"
    }
    rating: "TODO"
    comments: "TODO"
  }
  editing {
    editor {
      name: "Tom Cross"
    }
    rating: "TODO"
    comments: "TODO"
  }
  sound {
    rating: "TODO"
    comments: "TODO"
  }
  visual_effects {
    rating: "TODO"
    comments: "TODO"
  }
  production_design {
    rating: "TODO"
    comments: "TODO"
  }
  makeup {
    rating: "TODO"
    comments: "TODO"
  }
  costumes {
    rating: "TODO"
    comments: "TODO"
  }
  pacing: "Pacing "
  climax: "Climax "
  tone: "Tone "
  final_notes: ""
  overall: "Overall, "
}
release_year: 2014
review_date: "09/19/2024"
redux: true
id: 172
imdb_id: "tt2582802"
