title: "Won\'t You Be My Neighbor?"
rating: 9.6
review: "Best Documentary I have every seen, Incredible in almost every way, Very Emotional and powerful."
release_year: 2018
review_date: "10/31/2018"
redux: false
id: 77
imdb_id: "tt7681902"
