title: "You Sing Loud, I Sing Louder"
rating: 5.8
review {
  direction {
    director {
      name: "Emma Westenberg"
    }
    comments: "Pretty Bad to Decent Direction (For a directorial debut on a low budget film, she makes the most out what she can as she gets a good amount from the lead two actors from a pretty minimal story; though she is a victim of her own circumstances as the low budget caps at how much she can actually get the most out of the extras and shooting the scenes; the more artsy parts of the movie were really hit or miss as some of the nature aspects were visually pleasing but the more drug induced scenes were just like a fever dream)"
  }
  acting {
    actor {
      name: "Clara McGregor"
      comments: "Pretty Good from Clara McGregor (Plays the role pretty well with only some minor hiccups as she plays off her father while still showing her own demons; there are a lot of awkward pauses in the performance but I think they may be more from the direction than the acting)"
    }
    actor {
      name: "Ewan McGregor"
      comments: "Pretty Good to Good from Ewan McGregor (Really pulls from experience for this performance as it seems like he is transcending all the actors around him, though he does work well with his daughter)"
    }
    cast: "Bad from the rest of the cast (Just a lot of inexperience and poor direction)"
    comments: "Pretty Bad to Decent Acting"
  }
  story {
    writer {
      name: "Clara McGregor"
    }
    writer {
      name: "Vera Bulder"
    }
    writer {
      name: "Ruby Caster"
    }
    comments: "Pretty Bad to Decent Story (The concept of the story is pretty good as the road trip aspects mixed with the addiction parts really help portray the message of the story; but the more micro elements that help progress the story forward were pretty bad as a lot of them felt unnecessary and did not really add too much to overall story/message)"
  }
  screenplay {
    writer {
      name: "Ruby Caster"
    }
    comments: "Pretty Bad Screenplay (The dialogue was very amateur and pretty bland overall; there were a good amount of overt symbols but there were some subtle symbols I did appreciate; the foreshadowing of the movie is pretty good)"
  }
  score {
    composer {
      name: "Raven Aartsen"
    }
    comments: "Decent to Pretty Good Score (Helped give the movie a more artsy feel)"
  }
  cinematography {
    cinematographer {
      name: "Christopher Ripley"
    }
    comments: "Pretty Bad Cinematography (Very hit or miss as some of the more shaky amateur shots made the movie incredible nauseating and hard to watch, but the more artsy shots did have some merit to them)"
  }
  sound: "Decent Sound"
  editing {
    editor {
      name: "Autumn Dae"
    }
    comments: "Pretty Bad to Decent Editing (Felt very amateurish as the movie trades in being more artsy than actually having a tighter edited movie)"
  }
  plot_structure: "Plot Structure was pretty prevalent as the different elements were laid out to show their importance to the story"
  pacing: "Pacing was a really slow as it went more for a artsy/indie feel than a more stereotypical hollywood movie (a stylistic choice I cannot really complain about); Runtime could have been cut 10-20 minutes to make the movie seem a bit more tighter and fast paced"
  climax: "Climax was a bit of a mess as it feels like there is more effort in trying to piece what we are watching rather than viewing what is actually going on for the subjects"
  tone: "Tone was very art-house as the different edited shots with the score really helped in giving this vibe"
  final_notes: "Saw World Premiere at SXSW"
  overall: "Overall, a movie that suffers from having too low of a budget as the performances by the leads cannot save this artsy/indie film as it is held back by poor acting from the rest of the cast, bland writing (though not all of it is bad), and poorly executed sequences (whether it be scenes with a lot of dead air or the climax itself)"
}
release_year: 2023
review_date: "03/19/2023"
redux: false
id: 325
imdb_id: "tt15678810"
