title: "Zodiac"
rating: 7.7
review: "Good Direction, Good Story, Decent Screenplay, Decent Score, Good Acting by the main 3 actors but the rest of the cast was pretty meh, The killing scenes were so hard to watch because of the bad acting, Good cinematography, Entertaining because of the story/subject but was kinda dry at times, The Pacing of this movie was not good cause of how it was split into two parts but the first part carried more weight than the second when it should\'ve been the opposite, The exposition was too long and the resolution was too short."
release_year: 2007
review_date: "06/14/2020"
redux: false
id: 137
imdb_id: "tt0443706"
